/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailCadenceNodeAnyOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailCadenceNodeAnyOf3{}

// MailCadenceNodeAnyOf3 struct for MailCadenceNodeAnyOf3
type MailCadenceNodeAnyOf3 struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	NextNodeId string `json:"nextNodeId"`
	TaskType string `json:"taskType"`
	Title string `json:"title"`
	AdditionalProperties map[string]interface{}
}

type _MailCadenceNodeAnyOf3 MailCadenceNodeAnyOf3

// NewMailCadenceNodeAnyOf3 instantiates a new MailCadenceNodeAnyOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailCadenceNodeAnyOf3(id string, name string, kind string, nextNodeId string, taskType string, title string) *MailCadenceNodeAnyOf3 {
	this := MailCadenceNodeAnyOf3{}
	this.Id = id
	this.Name = name
	this.Kind = kind
	this.NextNodeId = nextNodeId
	this.TaskType = taskType
	this.Title = title
	return &this
}

// NewMailCadenceNodeAnyOf3WithDefaults instantiates a new MailCadenceNodeAnyOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailCadenceNodeAnyOf3WithDefaults() *MailCadenceNodeAnyOf3 {
	this := MailCadenceNodeAnyOf3{}
	return &this
}

// GetId returns the Id field value
func (o *MailCadenceNodeAnyOf3) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MailCadenceNodeAnyOf3) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MailCadenceNodeAnyOf3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailCadenceNodeAnyOf3) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *MailCadenceNodeAnyOf3) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MailCadenceNodeAnyOf3) SetKind(v string) {
	o.Kind = v
}

// GetNextNodeId returns the NextNodeId field value
func (o *MailCadenceNodeAnyOf3) GetNextNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextNodeId
}

// GetNextNodeIdOk returns a tuple with the NextNodeId field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetNextNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextNodeId, true
}

// SetNextNodeId sets field value
func (o *MailCadenceNodeAnyOf3) SetNextNodeId(v string) {
	o.NextNodeId = v
}

// GetTaskType returns the TaskType field value
func (o *MailCadenceNodeAnyOf3) GetTaskType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskType
}

// GetTaskTypeOk returns a tuple with the TaskType field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetTaskTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskType, true
}

// SetTaskType sets field value
func (o *MailCadenceNodeAnyOf3) SetTaskType(v string) {
	o.TaskType = v
}

// GetTitle returns the Title field value
func (o *MailCadenceNodeAnyOf3) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf3) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MailCadenceNodeAnyOf3) SetTitle(v string) {
	o.Title = v
}

func (o MailCadenceNodeAnyOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailCadenceNodeAnyOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["nextNodeId"] = o.NextNodeId
	toSerialize["taskType"] = o.TaskType
	toSerialize["title"] = o.Title

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailCadenceNodeAnyOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"kind",
		"nextNodeId",
		"taskType",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailCadenceNodeAnyOf3 := _MailCadenceNodeAnyOf3{}

	err = json.Unmarshal(data, &varMailCadenceNodeAnyOf3)

	if err != nil {
		return err
	}

	*o = MailCadenceNodeAnyOf3(varMailCadenceNodeAnyOf3)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "nextNodeId")
		delete(additionalProperties, "taskType")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailCadenceNodeAnyOf3 struct {
	value *MailCadenceNodeAnyOf3
	isSet bool
}

func (v NullableMailCadenceNodeAnyOf3) Get() *MailCadenceNodeAnyOf3 {
	return v.value
}

func (v *NullableMailCadenceNodeAnyOf3) Set(val *MailCadenceNodeAnyOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableMailCadenceNodeAnyOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableMailCadenceNodeAnyOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailCadenceNodeAnyOf3(val *MailCadenceNodeAnyOf3) *NullableMailCadenceNodeAnyOf3 {
	return &NullableMailCadenceNodeAnyOf3{value: val, isSet: true}
}

func (v NullableMailCadenceNodeAnyOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailCadenceNodeAnyOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


