/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainCatchAll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainCatchAll{}

// DomainCatchAll struct for DomainCatchAll
type DomainCatchAll struct {
	CatchAll NullableBool `json:"catch_all"`
	AdditionalProperties map[string]interface{}
}

type _DomainCatchAll DomainCatchAll

// NewDomainCatchAll instantiates a new DomainCatchAll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainCatchAll(catchAll NullableBool) *DomainCatchAll {
	this := DomainCatchAll{}
	this.CatchAll = catchAll
	return &this
}

// NewDomainCatchAllWithDefaults instantiates a new DomainCatchAll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainCatchAllWithDefaults() *DomainCatchAll {
	this := DomainCatchAll{}
	return &this
}

// GetCatchAll returns the CatchAll field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *DomainCatchAll) GetCatchAll() bool {
	if o == nil || o.CatchAll.Get() == nil {
		var ret bool
		return ret
	}

	return *o.CatchAll.Get()
}

// GetCatchAllOk returns a tuple with the CatchAll field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DomainCatchAll) GetCatchAllOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.CatchAll.Get(), o.CatchAll.IsSet()
}

// SetCatchAll sets field value
func (o *DomainCatchAll) SetCatchAll(v bool) {
	o.CatchAll.Set(&v)
}

func (o DomainCatchAll) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainCatchAll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catch_all"] = o.CatchAll.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainCatchAll) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catch_all",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainCatchAll := _DomainCatchAll{}

	err = json.Unmarshal(data, &varDomainCatchAll)

	if err != nil {
		return err
	}

	*o = DomainCatchAll(varDomainCatchAll)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catch_all")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainCatchAll struct {
	value *DomainCatchAll
	isSet bool
}

func (v NullableDomainCatchAll) Get() *DomainCatchAll {
	return v.value
}

func (v *NullableDomainCatchAll) Set(val *DomainCatchAll) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainCatchAll) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainCatchAll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainCatchAll(val *DomainCatchAll) *NullableDomainCatchAll {
	return &NullableDomainCatchAll{value: val, isSet: true}
}

func (v NullableDomainCatchAll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainCatchAll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


