/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the HubSpotConfigurationOptionsResponseOptionsPipelinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HubSpotConfigurationOptionsResponseOptionsPipelinesInner{}

// HubSpotConfigurationOptionsResponseOptionsPipelinesInner struct for HubSpotConfigurationOptionsResponseOptionsPipelinesInner
type HubSpotConfigurationOptionsResponseOptionsPipelinesInner struct {
	Id string `json:"id"`
	Label string `json:"label"`
	Stages []HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner `json:"stages"`
	AdditionalProperties map[string]interface{}
}

type _HubSpotConfigurationOptionsResponseOptionsPipelinesInner HubSpotConfigurationOptionsResponseOptionsPipelinesInner

// NewHubSpotConfigurationOptionsResponseOptionsPipelinesInner instantiates a new HubSpotConfigurationOptionsResponseOptionsPipelinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHubSpotConfigurationOptionsResponseOptionsPipelinesInner(id string, label string, stages []HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner) *HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
	this := HubSpotConfigurationOptionsResponseOptionsPipelinesInner{}
	this.Id = id
	this.Label = label
	this.Stages = stages
	return &this
}

// NewHubSpotConfigurationOptionsResponseOptionsPipelinesInnerWithDefaults instantiates a new HubSpotConfigurationOptionsResponseOptionsPipelinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHubSpotConfigurationOptionsResponseOptionsPipelinesInnerWithDefaults() *HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
	this := HubSpotConfigurationOptionsResponseOptionsPipelinesInner{}
	return &this
}

// GetId returns the Id field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) SetLabel(v string) {
	o.Label = v
}

// GetStages returns the Stages field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetStages() []HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner {
	if o == nil {
		var ret []HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner
		return ret
	}

	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value
// and a boolean to check if the value has been set.
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) GetStagesOk() ([]HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stages, true
}

// SetStages sets field value
func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) SetStages(v []HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner) {
	o.Stages = v
}

func (o HubSpotConfigurationOptionsResponseOptionsPipelinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HubSpotConfigurationOptionsResponseOptionsPipelinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["stages"] = o.Stages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"stages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHubSpotConfigurationOptionsResponseOptionsPipelinesInner := _HubSpotConfigurationOptionsResponseOptionsPipelinesInner{}

	err = json.Unmarshal(data, &varHubSpotConfigurationOptionsResponseOptionsPipelinesInner)

	if err != nil {
		return err
	}

	*o = HubSpotConfigurationOptionsResponseOptionsPipelinesInner(varHubSpotConfigurationOptionsResponseOptionsPipelinesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "stages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner struct {
	value *HubSpotConfigurationOptionsResponseOptionsPipelinesInner
	isSet bool
}

func (v NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) Get() *HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
	return v.value
}

func (v *NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) Set(val *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner(val *HubSpotConfigurationOptionsResponseOptionsPipelinesInner) *NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner {
	return &NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner{value: val, isSet: true}
}

func (v NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHubSpotConfigurationOptionsResponseOptionsPipelinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


