/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailConversationEntryLastErrorAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailConversationEntryLastErrorAnyOf{}

// MailConversationEntryLastErrorAnyOf struct for MailConversationEntryLastErrorAnyOf
type MailConversationEntryLastErrorAnyOf struct {
	Code string `json:"code"`
	Message string `json:"message"`
	Outcome string `json:"outcome"`
	RetryAfterMs *float32 `json:"retryAfterMs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MailConversationEntryLastErrorAnyOf MailConversationEntryLastErrorAnyOf

// NewMailConversationEntryLastErrorAnyOf instantiates a new MailConversationEntryLastErrorAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailConversationEntryLastErrorAnyOf(code string, message string, outcome string) *MailConversationEntryLastErrorAnyOf {
	this := MailConversationEntryLastErrorAnyOf{}
	this.Code = code
	this.Message = message
	this.Outcome = outcome
	return &this
}

// NewMailConversationEntryLastErrorAnyOfWithDefaults instantiates a new MailConversationEntryLastErrorAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailConversationEntryLastErrorAnyOfWithDefaults() *MailConversationEntryLastErrorAnyOf {
	this := MailConversationEntryLastErrorAnyOf{}
	return &this
}

// GetCode returns the Code field value
func (o *MailConversationEntryLastErrorAnyOf) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *MailConversationEntryLastErrorAnyOf) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *MailConversationEntryLastErrorAnyOf) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *MailConversationEntryLastErrorAnyOf) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MailConversationEntryLastErrorAnyOf) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MailConversationEntryLastErrorAnyOf) SetMessage(v string) {
	o.Message = v
}

// GetOutcome returns the Outcome field value
func (o *MailConversationEntryLastErrorAnyOf) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *MailConversationEntryLastErrorAnyOf) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *MailConversationEntryLastErrorAnyOf) SetOutcome(v string) {
	o.Outcome = v
}

// GetRetryAfterMs returns the RetryAfterMs field value if set, zero value otherwise.
func (o *MailConversationEntryLastErrorAnyOf) GetRetryAfterMs() float32 {
	if o == nil || IsNil(o.RetryAfterMs) {
		var ret float32
		return ret
	}
	return *o.RetryAfterMs
}

// GetRetryAfterMsOk returns a tuple with the RetryAfterMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailConversationEntryLastErrorAnyOf) GetRetryAfterMsOk() (*float32, bool) {
	if o == nil || IsNil(o.RetryAfterMs) {
		return nil, false
	}
	return o.RetryAfterMs, true
}

// HasRetryAfterMs returns a boolean if a field has been set.
func (o *MailConversationEntryLastErrorAnyOf) HasRetryAfterMs() bool {
	if o != nil && !IsNil(o.RetryAfterMs) {
		return true
	}

	return false
}

// SetRetryAfterMs gets a reference to the given float32 and assigns it to the RetryAfterMs field.
func (o *MailConversationEntryLastErrorAnyOf) SetRetryAfterMs(v float32) {
	o.RetryAfterMs = &v
}

func (o MailConversationEntryLastErrorAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailConversationEntryLastErrorAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["outcome"] = o.Outcome
	if !IsNil(o.RetryAfterMs) {
		toSerialize["retryAfterMs"] = o.RetryAfterMs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailConversationEntryLastErrorAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailConversationEntryLastErrorAnyOf := _MailConversationEntryLastErrorAnyOf{}

	err = json.Unmarshal(data, &varMailConversationEntryLastErrorAnyOf)

	if err != nil {
		return err
	}

	*o = MailConversationEntryLastErrorAnyOf(varMailConversationEntryLastErrorAnyOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		delete(additionalProperties, "outcome")
		delete(additionalProperties, "retryAfterMs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailConversationEntryLastErrorAnyOf struct {
	value *MailConversationEntryLastErrorAnyOf
	isSet bool
}

func (v NullableMailConversationEntryLastErrorAnyOf) Get() *MailConversationEntryLastErrorAnyOf {
	return v.value
}

func (v *NullableMailConversationEntryLastErrorAnyOf) Set(val *MailConversationEntryLastErrorAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMailConversationEntryLastErrorAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMailConversationEntryLastErrorAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailConversationEntryLastErrorAnyOf(val *MailConversationEntryLastErrorAnyOf) *NullableMailConversationEntryLastErrorAnyOf {
	return &NullableMailConversationEntryLastErrorAnyOf{value: val, isSet: true}
}

func (v NullableMailConversationEntryLastErrorAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailConversationEntryLastErrorAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


