/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPostDeliverabilityMailboxesByMailboxIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostDeliverabilityMailboxesByMailboxIdRequest{}

// MailPostDeliverabilityMailboxesByMailboxIdRequest Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
type MailPostDeliverabilityMailboxesByMailboxIdRequest struct {
	RampEnabled bool `json:"rampEnabled"`
	RampIntervalHours int32 `json:"rampIntervalHours"`
	RampStep int32 `json:"rampStep"`
	StartingDailyLimit int32 `json:"startingDailyLimit"`
	TargetDailyLimit int32 `json:"targetDailyLimit"`
}

type _MailPostDeliverabilityMailboxesByMailboxIdRequest MailPostDeliverabilityMailboxesByMailboxIdRequest

// NewMailPostDeliverabilityMailboxesByMailboxIdRequest instantiates a new MailPostDeliverabilityMailboxesByMailboxIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostDeliverabilityMailboxesByMailboxIdRequest(rampEnabled bool, rampIntervalHours int32, rampStep int32, startingDailyLimit int32, targetDailyLimit int32) *MailPostDeliverabilityMailboxesByMailboxIdRequest {
	this := MailPostDeliverabilityMailboxesByMailboxIdRequest{}
	this.RampEnabled = rampEnabled
	this.RampIntervalHours = rampIntervalHours
	this.RampStep = rampStep
	this.StartingDailyLimit = startingDailyLimit
	this.TargetDailyLimit = targetDailyLimit
	return &this
}

// NewMailPostDeliverabilityMailboxesByMailboxIdRequestWithDefaults instantiates a new MailPostDeliverabilityMailboxesByMailboxIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostDeliverabilityMailboxesByMailboxIdRequestWithDefaults() *MailPostDeliverabilityMailboxesByMailboxIdRequest {
	this := MailPostDeliverabilityMailboxesByMailboxIdRequest{}
	return &this
}

// GetRampEnabled returns the RampEnabled field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RampEnabled
}

// GetRampEnabledOk returns a tuple with the RampEnabled field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RampEnabled, true
}

// SetRampEnabled sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) SetRampEnabled(v bool) {
	o.RampEnabled = v
}

// GetRampIntervalHours returns the RampIntervalHours field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampIntervalHours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RampIntervalHours
}

// GetRampIntervalHoursOk returns a tuple with the RampIntervalHours field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampIntervalHoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RampIntervalHours, true
}

// SetRampIntervalHours sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) SetRampIntervalHours(v int32) {
	o.RampIntervalHours = v
}

// GetRampStep returns the RampStep field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampStep() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RampStep
}

// GetRampStepOk returns a tuple with the RampStep field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetRampStepOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RampStep, true
}

// SetRampStep sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) SetRampStep(v int32) {
	o.RampStep = v
}

// GetStartingDailyLimit returns the StartingDailyLimit field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetStartingDailyLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartingDailyLimit
}

// GetStartingDailyLimitOk returns a tuple with the StartingDailyLimit field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetStartingDailyLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartingDailyLimit, true
}

// SetStartingDailyLimit sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) SetStartingDailyLimit(v int32) {
	o.StartingDailyLimit = v
}

// GetTargetDailyLimit returns the TargetDailyLimit field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetTargetDailyLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetDailyLimit
}

// GetTargetDailyLimitOk returns a tuple with the TargetDailyLimit field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) GetTargetDailyLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetDailyLimit, true
}

// SetTargetDailyLimit sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) SetTargetDailyLimit(v int32) {
	o.TargetDailyLimit = v
}

func (o MailPostDeliverabilityMailboxesByMailboxIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostDeliverabilityMailboxesByMailboxIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rampEnabled"] = o.RampEnabled
	toSerialize["rampIntervalHours"] = o.RampIntervalHours
	toSerialize["rampStep"] = o.RampStep
	toSerialize["startingDailyLimit"] = o.StartingDailyLimit
	toSerialize["targetDailyLimit"] = o.TargetDailyLimit
	return toSerialize, nil
}

func (o *MailPostDeliverabilityMailboxesByMailboxIdRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rampEnabled",
		"rampIntervalHours",
		"rampStep",
		"startingDailyLimit",
		"targetDailyLimit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostDeliverabilityMailboxesByMailboxIdRequest := _MailPostDeliverabilityMailboxesByMailboxIdRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostDeliverabilityMailboxesByMailboxIdRequest)

	if err != nil {
		return err
	}

	*o = MailPostDeliverabilityMailboxesByMailboxIdRequest(varMailPostDeliverabilityMailboxesByMailboxIdRequest)

	return err
}

type NullableMailPostDeliverabilityMailboxesByMailboxIdRequest struct {
	value *MailPostDeliverabilityMailboxesByMailboxIdRequest
	isSet bool
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) Get() *MailPostDeliverabilityMailboxesByMailboxIdRequest {
	return v.value
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) Set(val *MailPostDeliverabilityMailboxesByMailboxIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostDeliverabilityMailboxesByMailboxIdRequest(val *MailPostDeliverabilityMailboxesByMailboxIdRequest) *NullableMailPostDeliverabilityMailboxesByMailboxIdRequest {
	return &NullableMailPostDeliverabilityMailboxesByMailboxIdRequest{value: val, isSet: true}
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


