/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the MailPostReplyAutomationsRequestActions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostReplyAutomationsRequestActions{}

// MailPostReplyAutomationsRequestActions struct for MailPostReplyAutomationsRequestActions
type MailPostReplyAutomationsRequestActions struct {
	AssignToActorId *string `json:"assignToActorId,omitempty"`
	Stage *string `json:"stage,omitempty"`
	StopCadences *bool `json:"stopCadences,omitempty"`
	Task *MailPostReplyAutomationsRequestActionsTask `json:"task,omitempty"`
}

// NewMailPostReplyAutomationsRequestActions instantiates a new MailPostReplyAutomationsRequestActions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostReplyAutomationsRequestActions() *MailPostReplyAutomationsRequestActions {
	this := MailPostReplyAutomationsRequestActions{}
	var stopCadences bool = true
	this.StopCadences = &stopCadences
	return &this
}

// NewMailPostReplyAutomationsRequestActionsWithDefaults instantiates a new MailPostReplyAutomationsRequestActions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostReplyAutomationsRequestActionsWithDefaults() *MailPostReplyAutomationsRequestActions {
	this := MailPostReplyAutomationsRequestActions{}
	var stopCadences bool = true
	this.StopCadences = &stopCadences
	return &this
}

// GetAssignToActorId returns the AssignToActorId field value if set, zero value otherwise.
func (o *MailPostReplyAutomationsRequestActions) GetAssignToActorId() string {
	if o == nil || IsNil(o.AssignToActorId) {
		var ret string
		return ret
	}
	return *o.AssignToActorId
}

// GetAssignToActorIdOk returns a tuple with the AssignToActorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostReplyAutomationsRequestActions) GetAssignToActorIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssignToActorId) {
		return nil, false
	}
	return o.AssignToActorId, true
}

// HasAssignToActorId returns a boolean if a field has been set.
func (o *MailPostReplyAutomationsRequestActions) HasAssignToActorId() bool {
	if o != nil && !IsNil(o.AssignToActorId) {
		return true
	}

	return false
}

// SetAssignToActorId gets a reference to the given string and assigns it to the AssignToActorId field.
func (o *MailPostReplyAutomationsRequestActions) SetAssignToActorId(v string) {
	o.AssignToActorId = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *MailPostReplyAutomationsRequestActions) GetStage() string {
	if o == nil || IsNil(o.Stage) {
		var ret string
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostReplyAutomationsRequestActions) GetStageOk() (*string, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *MailPostReplyAutomationsRequestActions) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given string and assigns it to the Stage field.
func (o *MailPostReplyAutomationsRequestActions) SetStage(v string) {
	o.Stage = &v
}

// GetStopCadences returns the StopCadences field value if set, zero value otherwise.
func (o *MailPostReplyAutomationsRequestActions) GetStopCadences() bool {
	if o == nil || IsNil(o.StopCadences) {
		var ret bool
		return ret
	}
	return *o.StopCadences
}

// GetStopCadencesOk returns a tuple with the StopCadences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostReplyAutomationsRequestActions) GetStopCadencesOk() (*bool, bool) {
	if o == nil || IsNil(o.StopCadences) {
		return nil, false
	}
	return o.StopCadences, true
}

// HasStopCadences returns a boolean if a field has been set.
func (o *MailPostReplyAutomationsRequestActions) HasStopCadences() bool {
	if o != nil && !IsNil(o.StopCadences) {
		return true
	}

	return false
}

// SetStopCadences gets a reference to the given bool and assigns it to the StopCadences field.
func (o *MailPostReplyAutomationsRequestActions) SetStopCadences(v bool) {
	o.StopCadences = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *MailPostReplyAutomationsRequestActions) GetTask() MailPostReplyAutomationsRequestActionsTask {
	if o == nil || IsNil(o.Task) {
		var ret MailPostReplyAutomationsRequestActionsTask
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostReplyAutomationsRequestActions) GetTaskOk() (*MailPostReplyAutomationsRequestActionsTask, bool) {
	if o == nil || IsNil(o.Task) {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *MailPostReplyAutomationsRequestActions) HasTask() bool {
	if o != nil && !IsNil(o.Task) {
		return true
	}

	return false
}

// SetTask gets a reference to the given MailPostReplyAutomationsRequestActionsTask and assigns it to the Task field.
func (o *MailPostReplyAutomationsRequestActions) SetTask(v MailPostReplyAutomationsRequestActionsTask) {
	o.Task = &v
}

func (o MailPostReplyAutomationsRequestActions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostReplyAutomationsRequestActions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssignToActorId) {
		toSerialize["assignToActorId"] = o.AssignToActorId
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	if !IsNil(o.StopCadences) {
		toSerialize["stopCadences"] = o.StopCadences
	}
	if !IsNil(o.Task) {
		toSerialize["task"] = o.Task
	}
	return toSerialize, nil
}

type NullableMailPostReplyAutomationsRequestActions struct {
	value *MailPostReplyAutomationsRequestActions
	isSet bool
}

func (v NullableMailPostReplyAutomationsRequestActions) Get() *MailPostReplyAutomationsRequestActions {
	return v.value
}

func (v *NullableMailPostReplyAutomationsRequestActions) Set(val *MailPostReplyAutomationsRequestActions) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostReplyAutomationsRequestActions) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostReplyAutomationsRequestActions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostReplyAutomationsRequestActions(val *MailPostReplyAutomationsRequestActions) *NullableMailPostReplyAutomationsRequestActions {
	return &NullableMailPostReplyAutomationsRequestActions{value: val, isSet: true}
}

func (v NullableMailPostReplyAutomationsRequestActions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostReplyAutomationsRequestActions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


