/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductSequenceRecipientsAddExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSequenceRecipientsAddExecution{}

// ProductSequenceRecipientsAddExecution struct for ProductSequenceRecipientsAddExecution
type ProductSequenceRecipientsAddExecution struct {
	ExecutionId string `json:"executionId"`
	Output ProductSequenceRecipientsAddOutput `json:"output"`
	Replay bool `json:"replay"`
	Tool string `json:"tool"`
	AdditionalProperties map[string]interface{}
}

type _ProductSequenceRecipientsAddExecution ProductSequenceRecipientsAddExecution

// NewProductSequenceRecipientsAddExecution instantiates a new ProductSequenceRecipientsAddExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSequenceRecipientsAddExecution(executionId string, output ProductSequenceRecipientsAddOutput, replay bool, tool string) *ProductSequenceRecipientsAddExecution {
	this := ProductSequenceRecipientsAddExecution{}
	this.ExecutionId = executionId
	this.Output = output
	this.Replay = replay
	this.Tool = tool
	return &this
}

// NewProductSequenceRecipientsAddExecutionWithDefaults instantiates a new ProductSequenceRecipientsAddExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSequenceRecipientsAddExecutionWithDefaults() *ProductSequenceRecipientsAddExecution {
	this := ProductSequenceRecipientsAddExecution{}
	return &this
}

// GetExecutionId returns the ExecutionId field value
func (o *ProductSequenceRecipientsAddExecution) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientsAddExecution) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *ProductSequenceRecipientsAddExecution) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetOutput returns the Output field value
func (o *ProductSequenceRecipientsAddExecution) GetOutput() ProductSequenceRecipientsAddOutput {
	if o == nil {
		var ret ProductSequenceRecipientsAddOutput
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientsAddExecution) GetOutputOk() (*ProductSequenceRecipientsAddOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *ProductSequenceRecipientsAddExecution) SetOutput(v ProductSequenceRecipientsAddOutput) {
	o.Output = v
}

// GetReplay returns the Replay field value
func (o *ProductSequenceRecipientsAddExecution) GetReplay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Replay
}

// GetReplayOk returns a tuple with the Replay field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientsAddExecution) GetReplayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replay, true
}

// SetReplay sets field value
func (o *ProductSequenceRecipientsAddExecution) SetReplay(v bool) {
	o.Replay = v
}

// GetTool returns the Tool field value
func (o *ProductSequenceRecipientsAddExecution) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientsAddExecution) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *ProductSequenceRecipientsAddExecution) SetTool(v string) {
	o.Tool = v
}

func (o ProductSequenceRecipientsAddExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSequenceRecipientsAddExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["executionId"] = o.ExecutionId
	toSerialize["output"] = o.Output
	toSerialize["replay"] = o.Replay
	toSerialize["tool"] = o.Tool

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductSequenceRecipientsAddExecution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"executionId",
		"output",
		"replay",
		"tool",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductSequenceRecipientsAddExecution := _ProductSequenceRecipientsAddExecution{}

	err = json.Unmarshal(data, &varProductSequenceRecipientsAddExecution)

	if err != nil {
		return err
	}

	*o = ProductSequenceRecipientsAddExecution(varProductSequenceRecipientsAddExecution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "executionId")
		delete(additionalProperties, "output")
		delete(additionalProperties, "replay")
		delete(additionalProperties, "tool")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductSequenceRecipientsAddExecution struct {
	value *ProductSequenceRecipientsAddExecution
	isSet bool
}

func (v NullableProductSequenceRecipientsAddExecution) Get() *ProductSequenceRecipientsAddExecution {
	return v.value
}

func (v *NullableProductSequenceRecipientsAddExecution) Set(val *ProductSequenceRecipientsAddExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSequenceRecipientsAddExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSequenceRecipientsAddExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSequenceRecipientsAddExecution(val *ProductSequenceRecipientsAddExecution) *NullableProductSequenceRecipientsAddExecution {
	return &NullableProductSequenceRecipientsAddExecution{value: val, isSet: true}
}

func (v NullableProductSequenceRecipientsAddExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSequenceRecipientsAddExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


