/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)


// ProductToolRequestInput Use the input model matching the tool path parameter. Equivalent input shapes appear once in this anyOf union; the tool catalog retains every named model.
type ProductToolRequestInput struct {
	ProductCompaniesListInput *ProductCompaniesListInput
	ProductCompanyDeleteInput *ProductCompanyDeleteInput
	ProductCompanyListAddInput *ProductCompanyListAddInput
	ProductCompanyTrackInput *ProductCompanyTrackInput
	ProductCompanyUpdateInput *ProductCompanyUpdateInput
	ProductConnectedAppPushInput *ProductConnectedAppPushInput
	ProductCustomAttributeCreateInput *ProductCustomAttributeCreateInput
	ProductDiscoverCompaniesInput *ProductDiscoverCompaniesInput
	ProductDiscoverPeopleInput *ProductDiscoverPeopleInput
	ProductDomainFinderInput *ProductDomainFinderInput
	ProductEmailCountInput *ProductEmailCountInput
	ProductLeadBulkDeleteInput *ProductLeadBulkDeleteInput
	ProductLeadCreateInput *ProductLeadCreateInput
	ProductLeadDeleteInput *ProductLeadDeleteInput
	ProductLeadGetInput *ProductLeadGetInput
	ProductLeadListAddLeadInput *ProductLeadListAddLeadInput
	ProductLeadListDeleteInput *ProductLeadListDeleteInput
	ProductLeadListUpdateInput *ProductLeadListUpdateInput
	ProductLeadTagAssignInput *ProductLeadTagAssignInput
	ProductLeadTagCreateInput *ProductLeadTagCreateInput
	ProductLeadUpdateInput *ProductLeadUpdateInput
	ProductLeadsListInput *ProductLeadsListInput
	ProductPersonEnrichInput *ProductPersonEnrichInput
	ProductSequenceRecipientAddInput *ProductSequenceRecipientAddInput
	ProductSequenceRecipientCancelInput *ProductSequenceRecipientCancelInput
	ProductSequenceRecipientsAddInput *ProductSequenceRecipientsAddInput
	ProductSequenceRecipientsListInput *ProductSequenceRecipientsListInput
	ProductSequenceStartInput *ProductSequenceStartInput
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ProductToolRequestInput) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ProductCompaniesListInput
	err = json.Unmarshal(data, &dst.ProductCompaniesListInput);
	if err == nil {
		jsonProductCompaniesListInput, _ := json.Marshal(dst.ProductCompaniesListInput)
		if string(jsonProductCompaniesListInput) == "{}" { // empty struct
			dst.ProductCompaniesListInput = nil
		} else {
			return nil // data stored in dst.ProductCompaniesListInput, return on the first match
		}
	} else {
		dst.ProductCompaniesListInput = nil
	}

	// try to unmarshal JSON data into ProductCompanyDeleteInput
	err = json.Unmarshal(data, &dst.ProductCompanyDeleteInput);
	if err == nil {
		jsonProductCompanyDeleteInput, _ := json.Marshal(dst.ProductCompanyDeleteInput)
		if string(jsonProductCompanyDeleteInput) == "{}" { // empty struct
			dst.ProductCompanyDeleteInput = nil
		} else {
			return nil // data stored in dst.ProductCompanyDeleteInput, return on the first match
		}
	} else {
		dst.ProductCompanyDeleteInput = nil
	}

	// try to unmarshal JSON data into ProductCompanyListAddInput
	err = json.Unmarshal(data, &dst.ProductCompanyListAddInput);
	if err == nil {
		jsonProductCompanyListAddInput, _ := json.Marshal(dst.ProductCompanyListAddInput)
		if string(jsonProductCompanyListAddInput) == "{}" { // empty struct
			dst.ProductCompanyListAddInput = nil
		} else {
			return nil // data stored in dst.ProductCompanyListAddInput, return on the first match
		}
	} else {
		dst.ProductCompanyListAddInput = nil
	}

	// try to unmarshal JSON data into ProductCompanyTrackInput
	err = json.Unmarshal(data, &dst.ProductCompanyTrackInput);
	if err == nil {
		jsonProductCompanyTrackInput, _ := json.Marshal(dst.ProductCompanyTrackInput)
		if string(jsonProductCompanyTrackInput) == "{}" { // empty struct
			dst.ProductCompanyTrackInput = nil
		} else {
			return nil // data stored in dst.ProductCompanyTrackInput, return on the first match
		}
	} else {
		dst.ProductCompanyTrackInput = nil
	}

	// try to unmarshal JSON data into ProductCompanyUpdateInput
	err = json.Unmarshal(data, &dst.ProductCompanyUpdateInput);
	if err == nil {
		jsonProductCompanyUpdateInput, _ := json.Marshal(dst.ProductCompanyUpdateInput)
		if string(jsonProductCompanyUpdateInput) == "{}" { // empty struct
			dst.ProductCompanyUpdateInput = nil
		} else {
			return nil // data stored in dst.ProductCompanyUpdateInput, return on the first match
		}
	} else {
		dst.ProductCompanyUpdateInput = nil
	}

	// try to unmarshal JSON data into ProductConnectedAppPushInput
	err = json.Unmarshal(data, &dst.ProductConnectedAppPushInput);
	if err == nil {
		jsonProductConnectedAppPushInput, _ := json.Marshal(dst.ProductConnectedAppPushInput)
		if string(jsonProductConnectedAppPushInput) == "{}" { // empty struct
			dst.ProductConnectedAppPushInput = nil
		} else {
			return nil // data stored in dst.ProductConnectedAppPushInput, return on the first match
		}
	} else {
		dst.ProductConnectedAppPushInput = nil
	}

	// try to unmarshal JSON data into ProductCustomAttributeCreateInput
	err = json.Unmarshal(data, &dst.ProductCustomAttributeCreateInput);
	if err == nil {
		jsonProductCustomAttributeCreateInput, _ := json.Marshal(dst.ProductCustomAttributeCreateInput)
		if string(jsonProductCustomAttributeCreateInput) == "{}" { // empty struct
			dst.ProductCustomAttributeCreateInput = nil
		} else {
			return nil // data stored in dst.ProductCustomAttributeCreateInput, return on the first match
		}
	} else {
		dst.ProductCustomAttributeCreateInput = nil
	}

	// try to unmarshal JSON data into ProductDiscoverCompaniesInput
	err = json.Unmarshal(data, &dst.ProductDiscoverCompaniesInput);
	if err == nil {
		jsonProductDiscoverCompaniesInput, _ := json.Marshal(dst.ProductDiscoverCompaniesInput)
		if string(jsonProductDiscoverCompaniesInput) == "{}" { // empty struct
			dst.ProductDiscoverCompaniesInput = nil
		} else {
			return nil // data stored in dst.ProductDiscoverCompaniesInput, return on the first match
		}
	} else {
		dst.ProductDiscoverCompaniesInput = nil
	}

	// try to unmarshal JSON data into ProductDiscoverPeopleInput
	err = json.Unmarshal(data, &dst.ProductDiscoverPeopleInput);
	if err == nil {
		jsonProductDiscoverPeopleInput, _ := json.Marshal(dst.ProductDiscoverPeopleInput)
		if string(jsonProductDiscoverPeopleInput) == "{}" { // empty struct
			dst.ProductDiscoverPeopleInput = nil
		} else {
			return nil // data stored in dst.ProductDiscoverPeopleInput, return on the first match
		}
	} else {
		dst.ProductDiscoverPeopleInput = nil
	}

	// try to unmarshal JSON data into ProductDomainFinderInput
	err = json.Unmarshal(data, &dst.ProductDomainFinderInput);
	if err == nil {
		jsonProductDomainFinderInput, _ := json.Marshal(dst.ProductDomainFinderInput)
		if string(jsonProductDomainFinderInput) == "{}" { // empty struct
			dst.ProductDomainFinderInput = nil
		} else {
			return nil // data stored in dst.ProductDomainFinderInput, return on the first match
		}
	} else {
		dst.ProductDomainFinderInput = nil
	}

	// try to unmarshal JSON data into ProductEmailCountInput
	err = json.Unmarshal(data, &dst.ProductEmailCountInput);
	if err == nil {
		jsonProductEmailCountInput, _ := json.Marshal(dst.ProductEmailCountInput)
		if string(jsonProductEmailCountInput) == "{}" { // empty struct
			dst.ProductEmailCountInput = nil
		} else {
			return nil // data stored in dst.ProductEmailCountInput, return on the first match
		}
	} else {
		dst.ProductEmailCountInput = nil
	}

	// try to unmarshal JSON data into ProductLeadBulkDeleteInput
	err = json.Unmarshal(data, &dst.ProductLeadBulkDeleteInput);
	if err == nil {
		jsonProductLeadBulkDeleteInput, _ := json.Marshal(dst.ProductLeadBulkDeleteInput)
		if string(jsonProductLeadBulkDeleteInput) == "{}" { // empty struct
			dst.ProductLeadBulkDeleteInput = nil
		} else {
			return nil // data stored in dst.ProductLeadBulkDeleteInput, return on the first match
		}
	} else {
		dst.ProductLeadBulkDeleteInput = nil
	}

	// try to unmarshal JSON data into ProductLeadCreateInput
	err = json.Unmarshal(data, &dst.ProductLeadCreateInput);
	if err == nil {
		jsonProductLeadCreateInput, _ := json.Marshal(dst.ProductLeadCreateInput)
		if string(jsonProductLeadCreateInput) == "{}" { // empty struct
			dst.ProductLeadCreateInput = nil
		} else {
			return nil // data stored in dst.ProductLeadCreateInput, return on the first match
		}
	} else {
		dst.ProductLeadCreateInput = nil
	}

	// try to unmarshal JSON data into ProductLeadDeleteInput
	err = json.Unmarshal(data, &dst.ProductLeadDeleteInput);
	if err == nil {
		jsonProductLeadDeleteInput, _ := json.Marshal(dst.ProductLeadDeleteInput)
		if string(jsonProductLeadDeleteInput) == "{}" { // empty struct
			dst.ProductLeadDeleteInput = nil
		} else {
			return nil // data stored in dst.ProductLeadDeleteInput, return on the first match
		}
	} else {
		dst.ProductLeadDeleteInput = nil
	}

	// try to unmarshal JSON data into ProductLeadGetInput
	err = json.Unmarshal(data, &dst.ProductLeadGetInput);
	if err == nil {
		jsonProductLeadGetInput, _ := json.Marshal(dst.ProductLeadGetInput)
		if string(jsonProductLeadGetInput) == "{}" { // empty struct
			dst.ProductLeadGetInput = nil
		} else {
			return nil // data stored in dst.ProductLeadGetInput, return on the first match
		}
	} else {
		dst.ProductLeadGetInput = nil
	}

	// try to unmarshal JSON data into ProductLeadListAddLeadInput
	err = json.Unmarshal(data, &dst.ProductLeadListAddLeadInput);
	if err == nil {
		jsonProductLeadListAddLeadInput, _ := json.Marshal(dst.ProductLeadListAddLeadInput)
		if string(jsonProductLeadListAddLeadInput) == "{}" { // empty struct
			dst.ProductLeadListAddLeadInput = nil
		} else {
			return nil // data stored in dst.ProductLeadListAddLeadInput, return on the first match
		}
	} else {
		dst.ProductLeadListAddLeadInput = nil
	}

	// try to unmarshal JSON data into ProductLeadListDeleteInput
	err = json.Unmarshal(data, &dst.ProductLeadListDeleteInput);
	if err == nil {
		jsonProductLeadListDeleteInput, _ := json.Marshal(dst.ProductLeadListDeleteInput)
		if string(jsonProductLeadListDeleteInput) == "{}" { // empty struct
			dst.ProductLeadListDeleteInput = nil
		} else {
			return nil // data stored in dst.ProductLeadListDeleteInput, return on the first match
		}
	} else {
		dst.ProductLeadListDeleteInput = nil
	}

	// try to unmarshal JSON data into ProductLeadListUpdateInput
	err = json.Unmarshal(data, &dst.ProductLeadListUpdateInput);
	if err == nil {
		jsonProductLeadListUpdateInput, _ := json.Marshal(dst.ProductLeadListUpdateInput)
		if string(jsonProductLeadListUpdateInput) == "{}" { // empty struct
			dst.ProductLeadListUpdateInput = nil
		} else {
			return nil // data stored in dst.ProductLeadListUpdateInput, return on the first match
		}
	} else {
		dst.ProductLeadListUpdateInput = nil
	}

	// try to unmarshal JSON data into ProductLeadTagAssignInput
	err = json.Unmarshal(data, &dst.ProductLeadTagAssignInput);
	if err == nil {
		jsonProductLeadTagAssignInput, _ := json.Marshal(dst.ProductLeadTagAssignInput)
		if string(jsonProductLeadTagAssignInput) == "{}" { // empty struct
			dst.ProductLeadTagAssignInput = nil
		} else {
			return nil // data stored in dst.ProductLeadTagAssignInput, return on the first match
		}
	} else {
		dst.ProductLeadTagAssignInput = nil
	}

	// try to unmarshal JSON data into ProductLeadTagCreateInput
	err = json.Unmarshal(data, &dst.ProductLeadTagCreateInput);
	if err == nil {
		jsonProductLeadTagCreateInput, _ := json.Marshal(dst.ProductLeadTagCreateInput)
		if string(jsonProductLeadTagCreateInput) == "{}" { // empty struct
			dst.ProductLeadTagCreateInput = nil
		} else {
			return nil // data stored in dst.ProductLeadTagCreateInput, return on the first match
		}
	} else {
		dst.ProductLeadTagCreateInput = nil
	}

	// try to unmarshal JSON data into ProductLeadUpdateInput
	err = json.Unmarshal(data, &dst.ProductLeadUpdateInput);
	if err == nil {
		jsonProductLeadUpdateInput, _ := json.Marshal(dst.ProductLeadUpdateInput)
		if string(jsonProductLeadUpdateInput) == "{}" { // empty struct
			dst.ProductLeadUpdateInput = nil
		} else {
			return nil // data stored in dst.ProductLeadUpdateInput, return on the first match
		}
	} else {
		dst.ProductLeadUpdateInput = nil
	}

	// try to unmarshal JSON data into ProductLeadsListInput
	err = json.Unmarshal(data, &dst.ProductLeadsListInput);
	if err == nil {
		jsonProductLeadsListInput, _ := json.Marshal(dst.ProductLeadsListInput)
		if string(jsonProductLeadsListInput) == "{}" { // empty struct
			dst.ProductLeadsListInput = nil
		} else {
			return nil // data stored in dst.ProductLeadsListInput, return on the first match
		}
	} else {
		dst.ProductLeadsListInput = nil
	}

	// try to unmarshal JSON data into ProductPersonEnrichInput
	err = json.Unmarshal(data, &dst.ProductPersonEnrichInput);
	if err == nil {
		jsonProductPersonEnrichInput, _ := json.Marshal(dst.ProductPersonEnrichInput)
		if string(jsonProductPersonEnrichInput) == "{}" { // empty struct
			dst.ProductPersonEnrichInput = nil
		} else {
			return nil // data stored in dst.ProductPersonEnrichInput, return on the first match
		}
	} else {
		dst.ProductPersonEnrichInput = nil
	}

	// try to unmarshal JSON data into ProductSequenceRecipientAddInput
	err = json.Unmarshal(data, &dst.ProductSequenceRecipientAddInput);
	if err == nil {
		jsonProductSequenceRecipientAddInput, _ := json.Marshal(dst.ProductSequenceRecipientAddInput)
		if string(jsonProductSequenceRecipientAddInput) == "{}" { // empty struct
			dst.ProductSequenceRecipientAddInput = nil
		} else {
			return nil // data stored in dst.ProductSequenceRecipientAddInput, return on the first match
		}
	} else {
		dst.ProductSequenceRecipientAddInput = nil
	}

	// try to unmarshal JSON data into ProductSequenceRecipientCancelInput
	err = json.Unmarshal(data, &dst.ProductSequenceRecipientCancelInput);
	if err == nil {
		jsonProductSequenceRecipientCancelInput, _ := json.Marshal(dst.ProductSequenceRecipientCancelInput)
		if string(jsonProductSequenceRecipientCancelInput) == "{}" { // empty struct
			dst.ProductSequenceRecipientCancelInput = nil
		} else {
			return nil // data stored in dst.ProductSequenceRecipientCancelInput, return on the first match
		}
	} else {
		dst.ProductSequenceRecipientCancelInput = nil
	}

	// try to unmarshal JSON data into ProductSequenceRecipientsAddInput
	err = json.Unmarshal(data, &dst.ProductSequenceRecipientsAddInput);
	if err == nil {
		jsonProductSequenceRecipientsAddInput, _ := json.Marshal(dst.ProductSequenceRecipientsAddInput)
		if string(jsonProductSequenceRecipientsAddInput) == "{}" { // empty struct
			dst.ProductSequenceRecipientsAddInput = nil
		} else {
			return nil // data stored in dst.ProductSequenceRecipientsAddInput, return on the first match
		}
	} else {
		dst.ProductSequenceRecipientsAddInput = nil
	}

	// try to unmarshal JSON data into ProductSequenceRecipientsListInput
	err = json.Unmarshal(data, &dst.ProductSequenceRecipientsListInput);
	if err == nil {
		jsonProductSequenceRecipientsListInput, _ := json.Marshal(dst.ProductSequenceRecipientsListInput)
		if string(jsonProductSequenceRecipientsListInput) == "{}" { // empty struct
			dst.ProductSequenceRecipientsListInput = nil
		} else {
			return nil // data stored in dst.ProductSequenceRecipientsListInput, return on the first match
		}
	} else {
		dst.ProductSequenceRecipientsListInput = nil
	}

	// try to unmarshal JSON data into ProductSequenceStartInput
	err = json.Unmarshal(data, &dst.ProductSequenceStartInput);
	if err == nil {
		jsonProductSequenceStartInput, _ := json.Marshal(dst.ProductSequenceStartInput)
		if string(jsonProductSequenceStartInput) == "{}" { // empty struct
			dst.ProductSequenceStartInput = nil
		} else {
			return nil // data stored in dst.ProductSequenceStartInput, return on the first match
		}
	} else {
		dst.ProductSequenceStartInput = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ProductToolRequestInput)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProductToolRequestInput) MarshalJSON() ([]byte, error) {
	if src.ProductCompaniesListInput != nil {
		return json.Marshal(&src.ProductCompaniesListInput)
	}

	if src.ProductCompanyDeleteInput != nil {
		return json.Marshal(&src.ProductCompanyDeleteInput)
	}

	if src.ProductCompanyListAddInput != nil {
		return json.Marshal(&src.ProductCompanyListAddInput)
	}

	if src.ProductCompanyTrackInput != nil {
		return json.Marshal(&src.ProductCompanyTrackInput)
	}

	if src.ProductCompanyUpdateInput != nil {
		return json.Marshal(&src.ProductCompanyUpdateInput)
	}

	if src.ProductConnectedAppPushInput != nil {
		return json.Marshal(&src.ProductConnectedAppPushInput)
	}

	if src.ProductCustomAttributeCreateInput != nil {
		return json.Marshal(&src.ProductCustomAttributeCreateInput)
	}

	if src.ProductDiscoverCompaniesInput != nil {
		return json.Marshal(&src.ProductDiscoverCompaniesInput)
	}

	if src.ProductDiscoverPeopleInput != nil {
		return json.Marshal(&src.ProductDiscoverPeopleInput)
	}

	if src.ProductDomainFinderInput != nil {
		return json.Marshal(&src.ProductDomainFinderInput)
	}

	if src.ProductEmailCountInput != nil {
		return json.Marshal(&src.ProductEmailCountInput)
	}

	if src.ProductLeadBulkDeleteInput != nil {
		return json.Marshal(&src.ProductLeadBulkDeleteInput)
	}

	if src.ProductLeadCreateInput != nil {
		return json.Marshal(&src.ProductLeadCreateInput)
	}

	if src.ProductLeadDeleteInput != nil {
		return json.Marshal(&src.ProductLeadDeleteInput)
	}

	if src.ProductLeadGetInput != nil {
		return json.Marshal(&src.ProductLeadGetInput)
	}

	if src.ProductLeadListAddLeadInput != nil {
		return json.Marshal(&src.ProductLeadListAddLeadInput)
	}

	if src.ProductLeadListDeleteInput != nil {
		return json.Marshal(&src.ProductLeadListDeleteInput)
	}

	if src.ProductLeadListUpdateInput != nil {
		return json.Marshal(&src.ProductLeadListUpdateInput)
	}

	if src.ProductLeadTagAssignInput != nil {
		return json.Marshal(&src.ProductLeadTagAssignInput)
	}

	if src.ProductLeadTagCreateInput != nil {
		return json.Marshal(&src.ProductLeadTagCreateInput)
	}

	if src.ProductLeadUpdateInput != nil {
		return json.Marshal(&src.ProductLeadUpdateInput)
	}

	if src.ProductLeadsListInput != nil {
		return json.Marshal(&src.ProductLeadsListInput)
	}

	if src.ProductPersonEnrichInput != nil {
		return json.Marshal(&src.ProductPersonEnrichInput)
	}

	if src.ProductSequenceRecipientAddInput != nil {
		return json.Marshal(&src.ProductSequenceRecipientAddInput)
	}

	if src.ProductSequenceRecipientCancelInput != nil {
		return json.Marshal(&src.ProductSequenceRecipientCancelInput)
	}

	if src.ProductSequenceRecipientsAddInput != nil {
		return json.Marshal(&src.ProductSequenceRecipientsAddInput)
	}

	if src.ProductSequenceRecipientsListInput != nil {
		return json.Marshal(&src.ProductSequenceRecipientsListInput)
	}

	if src.ProductSequenceStartInput != nil {
		return json.Marshal(&src.ProductSequenceStartInput)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableProductToolRequestInput struct {
	value *ProductToolRequestInput
	isSet bool
}

func (v NullableProductToolRequestInput) Get() *ProductToolRequestInput {
	return v.value
}

func (v *NullableProductToolRequestInput) Set(val *ProductToolRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableProductToolRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableProductToolRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductToolRequestInput(val *ProductToolRequestInput) *NullableProductToolRequestInput {
	return &NullableProductToolRequestInput{value: val, isSet: true}
}

func (v NullableProductToolRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductToolRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


