/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostInboxByMessageIdResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostInboxByMessageIdResponse200{}

// MailPostInboxByMessageIdResponse200 struct for MailPostInboxByMessageIdResponse200
type MailPostInboxByMessageIdResponse200 struct {
	Message MailPostInboxByMessageIdResponse200Message `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _MailPostInboxByMessageIdResponse200 MailPostInboxByMessageIdResponse200

// NewMailPostInboxByMessageIdResponse200 instantiates a new MailPostInboxByMessageIdResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostInboxByMessageIdResponse200(message MailPostInboxByMessageIdResponse200Message) *MailPostInboxByMessageIdResponse200 {
	this := MailPostInboxByMessageIdResponse200{}
	this.Message = message
	return &this
}

// NewMailPostInboxByMessageIdResponse200WithDefaults instantiates a new MailPostInboxByMessageIdResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostInboxByMessageIdResponse200WithDefaults() *MailPostInboxByMessageIdResponse200 {
	this := MailPostInboxByMessageIdResponse200{}
	return &this
}

// GetMessage returns the Message field value
func (o *MailPostInboxByMessageIdResponse200) GetMessage() MailPostInboxByMessageIdResponse200Message {
	if o == nil {
		var ret MailPostInboxByMessageIdResponse200Message
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MailPostInboxByMessageIdResponse200) GetMessageOk() (*MailPostInboxByMessageIdResponse200Message, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MailPostInboxByMessageIdResponse200) SetMessage(v MailPostInboxByMessageIdResponse200Message) {
	o.Message = v
}

func (o MailPostInboxByMessageIdResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostInboxByMessageIdResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostInboxByMessageIdResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostInboxByMessageIdResponse200 := _MailPostInboxByMessageIdResponse200{}

	err = json.Unmarshal(data, &varMailPostInboxByMessageIdResponse200)

	if err != nil {
		return err
	}

	*o = MailPostInboxByMessageIdResponse200(varMailPostInboxByMessageIdResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostInboxByMessageIdResponse200 struct {
	value *MailPostInboxByMessageIdResponse200
	isSet bool
}

func (v NullableMailPostInboxByMessageIdResponse200) Get() *MailPostInboxByMessageIdResponse200 {
	return v.value
}

func (v *NullableMailPostInboxByMessageIdResponse200) Set(val *MailPostInboxByMessageIdResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostInboxByMessageIdResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostInboxByMessageIdResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostInboxByMessageIdResponse200(val *MailPostInboxByMessageIdResponse200) *NullableMailPostInboxByMessageIdResponse200 {
	return &NullableMailPostInboxByMessageIdResponse200{value: val, isSet: true}
}

func (v NullableMailPostInboxByMessageIdResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostInboxByMessageIdResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


