/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailMessageAnalyticsOverviewDailyInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailMessageAnalyticsOverviewDailyInner{}

// MailMessageAnalyticsOverviewDailyInner struct for MailMessageAnalyticsOverviewDailyInner
type MailMessageAnalyticsOverviewDailyInner struct {
	Accepted float32 `json:"accepted"`
	Bounced float32 `json:"bounced"`
	Complained float32 `json:"complained"`
	Date string `json:"date"`
	Delivered float32 `json:"delivered"`
	Replied float32 `json:"replied"`
	Total float32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _MailMessageAnalyticsOverviewDailyInner MailMessageAnalyticsOverviewDailyInner

// NewMailMessageAnalyticsOverviewDailyInner instantiates a new MailMessageAnalyticsOverviewDailyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailMessageAnalyticsOverviewDailyInner(accepted float32, bounced float32, complained float32, date string, delivered float32, replied float32, total float32) *MailMessageAnalyticsOverviewDailyInner {
	this := MailMessageAnalyticsOverviewDailyInner{}
	this.Accepted = accepted
	this.Bounced = bounced
	this.Complained = complained
	this.Date = date
	this.Delivered = delivered
	this.Replied = replied
	this.Total = total
	return &this
}

// NewMailMessageAnalyticsOverviewDailyInnerWithDefaults instantiates a new MailMessageAnalyticsOverviewDailyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailMessageAnalyticsOverviewDailyInnerWithDefaults() *MailMessageAnalyticsOverviewDailyInner {
	this := MailMessageAnalyticsOverviewDailyInner{}
	return &this
}

// GetAccepted returns the Accepted field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetAccepted() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetAcceptedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accepted, true
}

// SetAccepted sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetAccepted(v float32) {
	o.Accepted = v
}

// GetBounced returns the Bounced field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetBounced() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Bounced
}

// GetBouncedOk returns a tuple with the Bounced field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetBouncedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bounced, true
}

// SetBounced sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetBounced(v float32) {
	o.Bounced = v
}

// GetComplained returns the Complained field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetComplained() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Complained
}

// GetComplainedOk returns a tuple with the Complained field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetComplainedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Complained, true
}

// SetComplained sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetComplained(v float32) {
	o.Complained = v
}

// GetDate returns the Date field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetDate(v string) {
	o.Date = v
}

// GetDelivered returns the Delivered field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetDelivered() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetDeliveredOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delivered, true
}

// SetDelivered sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetDelivered(v float32) {
	o.Delivered = v
}

// GetReplied returns the Replied field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetReplied() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Replied
}

// GetRepliedOk returns a tuple with the Replied field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetRepliedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replied, true
}

// SetReplied sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetReplied(v float32) {
	o.Replied = v
}

// GetTotal returns the Total field value
func (o *MailMessageAnalyticsOverviewDailyInner) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverviewDailyInner) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MailMessageAnalyticsOverviewDailyInner) SetTotal(v float32) {
	o.Total = v
}

func (o MailMessageAnalyticsOverviewDailyInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailMessageAnalyticsOverviewDailyInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accepted"] = o.Accepted
	toSerialize["bounced"] = o.Bounced
	toSerialize["complained"] = o.Complained
	toSerialize["date"] = o.Date
	toSerialize["delivered"] = o.Delivered
	toSerialize["replied"] = o.Replied
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailMessageAnalyticsOverviewDailyInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accepted",
		"bounced",
		"complained",
		"date",
		"delivered",
		"replied",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailMessageAnalyticsOverviewDailyInner := _MailMessageAnalyticsOverviewDailyInner{}

	err = json.Unmarshal(data, &varMailMessageAnalyticsOverviewDailyInner)

	if err != nil {
		return err
	}

	*o = MailMessageAnalyticsOverviewDailyInner(varMailMessageAnalyticsOverviewDailyInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accepted")
		delete(additionalProperties, "bounced")
		delete(additionalProperties, "complained")
		delete(additionalProperties, "date")
		delete(additionalProperties, "delivered")
		delete(additionalProperties, "replied")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailMessageAnalyticsOverviewDailyInner struct {
	value *MailMessageAnalyticsOverviewDailyInner
	isSet bool
}

func (v NullableMailMessageAnalyticsOverviewDailyInner) Get() *MailMessageAnalyticsOverviewDailyInner {
	return v.value
}

func (v *NullableMailMessageAnalyticsOverviewDailyInner) Set(val *MailMessageAnalyticsOverviewDailyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMailMessageAnalyticsOverviewDailyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMailMessageAnalyticsOverviewDailyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailMessageAnalyticsOverviewDailyInner(val *MailMessageAnalyticsOverviewDailyInner) *NullableMailMessageAnalyticsOverviewDailyInner {
	return &NullableMailMessageAnalyticsOverviewDailyInner{value: val, isSet: true}
}

func (v NullableMailMessageAnalyticsOverviewDailyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailMessageAnalyticsOverviewDailyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


