/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductUsageHistoryExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUsageHistoryExecution{}

// ProductUsageHistoryExecution struct for ProductUsageHistoryExecution
type ProductUsageHistoryExecution struct {
	ExecutionId NullableString `json:"executionId"`
	Output ProductUsageHistoryOutput `json:"output"`
	Replay bool `json:"replay"`
	Tool string `json:"tool"`
	AdditionalProperties map[string]interface{}
}

type _ProductUsageHistoryExecution ProductUsageHistoryExecution

// NewProductUsageHistoryExecution instantiates a new ProductUsageHistoryExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUsageHistoryExecution(executionId NullableString, output ProductUsageHistoryOutput, replay bool, tool string) *ProductUsageHistoryExecution {
	this := ProductUsageHistoryExecution{}
	this.ExecutionId = executionId
	this.Output = output
	this.Replay = replay
	this.Tool = tool
	return &this
}

// NewProductUsageHistoryExecutionWithDefaults instantiates a new ProductUsageHistoryExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUsageHistoryExecutionWithDefaults() *ProductUsageHistoryExecution {
	this := ProductUsageHistoryExecution{}
	return &this
}

// GetExecutionId returns the ExecutionId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProductUsageHistoryExecution) GetExecutionId() string {
	if o == nil || o.ExecutionId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExecutionId.Get()
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductUsageHistoryExecution) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecutionId.Get(), o.ExecutionId.IsSet()
}

// SetExecutionId sets field value
func (o *ProductUsageHistoryExecution) SetExecutionId(v string) {
	o.ExecutionId.Set(&v)
}

// GetOutput returns the Output field value
func (o *ProductUsageHistoryExecution) GetOutput() ProductUsageHistoryOutput {
	if o == nil {
		var ret ProductUsageHistoryOutput
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *ProductUsageHistoryExecution) GetOutputOk() (*ProductUsageHistoryOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *ProductUsageHistoryExecution) SetOutput(v ProductUsageHistoryOutput) {
	o.Output = v
}

// GetReplay returns the Replay field value
func (o *ProductUsageHistoryExecution) GetReplay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Replay
}

// GetReplayOk returns a tuple with the Replay field value
// and a boolean to check if the value has been set.
func (o *ProductUsageHistoryExecution) GetReplayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replay, true
}

// SetReplay sets field value
func (o *ProductUsageHistoryExecution) SetReplay(v bool) {
	o.Replay = v
}

// GetTool returns the Tool field value
func (o *ProductUsageHistoryExecution) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *ProductUsageHistoryExecution) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *ProductUsageHistoryExecution) SetTool(v string) {
	o.Tool = v
}

func (o ProductUsageHistoryExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUsageHistoryExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["executionId"] = o.ExecutionId.Get()
	toSerialize["output"] = o.Output
	toSerialize["replay"] = o.Replay
	toSerialize["tool"] = o.Tool

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductUsageHistoryExecution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"executionId",
		"output",
		"replay",
		"tool",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductUsageHistoryExecution := _ProductUsageHistoryExecution{}

	err = json.Unmarshal(data, &varProductUsageHistoryExecution)

	if err != nil {
		return err
	}

	*o = ProductUsageHistoryExecution(varProductUsageHistoryExecution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "executionId")
		delete(additionalProperties, "output")
		delete(additionalProperties, "replay")
		delete(additionalProperties, "tool")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductUsageHistoryExecution struct {
	value *ProductUsageHistoryExecution
	isSet bool
}

func (v NullableProductUsageHistoryExecution) Get() *ProductUsageHistoryExecution {
	return v.value
}

func (v *NullableProductUsageHistoryExecution) Set(val *ProductUsageHistoryExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUsageHistoryExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUsageHistoryExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUsageHistoryExecution(val *ProductUsageHistoryExecution) *NullableProductUsageHistoryExecution {
	return &NullableProductUsageHistoryExecution{value: val, isSet: true}
}

func (v NullableProductUsageHistoryExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUsageHistoryExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


