/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailGetCadenceCampaignsResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailGetCadenceCampaignsResponse200{}

// MailGetCadenceCampaignsResponse200 struct for MailGetCadenceCampaignsResponse200
type MailGetCadenceCampaignsResponse200 struct {
	Results []MailCadenceCampaignRecord `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _MailGetCadenceCampaignsResponse200 MailGetCadenceCampaignsResponse200

// NewMailGetCadenceCampaignsResponse200 instantiates a new MailGetCadenceCampaignsResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailGetCadenceCampaignsResponse200(results []MailCadenceCampaignRecord) *MailGetCadenceCampaignsResponse200 {
	this := MailGetCadenceCampaignsResponse200{}
	this.Results = results
	return &this
}

// NewMailGetCadenceCampaignsResponse200WithDefaults instantiates a new MailGetCadenceCampaignsResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailGetCadenceCampaignsResponse200WithDefaults() *MailGetCadenceCampaignsResponse200 {
	this := MailGetCadenceCampaignsResponse200{}
	return &this
}

// GetResults returns the Results field value
func (o *MailGetCadenceCampaignsResponse200) GetResults() []MailCadenceCampaignRecord {
	if o == nil {
		var ret []MailCadenceCampaignRecord
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *MailGetCadenceCampaignsResponse200) GetResultsOk() ([]MailCadenceCampaignRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *MailGetCadenceCampaignsResponse200) SetResults(v []MailCadenceCampaignRecord) {
	o.Results = v
}

func (o MailGetCadenceCampaignsResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailGetCadenceCampaignsResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailGetCadenceCampaignsResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailGetCadenceCampaignsResponse200 := _MailGetCadenceCampaignsResponse200{}

	err = json.Unmarshal(data, &varMailGetCadenceCampaignsResponse200)

	if err != nil {
		return err
	}

	*o = MailGetCadenceCampaignsResponse200(varMailGetCadenceCampaignsResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailGetCadenceCampaignsResponse200 struct {
	value *MailGetCadenceCampaignsResponse200
	isSet bool
}

func (v NullableMailGetCadenceCampaignsResponse200) Get() *MailGetCadenceCampaignsResponse200 {
	return v.value
}

func (v *NullableMailGetCadenceCampaignsResponse200) Set(val *MailGetCadenceCampaignsResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailGetCadenceCampaignsResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailGetCadenceCampaignsResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailGetCadenceCampaignsResponse200(val *MailGetCadenceCampaignsResponse200) *NullableMailGetCadenceCampaignsResponse200 {
	return &NullableMailGetCadenceCampaignsResponse200{value: val, isSet: true}
}

func (v NullableMailGetCadenceCampaignsResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailGetCadenceCampaignsResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


