/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the StartAttioOAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAttioOAuthRequest{}

// StartAttioOAuthRequest struct for StartAttioOAuthRequest
type StartAttioOAuthRequest struct {
	ReturnPath *string `json:"returnPath,omitempty"`
}

// NewStartAttioOAuthRequest instantiates a new StartAttioOAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAttioOAuthRequest() *StartAttioOAuthRequest {
	this := StartAttioOAuthRequest{}
	return &this
}

// NewStartAttioOAuthRequestWithDefaults instantiates a new StartAttioOAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAttioOAuthRequestWithDefaults() *StartAttioOAuthRequest {
	this := StartAttioOAuthRequest{}
	return &this
}

// GetReturnPath returns the ReturnPath field value if set, zero value otherwise.
func (o *StartAttioOAuthRequest) GetReturnPath() string {
	if o == nil || IsNil(o.ReturnPath) {
		var ret string
		return ret
	}
	return *o.ReturnPath
}

// GetReturnPathOk returns a tuple with the ReturnPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAttioOAuthRequest) GetReturnPathOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnPath) {
		return nil, false
	}
	return o.ReturnPath, true
}

// HasReturnPath returns a boolean if a field has been set.
func (o *StartAttioOAuthRequest) HasReturnPath() bool {
	if o != nil && !IsNil(o.ReturnPath) {
		return true
	}

	return false
}

// SetReturnPath gets a reference to the given string and assigns it to the ReturnPath field.
func (o *StartAttioOAuthRequest) SetReturnPath(v string) {
	o.ReturnPath = &v
}

func (o StartAttioOAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAttioOAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReturnPath) {
		toSerialize["returnPath"] = o.ReturnPath
	}
	return toSerialize, nil
}

type NullableStartAttioOAuthRequest struct {
	value *StartAttioOAuthRequest
	isSet bool
}

func (v NullableStartAttioOAuthRequest) Get() *StartAttioOAuthRequest {
	return v.value
}

func (v *NullableStartAttioOAuthRequest) Set(val *StartAttioOAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAttioOAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAttioOAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAttioOAuthRequest(val *StartAttioOAuthRequest) *NullableStartAttioOAuthRequest {
	return &NullableStartAttioOAuthRequest{value: val, isSet: true}
}

func (v NullableStartAttioOAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAttioOAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


