/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostDeliverabilityDomainHealthResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostDeliverabilityDomainHealthResponse200{}

// MailPostDeliverabilityDomainHealthResponse200 struct for MailPostDeliverabilityDomainHealthResponse200
type MailPostDeliverabilityDomainHealthResponse200 struct {
	Report MailDomainHealthReport `json:"report"`
	AdditionalProperties map[string]interface{}
}

type _MailPostDeliverabilityDomainHealthResponse200 MailPostDeliverabilityDomainHealthResponse200

// NewMailPostDeliverabilityDomainHealthResponse200 instantiates a new MailPostDeliverabilityDomainHealthResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostDeliverabilityDomainHealthResponse200(report MailDomainHealthReport) *MailPostDeliverabilityDomainHealthResponse200 {
	this := MailPostDeliverabilityDomainHealthResponse200{}
	this.Report = report
	return &this
}

// NewMailPostDeliverabilityDomainHealthResponse200WithDefaults instantiates a new MailPostDeliverabilityDomainHealthResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostDeliverabilityDomainHealthResponse200WithDefaults() *MailPostDeliverabilityDomainHealthResponse200 {
	this := MailPostDeliverabilityDomainHealthResponse200{}
	return &this
}

// GetReport returns the Report field value
func (o *MailPostDeliverabilityDomainHealthResponse200) GetReport() MailDomainHealthReport {
	if o == nil {
		var ret MailDomainHealthReport
		return ret
	}

	return o.Report
}

// GetReportOk returns a tuple with the Report field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityDomainHealthResponse200) GetReportOk() (*MailDomainHealthReport, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Report, true
}

// SetReport sets field value
func (o *MailPostDeliverabilityDomainHealthResponse200) SetReport(v MailDomainHealthReport) {
	o.Report = v
}

func (o MailPostDeliverabilityDomainHealthResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostDeliverabilityDomainHealthResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["report"] = o.Report

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostDeliverabilityDomainHealthResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"report",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostDeliverabilityDomainHealthResponse200 := _MailPostDeliverabilityDomainHealthResponse200{}

	err = json.Unmarshal(data, &varMailPostDeliverabilityDomainHealthResponse200)

	if err != nil {
		return err
	}

	*o = MailPostDeliverabilityDomainHealthResponse200(varMailPostDeliverabilityDomainHealthResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "report")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostDeliverabilityDomainHealthResponse200 struct {
	value *MailPostDeliverabilityDomainHealthResponse200
	isSet bool
}

func (v NullableMailPostDeliverabilityDomainHealthResponse200) Get() *MailPostDeliverabilityDomainHealthResponse200 {
	return v.value
}

func (v *NullableMailPostDeliverabilityDomainHealthResponse200) Set(val *MailPostDeliverabilityDomainHealthResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostDeliverabilityDomainHealthResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostDeliverabilityDomainHealthResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostDeliverabilityDomainHealthResponse200(val *MailPostDeliverabilityDomainHealthResponse200) *NullableMailPostDeliverabilityDomainHealthResponse200 {
	return &NullableMailPostDeliverabilityDomainHealthResponse200{value: val, isSet: true}
}

func (v NullableMailPostDeliverabilityDomainHealthResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostDeliverabilityDomainHealthResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


