/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostPortfolioResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostPortfolioResponse200{}

// MailPostPortfolioResponse200 struct for MailPostPortfolioResponse200
type MailPostPortfolioResponse200 struct {
	Portfolio MailMailPortfolio `json:"portfolio"`
	Suppressions []map[string]interface{} `json:"suppressions"`
	Teams []MailMailPortfolioTeam `json:"teams"`
	AdditionalProperties map[string]interface{}
}

type _MailPostPortfolioResponse200 MailPostPortfolioResponse200

// NewMailPostPortfolioResponse200 instantiates a new MailPostPortfolioResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostPortfolioResponse200(portfolio MailMailPortfolio, suppressions []map[string]interface{}, teams []MailMailPortfolioTeam) *MailPostPortfolioResponse200 {
	this := MailPostPortfolioResponse200{}
	this.Portfolio = portfolio
	this.Suppressions = suppressions
	this.Teams = teams
	return &this
}

// NewMailPostPortfolioResponse200WithDefaults instantiates a new MailPostPortfolioResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostPortfolioResponse200WithDefaults() *MailPostPortfolioResponse200 {
	this := MailPostPortfolioResponse200{}
	return &this
}

// GetPortfolio returns the Portfolio field value
func (o *MailPostPortfolioResponse200) GetPortfolio() MailMailPortfolio {
	if o == nil {
		var ret MailMailPortfolio
		return ret
	}

	return o.Portfolio
}

// GetPortfolioOk returns a tuple with the Portfolio field value
// and a boolean to check if the value has been set.
func (o *MailPostPortfolioResponse200) GetPortfolioOk() (*MailMailPortfolio, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Portfolio, true
}

// SetPortfolio sets field value
func (o *MailPostPortfolioResponse200) SetPortfolio(v MailMailPortfolio) {
	o.Portfolio = v
}

// GetSuppressions returns the Suppressions field value
func (o *MailPostPortfolioResponse200) GetSuppressions() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Suppressions
}

// GetSuppressionsOk returns a tuple with the Suppressions field value
// and a boolean to check if the value has been set.
func (o *MailPostPortfolioResponse200) GetSuppressionsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Suppressions, true
}

// SetSuppressions sets field value
func (o *MailPostPortfolioResponse200) SetSuppressions(v []map[string]interface{}) {
	o.Suppressions = v
}

// GetTeams returns the Teams field value
func (o *MailPostPortfolioResponse200) GetTeams() []MailMailPortfolioTeam {
	if o == nil {
		var ret []MailMailPortfolioTeam
		return ret
	}

	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value
// and a boolean to check if the value has been set.
func (o *MailPostPortfolioResponse200) GetTeamsOk() ([]MailMailPortfolioTeam, bool) {
	if o == nil {
		return nil, false
	}
	return o.Teams, true
}

// SetTeams sets field value
func (o *MailPostPortfolioResponse200) SetTeams(v []MailMailPortfolioTeam) {
	o.Teams = v
}

func (o MailPostPortfolioResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostPortfolioResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["portfolio"] = o.Portfolio
	toSerialize["suppressions"] = o.Suppressions
	toSerialize["teams"] = o.Teams

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostPortfolioResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"portfolio",
		"suppressions",
		"teams",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostPortfolioResponse200 := _MailPostPortfolioResponse200{}

	err = json.Unmarshal(data, &varMailPostPortfolioResponse200)

	if err != nil {
		return err
	}

	*o = MailPostPortfolioResponse200(varMailPostPortfolioResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "portfolio")
		delete(additionalProperties, "suppressions")
		delete(additionalProperties, "teams")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostPortfolioResponse200 struct {
	value *MailPostPortfolioResponse200
	isSet bool
}

func (v NullableMailPostPortfolioResponse200) Get() *MailPostPortfolioResponse200 {
	return v.value
}

func (v *NullableMailPostPortfolioResponse200) Set(val *MailPostPortfolioResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostPortfolioResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostPortfolioResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostPortfolioResponse200(val *MailPostPortfolioResponse200) *NullableMailPostPortfolioResponse200 {
	return &NullableMailPostPortfolioResponse200{value: val, isSet: true}
}

func (v NullableMailPostPortfolioResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostPortfolioResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


