/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the EmailRevealResponseProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailRevealResponseProfile{}

// EmailRevealResponseProfile struct for EmailRevealResponseProfile
type EmailRevealResponseProfile struct {
	Category NullableString `json:"category,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Domain string `json:"domain"`
	Email string `json:"email"`
	FirstName NullableString `json:"first_name,omitempty"`
	FirstSeen string `json:"first_seen"`
	FullName NullableString `json:"full_name,omitempty"`
	Id string `json:"id"`
	LastName NullableString `json:"last_name,omitempty"`
	LastSeen string `json:"last_seen"`
	Linkedin NullableString `json:"linkedin,omitempty"`
	Position NullableString `json:"position,omitempty"`
	Score float32 `json:"score"`
	// Known values: VALID, CATCHALL, UNKNOWN, INVALID. Clients preserve future values.
	Status string `json:"status"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EmailRevealResponseProfile EmailRevealResponseProfile

// NewEmailRevealResponseProfile instantiates a new EmailRevealResponseProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailRevealResponseProfile(domain string, email string, firstSeen string, id string, lastSeen string, score float32, status string) *EmailRevealResponseProfile {
	this := EmailRevealResponseProfile{}
	this.Domain = domain
	this.Email = email
	this.FirstSeen = firstSeen
	this.Id = id
	this.LastSeen = lastSeen
	this.Score = score
	this.Status = status
	return &this
}

// NewEmailRevealResponseProfileWithDefaults instantiates a new EmailRevealResponseProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailRevealResponseProfileWithDefaults() *EmailRevealResponseProfile {
	this := EmailRevealResponseProfile{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *EmailRevealResponseProfile) SetCategory(v string) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *EmailRevealResponseProfile) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetCategory() {
	o.Category.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EmailRevealResponseProfile) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *EmailRevealResponseProfile) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDomain returns the Domain field value
func (o *EmailRevealResponseProfile) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *EmailRevealResponseProfile) SetDomain(v string) {
	o.Domain = v
}

// GetEmail returns the Email field value
func (o *EmailRevealResponseProfile) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailRevealResponseProfile) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *EmailRevealResponseProfile) SetFirstName(v string) {
	o.FirstName.Set(&v)
}
// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *EmailRevealResponseProfile) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetFirstSeen returns the FirstSeen field value
func (o *EmailRevealResponseProfile) GetFirstSeen() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetFirstSeenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstSeen, true
}

// SetFirstSeen sets field value
func (o *EmailRevealResponseProfile) SetFirstSeen(v string) {
	o.FirstSeen = v
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *EmailRevealResponseProfile) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *EmailRevealResponseProfile) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetFullName() {
	o.FullName.Unset()
}

// GetId returns the Id field value
func (o *EmailRevealResponseProfile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmailRevealResponseProfile) SetId(v string) {
	o.Id = v
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *EmailRevealResponseProfile) SetLastName(v string) {
	o.LastName.Set(&v)
}
// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *EmailRevealResponseProfile) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetLastName() {
	o.LastName.Unset()
}

// GetLastSeen returns the LastSeen field value
func (o *EmailRevealResponseProfile) GetLastSeen() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetLastSeenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeen, true
}

// SetLastSeen sets field value
func (o *EmailRevealResponseProfile) SetLastSeen(v string) {
	o.LastSeen = v
}

// GetLinkedin returns the Linkedin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetLinkedin() string {
	if o == nil || IsNil(o.Linkedin.Get()) {
		var ret string
		return ret
	}
	return *o.Linkedin.Get()
}

// GetLinkedinOk returns a tuple with the Linkedin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetLinkedinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Linkedin.Get(), o.Linkedin.IsSet()
}

// HasLinkedin returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasLinkedin() bool {
	if o != nil && o.Linkedin.IsSet() {
		return true
	}

	return false
}

// SetLinkedin gets a reference to the given NullableString and assigns it to the Linkedin field.
func (o *EmailRevealResponseProfile) SetLinkedin(v string) {
	o.Linkedin.Set(&v)
}
// SetLinkedinNil sets the value for Linkedin to be an explicit nil
func (o *EmailRevealResponseProfile) SetLinkedinNil() {
	o.Linkedin.Set(nil)
}

// UnsetLinkedin ensures that no value is present for Linkedin, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetLinkedin() {
	o.Linkedin.Unset()
}

// GetPosition returns the Position field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailRevealResponseProfile) GetPosition() string {
	if o == nil || IsNil(o.Position.Get()) {
		var ret string
		return ret
	}
	return *o.Position.Get()
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailRevealResponseProfile) GetPositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Position.Get(), o.Position.IsSet()
}

// HasPosition returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasPosition() bool {
	if o != nil && o.Position.IsSet() {
		return true
	}

	return false
}

// SetPosition gets a reference to the given NullableString and assigns it to the Position field.
func (o *EmailRevealResponseProfile) SetPosition(v string) {
	o.Position.Set(&v)
}
// SetPositionNil sets the value for Position to be an explicit nil
func (o *EmailRevealResponseProfile) SetPositionNil() {
	o.Position.Set(nil)
}

// UnsetPosition ensures that no value is present for Position, not even an explicit nil
func (o *EmailRevealResponseProfile) UnsetPosition() {
	o.Position.Unset()
}

// GetScore returns the Score field value
func (o *EmailRevealResponseProfile) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *EmailRevealResponseProfile) SetScore(v float32) {
	o.Score = v
}

// GetStatus returns the Status field value
func (o *EmailRevealResponseProfile) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EmailRevealResponseProfile) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *EmailRevealResponseProfile) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailRevealResponseProfile) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *EmailRevealResponseProfile) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *EmailRevealResponseProfile) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o EmailRevealResponseProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailRevealResponseProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	toSerialize["domain"] = o.Domain
	toSerialize["email"] = o.Email
	if o.FirstName.IsSet() {
		toSerialize["first_name"] = o.FirstName.Get()
	}
	toSerialize["first_seen"] = o.FirstSeen
	if o.FullName.IsSet() {
		toSerialize["full_name"] = o.FullName.Get()
	}
	toSerialize["id"] = o.Id
	if o.LastName.IsSet() {
		toSerialize["last_name"] = o.LastName.Get()
	}
	toSerialize["last_seen"] = o.LastSeen
	if o.Linkedin.IsSet() {
		toSerialize["linkedin"] = o.Linkedin.Get()
	}
	if o.Position.IsSet() {
		toSerialize["position"] = o.Position.Get()
	}
	toSerialize["score"] = o.Score
	toSerialize["status"] = o.Status
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EmailRevealResponseProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"email",
		"first_seen",
		"id",
		"last_seen",
		"score",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailRevealResponseProfile := _EmailRevealResponseProfile{}

	err = json.Unmarshal(data, &varEmailRevealResponseProfile)

	if err != nil {
		return err
	}

	*o = EmailRevealResponseProfile(varEmailRevealResponseProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "category")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "email")
		delete(additionalProperties, "first_name")
		delete(additionalProperties, "first_seen")
		delete(additionalProperties, "full_name")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_name")
		delete(additionalProperties, "last_seen")
		delete(additionalProperties, "linkedin")
		delete(additionalProperties, "position")
		delete(additionalProperties, "score")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEmailRevealResponseProfile struct {
	value *EmailRevealResponseProfile
	isSet bool
}

func (v NullableEmailRevealResponseProfile) Get() *EmailRevealResponseProfile {
	return v.value
}

func (v *NullableEmailRevealResponseProfile) Set(val *EmailRevealResponseProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailRevealResponseProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailRevealResponseProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailRevealResponseProfile(val *EmailRevealResponseProfile) *NullableEmailRevealResponseProfile {
	return &NullableEmailRevealResponseProfile{value: val, isSet: true}
}

func (v NullableEmailRevealResponseProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailRevealResponseProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


