/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigureCrmSyncRequestConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureCrmSyncRequestConfiguration{}

// ConfigureCrmSyncRequestConfiguration struct for ConfigureCrmSyncRequestConfiguration
type ConfigureCrmSyncRequestConfiguration struct {
	Hubspot NullableConfigureCrmSyncRequestConfigurationHubspot `json:"hubspot"`
	Policy ConfigureCrmSyncRequestConfigurationPolicy `json:"policy"`
}

type _ConfigureCrmSyncRequestConfiguration ConfigureCrmSyncRequestConfiguration

// NewConfigureCrmSyncRequestConfiguration instantiates a new ConfigureCrmSyncRequestConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureCrmSyncRequestConfiguration(hubspot NullableConfigureCrmSyncRequestConfigurationHubspot, policy ConfigureCrmSyncRequestConfigurationPolicy) *ConfigureCrmSyncRequestConfiguration {
	this := ConfigureCrmSyncRequestConfiguration{}
	this.Hubspot = hubspot
	this.Policy = policy
	return &this
}

// NewConfigureCrmSyncRequestConfigurationWithDefaults instantiates a new ConfigureCrmSyncRequestConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureCrmSyncRequestConfigurationWithDefaults() *ConfigureCrmSyncRequestConfiguration {
	this := ConfigureCrmSyncRequestConfiguration{}
	return &this
}

// GetHubspot returns the Hubspot field value
// If the value is explicit nil, the zero value for ConfigureCrmSyncRequestConfigurationHubspot will be returned
func (o *ConfigureCrmSyncRequestConfiguration) GetHubspot() ConfigureCrmSyncRequestConfigurationHubspot {
	if o == nil || o.Hubspot.Get() == nil {
		var ret ConfigureCrmSyncRequestConfigurationHubspot
		return ret
	}

	return *o.Hubspot.Get()
}

// GetHubspotOk returns a tuple with the Hubspot field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigureCrmSyncRequestConfiguration) GetHubspotOk() (*ConfigureCrmSyncRequestConfigurationHubspot, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hubspot.Get(), o.Hubspot.IsSet()
}

// SetHubspot sets field value
func (o *ConfigureCrmSyncRequestConfiguration) SetHubspot(v ConfigureCrmSyncRequestConfigurationHubspot) {
	o.Hubspot.Set(&v)
}

// GetPolicy returns the Policy field value
func (o *ConfigureCrmSyncRequestConfiguration) GetPolicy() ConfigureCrmSyncRequestConfigurationPolicy {
	if o == nil {
		var ret ConfigureCrmSyncRequestConfigurationPolicy
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *ConfigureCrmSyncRequestConfiguration) GetPolicyOk() (*ConfigureCrmSyncRequestConfigurationPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *ConfigureCrmSyncRequestConfiguration) SetPolicy(v ConfigureCrmSyncRequestConfigurationPolicy) {
	o.Policy = v
}

func (o ConfigureCrmSyncRequestConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureCrmSyncRequestConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hubspot"] = o.Hubspot.Get()
	toSerialize["policy"] = o.Policy
	return toSerialize, nil
}

func (o *ConfigureCrmSyncRequestConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hubspot",
		"policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureCrmSyncRequestConfiguration := _ConfigureCrmSyncRequestConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigureCrmSyncRequestConfiguration)

	if err != nil {
		return err
	}

	*o = ConfigureCrmSyncRequestConfiguration(varConfigureCrmSyncRequestConfiguration)

	return err
}

type NullableConfigureCrmSyncRequestConfiguration struct {
	value *ConfigureCrmSyncRequestConfiguration
	isSet bool
}

func (v NullableConfigureCrmSyncRequestConfiguration) Get() *ConfigureCrmSyncRequestConfiguration {
	return v.value
}

func (v *NullableConfigureCrmSyncRequestConfiguration) Set(val *ConfigureCrmSyncRequestConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureCrmSyncRequestConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureCrmSyncRequestConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureCrmSyncRequestConfiguration(val *ConfigureCrmSyncRequestConfiguration) *NullableConfigureCrmSyncRequestConfiguration {
	return &NullableConfigureCrmSyncRequestConfiguration{value: val, isSet: true}
}

func (v NullableConfigureCrmSyncRequestConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureCrmSyncRequestConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


