/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostWebhooksResponse201 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostWebhooksResponse201{}

// MailPostWebhooksResponse201 struct for MailPostWebhooksResponse201
type MailPostWebhooksResponse201 struct {
	SigningSecret string `json:"signingSecret"`
	Subscription MailGetWebhooksResponse200SubscriptionsInner `json:"subscription"`
	AdditionalProperties map[string]interface{}
}

type _MailPostWebhooksResponse201 MailPostWebhooksResponse201

// NewMailPostWebhooksResponse201 instantiates a new MailPostWebhooksResponse201 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostWebhooksResponse201(signingSecret string, subscription MailGetWebhooksResponse200SubscriptionsInner) *MailPostWebhooksResponse201 {
	this := MailPostWebhooksResponse201{}
	this.SigningSecret = signingSecret
	this.Subscription = subscription
	return &this
}

// NewMailPostWebhooksResponse201WithDefaults instantiates a new MailPostWebhooksResponse201 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostWebhooksResponse201WithDefaults() *MailPostWebhooksResponse201 {
	this := MailPostWebhooksResponse201{}
	return &this
}

// GetSigningSecret returns the SigningSecret field value
func (o *MailPostWebhooksResponse201) GetSigningSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningSecret
}

// GetSigningSecretOk returns a tuple with the SigningSecret field value
// and a boolean to check if the value has been set.
func (o *MailPostWebhooksResponse201) GetSigningSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningSecret, true
}

// SetSigningSecret sets field value
func (o *MailPostWebhooksResponse201) SetSigningSecret(v string) {
	o.SigningSecret = v
}

// GetSubscription returns the Subscription field value
func (o *MailPostWebhooksResponse201) GetSubscription() MailGetWebhooksResponse200SubscriptionsInner {
	if o == nil {
		var ret MailGetWebhooksResponse200SubscriptionsInner
		return ret
	}

	return o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value
// and a boolean to check if the value has been set.
func (o *MailPostWebhooksResponse201) GetSubscriptionOk() (*MailGetWebhooksResponse200SubscriptionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subscription, true
}

// SetSubscription sets field value
func (o *MailPostWebhooksResponse201) SetSubscription(v MailGetWebhooksResponse200SubscriptionsInner) {
	o.Subscription = v
}

func (o MailPostWebhooksResponse201) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostWebhooksResponse201) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signingSecret"] = o.SigningSecret
	toSerialize["subscription"] = o.Subscription

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostWebhooksResponse201) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signingSecret",
		"subscription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostWebhooksResponse201 := _MailPostWebhooksResponse201{}

	err = json.Unmarshal(data, &varMailPostWebhooksResponse201)

	if err != nil {
		return err
	}

	*o = MailPostWebhooksResponse201(varMailPostWebhooksResponse201)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "signingSecret")
		delete(additionalProperties, "subscription")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostWebhooksResponse201 struct {
	value *MailPostWebhooksResponse201
	isSet bool
}

func (v NullableMailPostWebhooksResponse201) Get() *MailPostWebhooksResponse201 {
	return v.value
}

func (v *NullableMailPostWebhooksResponse201) Set(val *MailPostWebhooksResponse201) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostWebhooksResponse201) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostWebhooksResponse201) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostWebhooksResponse201(val *MailPostWebhooksResponse201) *NullableMailPostWebhooksResponse201 {
	return &NullableMailPostWebhooksResponse201{value: val, isSet: true}
}

func (v NullableMailPostWebhooksResponse201) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostWebhooksResponse201) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


