/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailCadenceNodeAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailCadenceNodeAnyOf{}

// MailCadenceNodeAnyOf struct for MailCadenceNodeAnyOf
type MailCadenceNodeAnyOf struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	NextNodeId string `json:"nextNodeId"`
	AdditionalProperties map[string]interface{}
}

type _MailCadenceNodeAnyOf MailCadenceNodeAnyOf

// NewMailCadenceNodeAnyOf instantiates a new MailCadenceNodeAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailCadenceNodeAnyOf(id string, name string, kind string, nextNodeId string) *MailCadenceNodeAnyOf {
	this := MailCadenceNodeAnyOf{}
	this.Id = id
	this.Name = name
	this.Kind = kind
	this.NextNodeId = nextNodeId
	return &this
}

// NewMailCadenceNodeAnyOfWithDefaults instantiates a new MailCadenceNodeAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailCadenceNodeAnyOfWithDefaults() *MailCadenceNodeAnyOf {
	this := MailCadenceNodeAnyOf{}
	return &this
}

// GetId returns the Id field value
func (o *MailCadenceNodeAnyOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MailCadenceNodeAnyOf) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MailCadenceNodeAnyOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailCadenceNodeAnyOf) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *MailCadenceNodeAnyOf) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MailCadenceNodeAnyOf) SetKind(v string) {
	o.Kind = v
}

// GetNextNodeId returns the NextNodeId field value
func (o *MailCadenceNodeAnyOf) GetNextNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextNodeId
}

// GetNextNodeIdOk returns a tuple with the NextNodeId field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf) GetNextNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextNodeId, true
}

// SetNextNodeId sets field value
func (o *MailCadenceNodeAnyOf) SetNextNodeId(v string) {
	o.NextNodeId = v
}

func (o MailCadenceNodeAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailCadenceNodeAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["nextNodeId"] = o.NextNodeId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailCadenceNodeAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"kind",
		"nextNodeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailCadenceNodeAnyOf := _MailCadenceNodeAnyOf{}

	err = json.Unmarshal(data, &varMailCadenceNodeAnyOf)

	if err != nil {
		return err
	}

	*o = MailCadenceNodeAnyOf(varMailCadenceNodeAnyOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "nextNodeId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailCadenceNodeAnyOf struct {
	value *MailCadenceNodeAnyOf
	isSet bool
}

func (v NullableMailCadenceNodeAnyOf) Get() *MailCadenceNodeAnyOf {
	return v.value
}

func (v *NullableMailCadenceNodeAnyOf) Set(val *MailCadenceNodeAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMailCadenceNodeAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMailCadenceNodeAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailCadenceNodeAnyOf(val *MailCadenceNodeAnyOf) *NullableMailCadenceNodeAnyOf {
	return &NullableMailCadenceNodeAnyOf{value: val, isSet: true}
}

func (v NullableMailCadenceNodeAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailCadenceNodeAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


