/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MailPostCrmTasksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCrmTasksRequest{}

// MailPostCrmTasksRequest struct for MailPostCrmTasksRequest
type MailPostCrmTasksRequest struct {
	AssignedToActorId string `json:"assignedToActorId"`
	ContactId string `json:"contactId"`
	DueAt time.Time `json:"dueAt"`
	Title string `json:"title"`
	Type string `json:"type"`
}

type _MailPostCrmTasksRequest MailPostCrmTasksRequest

// NewMailPostCrmTasksRequest instantiates a new MailPostCrmTasksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCrmTasksRequest(assignedToActorId string, contactId string, dueAt time.Time, title string, type_ string) *MailPostCrmTasksRequest {
	this := MailPostCrmTasksRequest{}
	this.AssignedToActorId = assignedToActorId
	this.ContactId = contactId
	this.DueAt = dueAt
	this.Title = title
	this.Type = type_
	return &this
}

// NewMailPostCrmTasksRequestWithDefaults instantiates a new MailPostCrmTasksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCrmTasksRequestWithDefaults() *MailPostCrmTasksRequest {
	this := MailPostCrmTasksRequest{}
	return &this
}

// GetAssignedToActorId returns the AssignedToActorId field value
func (o *MailPostCrmTasksRequest) GetAssignedToActorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssignedToActorId
}

// GetAssignedToActorIdOk returns a tuple with the AssignedToActorId field value
// and a boolean to check if the value has been set.
func (o *MailPostCrmTasksRequest) GetAssignedToActorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssignedToActorId, true
}

// SetAssignedToActorId sets field value
func (o *MailPostCrmTasksRequest) SetAssignedToActorId(v string) {
	o.AssignedToActorId = v
}

// GetContactId returns the ContactId field value
func (o *MailPostCrmTasksRequest) GetContactId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactId
}

// GetContactIdOk returns a tuple with the ContactId field value
// and a boolean to check if the value has been set.
func (o *MailPostCrmTasksRequest) GetContactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactId, true
}

// SetContactId sets field value
func (o *MailPostCrmTasksRequest) SetContactId(v string) {
	o.ContactId = v
}

// GetDueAt returns the DueAt field value
func (o *MailPostCrmTasksRequest) GetDueAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DueAt
}

// GetDueAtOk returns a tuple with the DueAt field value
// and a boolean to check if the value has been set.
func (o *MailPostCrmTasksRequest) GetDueAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DueAt, true
}

// SetDueAt sets field value
func (o *MailPostCrmTasksRequest) SetDueAt(v time.Time) {
	o.DueAt = v
}

// GetTitle returns the Title field value
func (o *MailPostCrmTasksRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MailPostCrmTasksRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MailPostCrmTasksRequest) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *MailPostCrmTasksRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MailPostCrmTasksRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MailPostCrmTasksRequest) SetType(v string) {
	o.Type = v
}

func (o MailPostCrmTasksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCrmTasksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assignedToActorId"] = o.AssignedToActorId
	toSerialize["contactId"] = o.ContactId
	toSerialize["dueAt"] = o.DueAt
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MailPostCrmTasksRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assignedToActorId",
		"contactId",
		"dueAt",
		"title",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCrmTasksRequest := _MailPostCrmTasksRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostCrmTasksRequest)

	if err != nil {
		return err
	}

	*o = MailPostCrmTasksRequest(varMailPostCrmTasksRequest)

	return err
}

type NullableMailPostCrmTasksRequest struct {
	value *MailPostCrmTasksRequest
	isSet bool
}

func (v NullableMailPostCrmTasksRequest) Get() *MailPostCrmTasksRequest {
	return v.value
}

func (v *NullableMailPostCrmTasksRequest) Set(val *MailPostCrmTasksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCrmTasksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCrmTasksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCrmTasksRequest(val *MailPostCrmTasksRequest) *NullableMailPostCrmTasksRequest {
	return &NullableMailPostCrmTasksRequest{value: val, isSet: true}
}

func (v NullableMailPostCrmTasksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCrmTasksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


