/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MailPostCampaignsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCampaignsRequest{}

// MailPostCampaignsRequest struct for MailPostCampaignsRequest
type MailPostCampaignsRequest struct {
	AudienceListIds []string `json:"audienceListIds,omitempty"`
	MailboxIds []string `json:"mailboxIds,omitempty"`
	MailboxPoolId *string `json:"mailboxPoolId,omitempty"`
	Name string `json:"name"`
	Policy *MailPatchCampaignsByCampaignIdRequestPolicy `json:"policy,omitempty"`
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`
	Steps []MailPatchCampaignsByCampaignIdRequestStepsInner `json:"steps,omitempty"`
}

type _MailPostCampaignsRequest MailPostCampaignsRequest

// NewMailPostCampaignsRequest instantiates a new MailPostCampaignsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCampaignsRequest(name string) *MailPostCampaignsRequest {
	this := MailPostCampaignsRequest{}
	this.Name = name
	return &this
}

// NewMailPostCampaignsRequestWithDefaults instantiates a new MailPostCampaignsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCampaignsRequestWithDefaults() *MailPostCampaignsRequest {
	this := MailPostCampaignsRequest{}
	return &this
}

// GetAudienceListIds returns the AudienceListIds field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetAudienceListIds() []string {
	if o == nil || IsNil(o.AudienceListIds) {
		var ret []string
		return ret
	}
	return o.AudienceListIds
}

// GetAudienceListIdsOk returns a tuple with the AudienceListIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetAudienceListIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AudienceListIds) {
		return nil, false
	}
	return o.AudienceListIds, true
}

// HasAudienceListIds returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasAudienceListIds() bool {
	if o != nil && !IsNil(o.AudienceListIds) {
		return true
	}

	return false
}

// SetAudienceListIds gets a reference to the given []string and assigns it to the AudienceListIds field.
func (o *MailPostCampaignsRequest) SetAudienceListIds(v []string) {
	o.AudienceListIds = v
}

// GetMailboxIds returns the MailboxIds field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetMailboxIds() []string {
	if o == nil || IsNil(o.MailboxIds) {
		var ret []string
		return ret
	}
	return o.MailboxIds
}

// GetMailboxIdsOk returns a tuple with the MailboxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetMailboxIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.MailboxIds) {
		return nil, false
	}
	return o.MailboxIds, true
}

// HasMailboxIds returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasMailboxIds() bool {
	if o != nil && !IsNil(o.MailboxIds) {
		return true
	}

	return false
}

// SetMailboxIds gets a reference to the given []string and assigns it to the MailboxIds field.
func (o *MailPostCampaignsRequest) SetMailboxIds(v []string) {
	o.MailboxIds = v
}

// GetMailboxPoolId returns the MailboxPoolId field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetMailboxPoolId() string {
	if o == nil || IsNil(o.MailboxPoolId) {
		var ret string
		return ret
	}
	return *o.MailboxPoolId
}

// GetMailboxPoolIdOk returns a tuple with the MailboxPoolId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetMailboxPoolIdOk() (*string, bool) {
	if o == nil || IsNil(o.MailboxPoolId) {
		return nil, false
	}
	return o.MailboxPoolId, true
}

// HasMailboxPoolId returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasMailboxPoolId() bool {
	if o != nil && !IsNil(o.MailboxPoolId) {
		return true
	}

	return false
}

// SetMailboxPoolId gets a reference to the given string and assigns it to the MailboxPoolId field.
func (o *MailPostCampaignsRequest) SetMailboxPoolId(v string) {
	o.MailboxPoolId = &v
}

// GetName returns the Name field value
func (o *MailPostCampaignsRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailPostCampaignsRequest) SetName(v string) {
	o.Name = v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetPolicy() MailPatchCampaignsByCampaignIdRequestPolicy {
	if o == nil || IsNil(o.Policy) {
		var ret MailPatchCampaignsByCampaignIdRequestPolicy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetPolicyOk() (*MailPatchCampaignsByCampaignIdRequestPolicy, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given MailPatchCampaignsByCampaignIdRequestPolicy and assigns it to the Policy field.
func (o *MailPostCampaignsRequest) SetPolicy(v MailPatchCampaignsByCampaignIdRequestPolicy) {
	o.Policy = &v
}

// GetScheduledAt returns the ScheduledAt field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetScheduledAt() time.Time {
	if o == nil || IsNil(o.ScheduledAt) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledAt
}

// GetScheduledAtOk returns a tuple with the ScheduledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetScheduledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledAt) {
		return nil, false
	}
	return o.ScheduledAt, true
}

// HasScheduledAt returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasScheduledAt() bool {
	if o != nil && !IsNil(o.ScheduledAt) {
		return true
	}

	return false
}

// SetScheduledAt gets a reference to the given time.Time and assigns it to the ScheduledAt field.
func (o *MailPostCampaignsRequest) SetScheduledAt(v time.Time) {
	o.ScheduledAt = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *MailPostCampaignsRequest) GetSteps() []MailPatchCampaignsByCampaignIdRequestStepsInner {
	if o == nil || IsNil(o.Steps) {
		var ret []MailPatchCampaignsByCampaignIdRequestStepsInner
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsRequest) GetStepsOk() ([]MailPatchCampaignsByCampaignIdRequestStepsInner, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *MailPostCampaignsRequest) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []MailPatchCampaignsByCampaignIdRequestStepsInner and assigns it to the Steps field.
func (o *MailPostCampaignsRequest) SetSteps(v []MailPatchCampaignsByCampaignIdRequestStepsInner) {
	o.Steps = v
}

func (o MailPostCampaignsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCampaignsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AudienceListIds) {
		toSerialize["audienceListIds"] = o.AudienceListIds
	}
	if !IsNil(o.MailboxIds) {
		toSerialize["mailboxIds"] = o.MailboxIds
	}
	if !IsNil(o.MailboxPoolId) {
		toSerialize["mailboxPoolId"] = o.MailboxPoolId
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.ScheduledAt) {
		toSerialize["scheduledAt"] = o.ScheduledAt
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return toSerialize, nil
}

func (o *MailPostCampaignsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCampaignsRequest := _MailPostCampaignsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostCampaignsRequest)

	if err != nil {
		return err
	}

	*o = MailPostCampaignsRequest(varMailPostCampaignsRequest)

	return err
}

type NullableMailPostCampaignsRequest struct {
	value *MailPostCampaignsRequest
	isSet bool
}

func (v NullableMailPostCampaignsRequest) Get() *MailPostCampaignsRequest {
	return v.value
}

func (v *NullableMailPostCampaignsRequest) Set(val *MailPostCampaignsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCampaignsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCampaignsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCampaignsRequest(val *MailPostCampaignsRequest) *NullableMailPostCampaignsRequest {
	return &NullableMailPostCampaignsRequest{value: val, isSet: true}
}

func (v NullableMailPostCampaignsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCampaignsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


