/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the MailMessageAnalyticsOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailMessageAnalyticsOverview{}

// MailMessageAnalyticsOverview struct for MailMessageAnalyticsOverview
type MailMessageAnalyticsOverview struct {
	AcceptanceRate float32 `json:"acceptanceRate"`
	AverageAcceptanceLatencyMs NullableFloat32 `json:"averageAcceptanceLatencyMs"`
	BounceRate float32 `json:"bounceRate"`
	ComplaintRate float32 `json:"complaintRate"`
	Counts MailCampaignProgressMessageCounts `json:"counts"`
	Daily []MailMessageAnalyticsOverviewDailyInner `json:"daily"`
	DeliveryRate float32 `json:"deliveryRate"`
	From time.Time `json:"from"`
	Mailboxes []MailMessageAnalyticsOverviewMailboxesInner `json:"mailboxes"`
	ReplyRate float32 `json:"replyRate"`
	To time.Time `json:"to"`
	Total float32 `json:"total"`
	Variants []MailMessageAnalyticsOverviewVariantsInner `json:"variants"`
	AdditionalProperties map[string]interface{}
}

type _MailMessageAnalyticsOverview MailMessageAnalyticsOverview

// NewMailMessageAnalyticsOverview instantiates a new MailMessageAnalyticsOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailMessageAnalyticsOverview(acceptanceRate float32, averageAcceptanceLatencyMs NullableFloat32, bounceRate float32, complaintRate float32, counts MailCampaignProgressMessageCounts, daily []MailMessageAnalyticsOverviewDailyInner, deliveryRate float32, from time.Time, mailboxes []MailMessageAnalyticsOverviewMailboxesInner, replyRate float32, to time.Time, total float32, variants []MailMessageAnalyticsOverviewVariantsInner) *MailMessageAnalyticsOverview {
	this := MailMessageAnalyticsOverview{}
	this.AcceptanceRate = acceptanceRate
	this.AverageAcceptanceLatencyMs = averageAcceptanceLatencyMs
	this.BounceRate = bounceRate
	this.ComplaintRate = complaintRate
	this.Counts = counts
	this.Daily = daily
	this.DeliveryRate = deliveryRate
	this.From = from
	this.Mailboxes = mailboxes
	this.ReplyRate = replyRate
	this.To = to
	this.Total = total
	this.Variants = variants
	return &this
}

// NewMailMessageAnalyticsOverviewWithDefaults instantiates a new MailMessageAnalyticsOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailMessageAnalyticsOverviewWithDefaults() *MailMessageAnalyticsOverview {
	this := MailMessageAnalyticsOverview{}
	return &this
}

// GetAcceptanceRate returns the AcceptanceRate field value
func (o *MailMessageAnalyticsOverview) GetAcceptanceRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AcceptanceRate
}

// GetAcceptanceRateOk returns a tuple with the AcceptanceRate field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetAcceptanceRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptanceRate, true
}

// SetAcceptanceRate sets field value
func (o *MailMessageAnalyticsOverview) SetAcceptanceRate(v float32) {
	o.AcceptanceRate = v
}

// GetAverageAcceptanceLatencyMs returns the AverageAcceptanceLatencyMs field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *MailMessageAnalyticsOverview) GetAverageAcceptanceLatencyMs() float32 {
	if o == nil || o.AverageAcceptanceLatencyMs.Get() == nil {
		var ret float32
		return ret
	}

	return *o.AverageAcceptanceLatencyMs.Get()
}

// GetAverageAcceptanceLatencyMsOk returns a tuple with the AverageAcceptanceLatencyMs field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailMessageAnalyticsOverview) GetAverageAcceptanceLatencyMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AverageAcceptanceLatencyMs.Get(), o.AverageAcceptanceLatencyMs.IsSet()
}

// SetAverageAcceptanceLatencyMs sets field value
func (o *MailMessageAnalyticsOverview) SetAverageAcceptanceLatencyMs(v float32) {
	o.AverageAcceptanceLatencyMs.Set(&v)
}

// GetBounceRate returns the BounceRate field value
func (o *MailMessageAnalyticsOverview) GetBounceRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BounceRate
}

// GetBounceRateOk returns a tuple with the BounceRate field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetBounceRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BounceRate, true
}

// SetBounceRate sets field value
func (o *MailMessageAnalyticsOverview) SetBounceRate(v float32) {
	o.BounceRate = v
}

// GetComplaintRate returns the ComplaintRate field value
func (o *MailMessageAnalyticsOverview) GetComplaintRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ComplaintRate
}

// GetComplaintRateOk returns a tuple with the ComplaintRate field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetComplaintRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComplaintRate, true
}

// SetComplaintRate sets field value
func (o *MailMessageAnalyticsOverview) SetComplaintRate(v float32) {
	o.ComplaintRate = v
}

// GetCounts returns the Counts field value
func (o *MailMessageAnalyticsOverview) GetCounts() MailCampaignProgressMessageCounts {
	if o == nil {
		var ret MailCampaignProgressMessageCounts
		return ret
	}

	return o.Counts
}

// GetCountsOk returns a tuple with the Counts field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetCountsOk() (*MailCampaignProgressMessageCounts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Counts, true
}

// SetCounts sets field value
func (o *MailMessageAnalyticsOverview) SetCounts(v MailCampaignProgressMessageCounts) {
	o.Counts = v
}

// GetDaily returns the Daily field value
func (o *MailMessageAnalyticsOverview) GetDaily() []MailMessageAnalyticsOverviewDailyInner {
	if o == nil {
		var ret []MailMessageAnalyticsOverviewDailyInner
		return ret
	}

	return o.Daily
}

// GetDailyOk returns a tuple with the Daily field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetDailyOk() ([]MailMessageAnalyticsOverviewDailyInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Daily, true
}

// SetDaily sets field value
func (o *MailMessageAnalyticsOverview) SetDaily(v []MailMessageAnalyticsOverviewDailyInner) {
	o.Daily = v
}

// GetDeliveryRate returns the DeliveryRate field value
func (o *MailMessageAnalyticsOverview) GetDeliveryRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DeliveryRate
}

// GetDeliveryRateOk returns a tuple with the DeliveryRate field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetDeliveryRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryRate, true
}

// SetDeliveryRate sets field value
func (o *MailMessageAnalyticsOverview) SetDeliveryRate(v float32) {
	o.DeliveryRate = v
}

// GetFrom returns the From field value
func (o *MailMessageAnalyticsOverview) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *MailMessageAnalyticsOverview) SetFrom(v time.Time) {
	o.From = v
}

// GetMailboxes returns the Mailboxes field value
func (o *MailMessageAnalyticsOverview) GetMailboxes() []MailMessageAnalyticsOverviewMailboxesInner {
	if o == nil {
		var ret []MailMessageAnalyticsOverviewMailboxesInner
		return ret
	}

	return o.Mailboxes
}

// GetMailboxesOk returns a tuple with the Mailboxes field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetMailboxesOk() ([]MailMessageAnalyticsOverviewMailboxesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mailboxes, true
}

// SetMailboxes sets field value
func (o *MailMessageAnalyticsOverview) SetMailboxes(v []MailMessageAnalyticsOverviewMailboxesInner) {
	o.Mailboxes = v
}

// GetReplyRate returns the ReplyRate field value
func (o *MailMessageAnalyticsOverview) GetReplyRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReplyRate
}

// GetReplyRateOk returns a tuple with the ReplyRate field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetReplyRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReplyRate, true
}

// SetReplyRate sets field value
func (o *MailMessageAnalyticsOverview) SetReplyRate(v float32) {
	o.ReplyRate = v
}

// GetTo returns the To field value
func (o *MailMessageAnalyticsOverview) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *MailMessageAnalyticsOverview) SetTo(v time.Time) {
	o.To = v
}

// GetTotal returns the Total field value
func (o *MailMessageAnalyticsOverview) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MailMessageAnalyticsOverview) SetTotal(v float32) {
	o.Total = v
}

// GetVariants returns the Variants field value
func (o *MailMessageAnalyticsOverview) GetVariants() []MailMessageAnalyticsOverviewVariantsInner {
	if o == nil {
		var ret []MailMessageAnalyticsOverviewVariantsInner
		return ret
	}

	return o.Variants
}

// GetVariantsOk returns a tuple with the Variants field value
// and a boolean to check if the value has been set.
func (o *MailMessageAnalyticsOverview) GetVariantsOk() ([]MailMessageAnalyticsOverviewVariantsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Variants, true
}

// SetVariants sets field value
func (o *MailMessageAnalyticsOverview) SetVariants(v []MailMessageAnalyticsOverviewVariantsInner) {
	o.Variants = v
}

func (o MailMessageAnalyticsOverview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailMessageAnalyticsOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["acceptanceRate"] = o.AcceptanceRate
	toSerialize["averageAcceptanceLatencyMs"] = o.AverageAcceptanceLatencyMs.Get()
	toSerialize["bounceRate"] = o.BounceRate
	toSerialize["complaintRate"] = o.ComplaintRate
	toSerialize["counts"] = o.Counts
	toSerialize["daily"] = o.Daily
	toSerialize["deliveryRate"] = o.DeliveryRate
	toSerialize["from"] = o.From
	toSerialize["mailboxes"] = o.Mailboxes
	toSerialize["replyRate"] = o.ReplyRate
	toSerialize["to"] = o.To
	toSerialize["total"] = o.Total
	toSerialize["variants"] = o.Variants

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailMessageAnalyticsOverview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"acceptanceRate",
		"averageAcceptanceLatencyMs",
		"bounceRate",
		"complaintRate",
		"counts",
		"daily",
		"deliveryRate",
		"from",
		"mailboxes",
		"replyRate",
		"to",
		"total",
		"variants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailMessageAnalyticsOverview := _MailMessageAnalyticsOverview{}

	err = json.Unmarshal(data, &varMailMessageAnalyticsOverview)

	if err != nil {
		return err
	}

	*o = MailMessageAnalyticsOverview(varMailMessageAnalyticsOverview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "acceptanceRate")
		delete(additionalProperties, "averageAcceptanceLatencyMs")
		delete(additionalProperties, "bounceRate")
		delete(additionalProperties, "complaintRate")
		delete(additionalProperties, "counts")
		delete(additionalProperties, "daily")
		delete(additionalProperties, "deliveryRate")
		delete(additionalProperties, "from")
		delete(additionalProperties, "mailboxes")
		delete(additionalProperties, "replyRate")
		delete(additionalProperties, "to")
		delete(additionalProperties, "total")
		delete(additionalProperties, "variants")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailMessageAnalyticsOverview struct {
	value *MailMessageAnalyticsOverview
	isSet bool
}

func (v NullableMailMessageAnalyticsOverview) Get() *MailMessageAnalyticsOverview {
	return v.value
}

func (v *NullableMailMessageAnalyticsOverview) Set(val *MailMessageAnalyticsOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableMailMessageAnalyticsOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableMailMessageAnalyticsOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailMessageAnalyticsOverview(val *MailMessageAnalyticsOverview) *NullableMailMessageAnalyticsOverview {
	return &NullableMailMessageAnalyticsOverview{value: val, isSet: true}
}

func (v NullableMailMessageAnalyticsOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailMessageAnalyticsOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


