/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateCodaCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateCodaCredentialRequest{}

// RotateCodaCredentialRequest struct for RotateCodaCredentialRequest
type RotateCodaCredentialRequest struct {
	ApiToken string `json:"apiToken"`
}

type _RotateCodaCredentialRequest RotateCodaCredentialRequest

// NewRotateCodaCredentialRequest instantiates a new RotateCodaCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateCodaCredentialRequest(apiToken string) *RotateCodaCredentialRequest {
	this := RotateCodaCredentialRequest{}
	this.ApiToken = apiToken
	return &this
}

// NewRotateCodaCredentialRequestWithDefaults instantiates a new RotateCodaCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateCodaCredentialRequestWithDefaults() *RotateCodaCredentialRequest {
	this := RotateCodaCredentialRequest{}
	return &this
}

// GetApiToken returns the ApiToken field value
func (o *RotateCodaCredentialRequest) GetApiToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiToken
}

// GetApiTokenOk returns a tuple with the ApiToken field value
// and a boolean to check if the value has been set.
func (o *RotateCodaCredentialRequest) GetApiTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiToken, true
}

// SetApiToken sets field value
func (o *RotateCodaCredentialRequest) SetApiToken(v string) {
	o.ApiToken = v
}

func (o RotateCodaCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateCodaCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiToken"] = o.ApiToken
	return toSerialize, nil
}

func (o *RotateCodaCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateCodaCredentialRequest := _RotateCodaCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateCodaCredentialRequest)

	if err != nil {
		return err
	}

	*o = RotateCodaCredentialRequest(varRotateCodaCredentialRequest)

	return err
}

type NullableRotateCodaCredentialRequest struct {
	value *RotateCodaCredentialRequest
	isSet bool
}

func (v NullableRotateCodaCredentialRequest) Get() *RotateCodaCredentialRequest {
	return v.value
}

func (v *NullableRotateCodaCredentialRequest) Set(val *RotateCodaCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateCodaCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateCodaCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateCodaCredentialRequest(val *RotateCodaCredentialRequest) *NullableRotateCodaCredentialRequest {
	return &NullableRotateCodaCredentialRequest{value: val, isSet: true}
}

func (v NullableRotateCodaCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateCodaCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


