/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MailPostAnalyticsExportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostAnalyticsExportRequest{}

// MailPostAnalyticsExportRequest struct for MailPostAnalyticsExportRequest
type MailPostAnalyticsExportRequest struct {
	After *MailPostAnalyticsExportRequestAfter `json:"after,omitempty"`
	From time.Time `json:"from"`
	Limit *int32 `json:"limit,omitempty"`
	To time.Time `json:"to"`
}

type _MailPostAnalyticsExportRequest MailPostAnalyticsExportRequest

// NewMailPostAnalyticsExportRequest instantiates a new MailPostAnalyticsExportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostAnalyticsExportRequest(from time.Time, to time.Time) *MailPostAnalyticsExportRequest {
	this := MailPostAnalyticsExportRequest{}
	this.From = from
	var limit int32 = 2000
	this.Limit = &limit
	this.To = to
	return &this
}

// NewMailPostAnalyticsExportRequestWithDefaults instantiates a new MailPostAnalyticsExportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostAnalyticsExportRequestWithDefaults() *MailPostAnalyticsExportRequest {
	this := MailPostAnalyticsExportRequest{}
	var limit int32 = 2000
	this.Limit = &limit
	return &this
}

// GetAfter returns the After field value if set, zero value otherwise.
func (o *MailPostAnalyticsExportRequest) GetAfter() MailPostAnalyticsExportRequestAfter {
	if o == nil || IsNil(o.After) {
		var ret MailPostAnalyticsExportRequestAfter
		return ret
	}
	return *o.After
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostAnalyticsExportRequest) GetAfterOk() (*MailPostAnalyticsExportRequestAfter, bool) {
	if o == nil || IsNil(o.After) {
		return nil, false
	}
	return o.After, true
}

// HasAfter returns a boolean if a field has been set.
func (o *MailPostAnalyticsExportRequest) HasAfter() bool {
	if o != nil && !IsNil(o.After) {
		return true
	}

	return false
}

// SetAfter gets a reference to the given MailPostAnalyticsExportRequestAfter and assigns it to the After field.
func (o *MailPostAnalyticsExportRequest) SetAfter(v MailPostAnalyticsExportRequestAfter) {
	o.After = &v
}

// GetFrom returns the From field value
func (o *MailPostAnalyticsExportRequest) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *MailPostAnalyticsExportRequest) GetFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *MailPostAnalyticsExportRequest) SetFrom(v time.Time) {
	o.From = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MailPostAnalyticsExportRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostAnalyticsExportRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MailPostAnalyticsExportRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *MailPostAnalyticsExportRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetTo returns the To field value
func (o *MailPostAnalyticsExportRequest) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *MailPostAnalyticsExportRequest) GetToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *MailPostAnalyticsExportRequest) SetTo(v time.Time) {
	o.To = v
}

func (o MailPostAnalyticsExportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostAnalyticsExportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.After) {
		toSerialize["after"] = o.After
	}
	toSerialize["from"] = o.From
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *MailPostAnalyticsExportRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostAnalyticsExportRequest := _MailPostAnalyticsExportRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostAnalyticsExportRequest)

	if err != nil {
		return err
	}

	*o = MailPostAnalyticsExportRequest(varMailPostAnalyticsExportRequest)

	return err
}

type NullableMailPostAnalyticsExportRequest struct {
	value *MailPostAnalyticsExportRequest
	isSet bool
}

func (v NullableMailPostAnalyticsExportRequest) Get() *MailPostAnalyticsExportRequest {
	return v.value
}

func (v *NullableMailPostAnalyticsExportRequest) Set(val *MailPostAnalyticsExportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostAnalyticsExportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostAnalyticsExportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostAnalyticsExportRequest(val *MailPostAnalyticsExportRequest) *NullableMailPostAnalyticsExportRequest {
	return &NullableMailPostAnalyticsExportRequest{value: val, isSet: true}
}

func (v NullableMailPostAnalyticsExportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostAnalyticsExportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


