/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the InsightRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsightRole{}

// InsightRole struct for InsightRole
type InsightRole struct {
	Department *string `json:"department,omitempty"`
	EndedAt *string `json:"endedAt,omitempty"`
	IsCurrent *bool `json:"isCurrent,omitempty"`
	Seniority *string `json:"seniority,omitempty"`
	StartedAt *string `json:"startedAt,omitempty"`
	Title *string `json:"title,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InsightRole InsightRole

// NewInsightRole instantiates a new InsightRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsightRole() *InsightRole {
	this := InsightRole{}
	return &this
}

// NewInsightRoleWithDefaults instantiates a new InsightRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsightRoleWithDefaults() *InsightRole {
	this := InsightRole{}
	return &this
}

// GetDepartment returns the Department field value if set, zero value otherwise.
func (o *InsightRole) GetDepartment() string {
	if o == nil || IsNil(o.Department) {
		var ret string
		return ret
	}
	return *o.Department
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetDepartmentOk() (*string, bool) {
	if o == nil || IsNil(o.Department) {
		return nil, false
	}
	return o.Department, true
}

// HasDepartment returns a boolean if a field has been set.
func (o *InsightRole) HasDepartment() bool {
	if o != nil && !IsNil(o.Department) {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given string and assigns it to the Department field.
func (o *InsightRole) SetDepartment(v string) {
	o.Department = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *InsightRole) GetEndedAt() string {
	if o == nil || IsNil(o.EndedAt) {
		var ret string
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetEndedAtOk() (*string, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *InsightRole) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given string and assigns it to the EndedAt field.
func (o *InsightRole) SetEndedAt(v string) {
	o.EndedAt = &v
}

// GetIsCurrent returns the IsCurrent field value if set, zero value otherwise.
func (o *InsightRole) GetIsCurrent() bool {
	if o == nil || IsNil(o.IsCurrent) {
		var ret bool
		return ret
	}
	return *o.IsCurrent
}

// GetIsCurrentOk returns a tuple with the IsCurrent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetIsCurrentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCurrent) {
		return nil, false
	}
	return o.IsCurrent, true
}

// HasIsCurrent returns a boolean if a field has been set.
func (o *InsightRole) HasIsCurrent() bool {
	if o != nil && !IsNil(o.IsCurrent) {
		return true
	}

	return false
}

// SetIsCurrent gets a reference to the given bool and assigns it to the IsCurrent field.
func (o *InsightRole) SetIsCurrent(v bool) {
	o.IsCurrent = &v
}

// GetSeniority returns the Seniority field value if set, zero value otherwise.
func (o *InsightRole) GetSeniority() string {
	if o == nil || IsNil(o.Seniority) {
		var ret string
		return ret
	}
	return *o.Seniority
}

// GetSeniorityOk returns a tuple with the Seniority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetSeniorityOk() (*string, bool) {
	if o == nil || IsNil(o.Seniority) {
		return nil, false
	}
	return o.Seniority, true
}

// HasSeniority returns a boolean if a field has been set.
func (o *InsightRole) HasSeniority() bool {
	if o != nil && !IsNil(o.Seniority) {
		return true
	}

	return false
}

// SetSeniority gets a reference to the given string and assigns it to the Seniority field.
func (o *InsightRole) SetSeniority(v string) {
	o.Seniority = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *InsightRole) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt) {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetStartedAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *InsightRole) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *InsightRole) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *InsightRole) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightRole) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *InsightRole) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *InsightRole) SetTitle(v string) {
	o.Title = &v
}

func (o InsightRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsightRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Department) {
		toSerialize["department"] = o.Department
	}
	if !IsNil(o.EndedAt) {
		toSerialize["endedAt"] = o.EndedAt
	}
	if !IsNil(o.IsCurrent) {
		toSerialize["isCurrent"] = o.IsCurrent
	}
	if !IsNil(o.Seniority) {
		toSerialize["seniority"] = o.Seniority
	}
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InsightRole) UnmarshalJSON(data []byte) (err error) {
	varInsightRole := _InsightRole{}

	err = json.Unmarshal(data, &varInsightRole)

	if err != nil {
		return err
	}

	*o = InsightRole(varInsightRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "department")
		delete(additionalProperties, "endedAt")
		delete(additionalProperties, "isCurrent")
		delete(additionalProperties, "seniority")
		delete(additionalProperties, "startedAt")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInsightRole struct {
	value *InsightRole
	isSet bool
}

func (v NullableInsightRole) Get() *InsightRole {
	return v.value
}

func (v *NullableInsightRole) Set(val *InsightRole) {
	v.value = val
	v.isSet = true
}

func (v NullableInsightRole) IsSet() bool {
	return v.isSet
}

func (v *NullableInsightRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsightRole(val *InsightRole) *NullableInsightRole {
	return &NullableInsightRole{value: val, isSet: true}
}

func (v NullableInsightRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsightRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


