/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostCampaignsByCampaignIdLaunchResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCampaignsByCampaignIdLaunchResponse200{}

// MailPostCampaignsByCampaignIdLaunchResponse200 struct for MailPostCampaignsByCampaignIdLaunchResponse200
type MailPostCampaignsByCampaignIdLaunchResponse200 struct {
	Campaign MailPostCampaignsByCampaignIdLaunchResponse200Campaign `json:"campaign"`
	Draft MailCampaignDraftRecord `json:"draft"`
	Sequences []MailSequenceRunRecord `json:"sequences"`
	AdditionalProperties map[string]interface{}
}

type _MailPostCampaignsByCampaignIdLaunchResponse200 MailPostCampaignsByCampaignIdLaunchResponse200

// NewMailPostCampaignsByCampaignIdLaunchResponse200 instantiates a new MailPostCampaignsByCampaignIdLaunchResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCampaignsByCampaignIdLaunchResponse200(campaign MailPostCampaignsByCampaignIdLaunchResponse200Campaign, draft MailCampaignDraftRecord, sequences []MailSequenceRunRecord) *MailPostCampaignsByCampaignIdLaunchResponse200 {
	this := MailPostCampaignsByCampaignIdLaunchResponse200{}
	this.Campaign = campaign
	this.Draft = draft
	this.Sequences = sequences
	return &this
}

// NewMailPostCampaignsByCampaignIdLaunchResponse200WithDefaults instantiates a new MailPostCampaignsByCampaignIdLaunchResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCampaignsByCampaignIdLaunchResponse200WithDefaults() *MailPostCampaignsByCampaignIdLaunchResponse200 {
	this := MailPostCampaignsByCampaignIdLaunchResponse200{}
	return &this
}

// GetCampaign returns the Campaign field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetCampaign() MailPostCampaignsByCampaignIdLaunchResponse200Campaign {
	if o == nil {
		var ret MailPostCampaignsByCampaignIdLaunchResponse200Campaign
		return ret
	}

	return o.Campaign
}

// GetCampaignOk returns a tuple with the Campaign field value
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetCampaignOk() (*MailPostCampaignsByCampaignIdLaunchResponse200Campaign, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Campaign, true
}

// SetCampaign sets field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) SetCampaign(v MailPostCampaignsByCampaignIdLaunchResponse200Campaign) {
	o.Campaign = v
}

// GetDraft returns the Draft field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetDraft() MailCampaignDraftRecord {
	if o == nil {
		var ret MailCampaignDraftRecord
		return ret
	}

	return o.Draft
}

// GetDraftOk returns a tuple with the Draft field value
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetDraftOk() (*MailCampaignDraftRecord, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Draft, true
}

// SetDraft sets field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) SetDraft(v MailCampaignDraftRecord) {
	o.Draft = v
}

// GetSequences returns the Sequences field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetSequences() []MailSequenceRunRecord {
	if o == nil {
		var ret []MailSequenceRunRecord
		return ret
	}

	return o.Sequences
}

// GetSequencesOk returns a tuple with the Sequences field value
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) GetSequencesOk() ([]MailSequenceRunRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sequences, true
}

// SetSequences sets field value
func (o *MailPostCampaignsByCampaignIdLaunchResponse200) SetSequences(v []MailSequenceRunRecord) {
	o.Sequences = v
}

func (o MailPostCampaignsByCampaignIdLaunchResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCampaignsByCampaignIdLaunchResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaign"] = o.Campaign
	toSerialize["draft"] = o.Draft
	toSerialize["sequences"] = o.Sequences

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostCampaignsByCampaignIdLaunchResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaign",
		"draft",
		"sequences",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCampaignsByCampaignIdLaunchResponse200 := _MailPostCampaignsByCampaignIdLaunchResponse200{}

	err = json.Unmarshal(data, &varMailPostCampaignsByCampaignIdLaunchResponse200)

	if err != nil {
		return err
	}

	*o = MailPostCampaignsByCampaignIdLaunchResponse200(varMailPostCampaignsByCampaignIdLaunchResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "campaign")
		delete(additionalProperties, "draft")
		delete(additionalProperties, "sequences")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostCampaignsByCampaignIdLaunchResponse200 struct {
	value *MailPostCampaignsByCampaignIdLaunchResponse200
	isSet bool
}

func (v NullableMailPostCampaignsByCampaignIdLaunchResponse200) Get() *MailPostCampaignsByCampaignIdLaunchResponse200 {
	return v.value
}

func (v *NullableMailPostCampaignsByCampaignIdLaunchResponse200) Set(val *MailPostCampaignsByCampaignIdLaunchResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCampaignsByCampaignIdLaunchResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCampaignsByCampaignIdLaunchResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCampaignsByCampaignIdLaunchResponse200(val *MailPostCampaignsByCampaignIdLaunchResponse200) *NullableMailPostCampaignsByCampaignIdLaunchResponse200 {
	return &NullableMailPostCampaignsByCampaignIdLaunchResponse200{value: val, isSet: true}
}

func (v NullableMailPostCampaignsByCampaignIdLaunchResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCampaignsByCampaignIdLaunchResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


