/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the MailPostInboxByMessageIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostInboxByMessageIdRequest{}

// MailPostInboxByMessageIdRequest Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
type MailPostInboxByMessageIdRequest struct {
	AssignedToActorId NullableString `json:"assignedToActorId,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewMailPostInboxByMessageIdRequest instantiates a new MailPostInboxByMessageIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostInboxByMessageIdRequest() *MailPostInboxByMessageIdRequest {
	this := MailPostInboxByMessageIdRequest{}
	return &this
}

// NewMailPostInboxByMessageIdRequestWithDefaults instantiates a new MailPostInboxByMessageIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostInboxByMessageIdRequestWithDefaults() *MailPostInboxByMessageIdRequest {
	this := MailPostInboxByMessageIdRequest{}
	return &this
}

// GetAssignedToActorId returns the AssignedToActorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MailPostInboxByMessageIdRequest) GetAssignedToActorId() string {
	if o == nil || IsNil(o.AssignedToActorId.Get()) {
		var ret string
		return ret
	}
	return *o.AssignedToActorId.Get()
}

// GetAssignedToActorIdOk returns a tuple with the AssignedToActorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailPostInboxByMessageIdRequest) GetAssignedToActorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssignedToActorId.Get(), o.AssignedToActorId.IsSet()
}

// HasAssignedToActorId returns a boolean if a field has been set.
func (o *MailPostInboxByMessageIdRequest) HasAssignedToActorId() bool {
	if o != nil && o.AssignedToActorId.IsSet() {
		return true
	}

	return false
}

// SetAssignedToActorId gets a reference to the given NullableString and assigns it to the AssignedToActorId field.
func (o *MailPostInboxByMessageIdRequest) SetAssignedToActorId(v string) {
	o.AssignedToActorId.Set(&v)
}
// SetAssignedToActorIdNil sets the value for AssignedToActorId to be an explicit nil
func (o *MailPostInboxByMessageIdRequest) SetAssignedToActorIdNil() {
	o.AssignedToActorId.Set(nil)
}

// UnsetAssignedToActorId ensures that no value is present for AssignedToActorId, not even an explicit nil
func (o *MailPostInboxByMessageIdRequest) UnsetAssignedToActorId() {
	o.AssignedToActorId.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MailPostInboxByMessageIdRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostInboxByMessageIdRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MailPostInboxByMessageIdRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MailPostInboxByMessageIdRequest) SetStatus(v string) {
	o.Status = &v
}

func (o MailPostInboxByMessageIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostInboxByMessageIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AssignedToActorId.IsSet() {
		toSerialize["assignedToActorId"] = o.AssignedToActorId.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableMailPostInboxByMessageIdRequest struct {
	value *MailPostInboxByMessageIdRequest
	isSet bool
}

func (v NullableMailPostInboxByMessageIdRequest) Get() *MailPostInboxByMessageIdRequest {
	return v.value
}

func (v *NullableMailPostInboxByMessageIdRequest) Set(val *MailPostInboxByMessageIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostInboxByMessageIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostInboxByMessageIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostInboxByMessageIdRequest(val *MailPostInboxByMessageIdRequest) *NullableMailPostInboxByMessageIdRequest {
	return &NullableMailPostInboxByMessageIdRequest{value: val, isSet: true}
}

func (v NullableMailPostInboxByMessageIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostInboxByMessageIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


