/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostCadencesByCadenceIdCopyResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCadencesByCadenceIdCopyResponse200{}

// MailPostCadencesByCadenceIdCopyResponse200 struct for MailPostCadencesByCadenceIdCopyResponse200
type MailPostCadencesByCadenceIdCopyResponse200 struct {
	Cadence MailCadenceDefinition `json:"cadence"`
	RequiresReview bool `json:"requiresReview"`
	Templates []MailMessageTemplateVersion `json:"templates"`
	AdditionalProperties map[string]interface{}
}

type _MailPostCadencesByCadenceIdCopyResponse200 MailPostCadencesByCadenceIdCopyResponse200

// NewMailPostCadencesByCadenceIdCopyResponse200 instantiates a new MailPostCadencesByCadenceIdCopyResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCadencesByCadenceIdCopyResponse200(cadence MailCadenceDefinition, requiresReview bool, templates []MailMessageTemplateVersion) *MailPostCadencesByCadenceIdCopyResponse200 {
	this := MailPostCadencesByCadenceIdCopyResponse200{}
	this.Cadence = cadence
	this.RequiresReview = requiresReview
	this.Templates = templates
	return &this
}

// NewMailPostCadencesByCadenceIdCopyResponse200WithDefaults instantiates a new MailPostCadencesByCadenceIdCopyResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCadencesByCadenceIdCopyResponse200WithDefaults() *MailPostCadencesByCadenceIdCopyResponse200 {
	this := MailPostCadencesByCadenceIdCopyResponse200{}
	return &this
}

// GetCadence returns the Cadence field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetCadence() MailCadenceDefinition {
	if o == nil {
		var ret MailCadenceDefinition
		return ret
	}

	return o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetCadenceOk() (*MailCadenceDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cadence, true
}

// SetCadence sets field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) SetCadence(v MailCadenceDefinition) {
	o.Cadence = v
}

// GetRequiresReview returns the RequiresReview field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetRequiresReview() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresReview
}

// GetRequiresReviewOk returns a tuple with the RequiresReview field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetRequiresReviewOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresReview, true
}

// SetRequiresReview sets field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) SetRequiresReview(v bool) {
	o.RequiresReview = v
}

// GetTemplates returns the Templates field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetTemplates() []MailMessageTemplateVersion {
	if o == nil {
		var ret []MailMessageTemplateVersion
		return ret
	}

	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesByCadenceIdCopyResponse200) GetTemplatesOk() ([]MailMessageTemplateVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Templates, true
}

// SetTemplates sets field value
func (o *MailPostCadencesByCadenceIdCopyResponse200) SetTemplates(v []MailMessageTemplateVersion) {
	o.Templates = v
}

func (o MailPostCadencesByCadenceIdCopyResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCadencesByCadenceIdCopyResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cadence"] = o.Cadence
	toSerialize["requiresReview"] = o.RequiresReview
	toSerialize["templates"] = o.Templates

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostCadencesByCadenceIdCopyResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cadence",
		"requiresReview",
		"templates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCadencesByCadenceIdCopyResponse200 := _MailPostCadencesByCadenceIdCopyResponse200{}

	err = json.Unmarshal(data, &varMailPostCadencesByCadenceIdCopyResponse200)

	if err != nil {
		return err
	}

	*o = MailPostCadencesByCadenceIdCopyResponse200(varMailPostCadencesByCadenceIdCopyResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cadence")
		delete(additionalProperties, "requiresReview")
		delete(additionalProperties, "templates")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostCadencesByCadenceIdCopyResponse200 struct {
	value *MailPostCadencesByCadenceIdCopyResponse200
	isSet bool
}

func (v NullableMailPostCadencesByCadenceIdCopyResponse200) Get() *MailPostCadencesByCadenceIdCopyResponse200 {
	return v.value
}

func (v *NullableMailPostCadencesByCadenceIdCopyResponse200) Set(val *MailPostCadencesByCadenceIdCopyResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCadencesByCadenceIdCopyResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCadencesByCadenceIdCopyResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCadencesByCadenceIdCopyResponse200(val *MailPostCadencesByCadenceIdCopyResponse200) *NullableMailPostCadencesByCadenceIdCopyResponse200 {
	return &NullableMailPostCadencesByCadenceIdCopyResponse200{value: val, isSet: true}
}

func (v NullableMailPostCadencesByCadenceIdCopyResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCadencesByCadenceIdCopyResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


