/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)


// MailPostAnalyticsExportResponse200NextCursor struct for MailPostAnalyticsExportResponse200NextCursor
type MailPostAnalyticsExportResponse200NextCursor struct {
	MailPostAnalyticsExportResponse200NextCursorAnyOf *MailPostAnalyticsExportResponse200NextCursorAnyOf
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *MailPostAnalyticsExportResponse200NextCursor) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MailPostAnalyticsExportResponse200NextCursorAnyOf
	err = json.Unmarshal(data, &dst.MailPostAnalyticsExportResponse200NextCursorAnyOf);
	if err == nil {
		jsonMailPostAnalyticsExportResponse200NextCursorAnyOf, _ := json.Marshal(dst.MailPostAnalyticsExportResponse200NextCursorAnyOf)
		if string(jsonMailPostAnalyticsExportResponse200NextCursorAnyOf) == "{}" { // empty struct
			dst.MailPostAnalyticsExportResponse200NextCursorAnyOf = nil
		} else {
			return nil // data stored in dst.MailPostAnalyticsExportResponse200NextCursorAnyOf, return on the first match
		}
	} else {
		dst.MailPostAnalyticsExportResponse200NextCursorAnyOf = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(MailPostAnalyticsExportResponse200NextCursor)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MailPostAnalyticsExportResponse200NextCursor) MarshalJSON() ([]byte, error) {
	if src.MailPostAnalyticsExportResponse200NextCursorAnyOf != nil {
		return json.Marshal(&src.MailPostAnalyticsExportResponse200NextCursorAnyOf)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableMailPostAnalyticsExportResponse200NextCursor struct {
	value *MailPostAnalyticsExportResponse200NextCursor
	isSet bool
}

func (v NullableMailPostAnalyticsExportResponse200NextCursor) Get() *MailPostAnalyticsExportResponse200NextCursor {
	return v.value
}

func (v *NullableMailPostAnalyticsExportResponse200NextCursor) Set(val *MailPostAnalyticsExportResponse200NextCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostAnalyticsExportResponse200NextCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostAnalyticsExportResponse200NextCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostAnalyticsExportResponse200NextCursor(val *MailPostAnalyticsExportResponse200NextCursor) *NullableMailPostAnalyticsExportResponse200NextCursor {
	return &NullableMailPostAnalyticsExportResponse200NextCursor{value: val, isSet: true}
}

func (v NullableMailPostAnalyticsExportResponse200NextCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostAnalyticsExportResponse200NextCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


