/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner{}

// MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner struct for MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner
type MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner struct {
	Html *string `json:"html,omitempty"`
	Id string `json:"id"`
	Subject string `json:"subject"`
	Text string `json:"text"`
	Weight float32 `json:"weight"`
}

type _MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner

// NewMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner instantiates a new MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner(id string, subject string, text string, weight float32) *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
	this := MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner{}
	this.Id = id
	this.Subject = subject
	this.Text = text
	this.Weight = weight
	return &this
}

// NewMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerWithDefaults instantiates a new MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerWithDefaults() *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
	this := MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner{}
	return &this
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) SetHtml(v string) {
	o.Html = &v
}

// GetId returns the Id field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) SetId(v string) {
	o.Id = v
}

// GetSubject returns the Subject field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) SetSubject(v string) {
	o.Subject = v
}

// GetText returns the Text field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) SetText(v string) {
	o.Text = v
}

// GetWeight returns the Weight field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetWeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) GetWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) SetWeight(v float32) {
	o.Weight = v
}

func (o MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	toSerialize["id"] = o.Id
	toSerialize["subject"] = o.Subject
	toSerialize["text"] = o.Text
	toSerialize["weight"] = o.Weight
	return toSerialize, nil
}

func (o *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"subject",
		"text",
		"weight",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner := _MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner)

	if err != nil {
		return err
	}

	*o = MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner(varMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner)

	return err
}

type NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner struct {
	value *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner
	isSet bool
}

func (v NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) Get() *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
	return v.value
}

func (v *NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) Set(val *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner(val *MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) *NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
	return &NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner{value: val, isSet: true}
}

func (v NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


