/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPostCampaignsByCampaignIdStateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCampaignsByCampaignIdStateRequest{}

// MailPostCampaignsByCampaignIdStateRequest struct for MailPostCampaignsByCampaignIdStateRequest
type MailPostCampaignsByCampaignIdStateRequest struct {
	Action string `json:"action"`
}

type _MailPostCampaignsByCampaignIdStateRequest MailPostCampaignsByCampaignIdStateRequest

// NewMailPostCampaignsByCampaignIdStateRequest instantiates a new MailPostCampaignsByCampaignIdStateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCampaignsByCampaignIdStateRequest(action string) *MailPostCampaignsByCampaignIdStateRequest {
	this := MailPostCampaignsByCampaignIdStateRequest{}
	this.Action = action
	return &this
}

// NewMailPostCampaignsByCampaignIdStateRequestWithDefaults instantiates a new MailPostCampaignsByCampaignIdStateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCampaignsByCampaignIdStateRequestWithDefaults() *MailPostCampaignsByCampaignIdStateRequest {
	this := MailPostCampaignsByCampaignIdStateRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *MailPostCampaignsByCampaignIdStateRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MailPostCampaignsByCampaignIdStateRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MailPostCampaignsByCampaignIdStateRequest) SetAction(v string) {
	o.Action = v
}

func (o MailPostCampaignsByCampaignIdStateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCampaignsByCampaignIdStateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *MailPostCampaignsByCampaignIdStateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCampaignsByCampaignIdStateRequest := _MailPostCampaignsByCampaignIdStateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostCampaignsByCampaignIdStateRequest)

	if err != nil {
		return err
	}

	*o = MailPostCampaignsByCampaignIdStateRequest(varMailPostCampaignsByCampaignIdStateRequest)

	return err
}

type NullableMailPostCampaignsByCampaignIdStateRequest struct {
	value *MailPostCampaignsByCampaignIdStateRequest
	isSet bool
}

func (v NullableMailPostCampaignsByCampaignIdStateRequest) Get() *MailPostCampaignsByCampaignIdStateRequest {
	return v.value
}

func (v *NullableMailPostCampaignsByCampaignIdStateRequest) Set(val *MailPostCampaignsByCampaignIdStateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCampaignsByCampaignIdStateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCampaignsByCampaignIdStateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCampaignsByCampaignIdStateRequest(val *MailPostCampaignsByCampaignIdStateRequest) *NullableMailPostCampaignsByCampaignIdStateRequest {
	return &NullableMailPostCampaignsByCampaignIdStateRequest{value: val, isSet: true}
}

func (v NullableMailPostCampaignsByCampaignIdStateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCampaignsByCampaignIdStateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


