/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailOperationalAnalyticsOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailOperationalAnalyticsOverview{}

// MailOperationalAnalyticsOverview struct for MailOperationalAnalyticsOverview
type MailOperationalAnalyticsOverview struct {
	CadenceSteps []MailOperationalAnalyticsOverviewCadenceStepsInner `json:"cadenceSteps"`
	ReplyLabels map[string]float32 `json:"replyLabels"`
	SampleLimited bool `json:"sampleLimited"`
	Stages map[string]float32 `json:"stages"`
	TaskOutcomes map[string]float32 `json:"taskOutcomes"`
	AdditionalProperties map[string]interface{}
}

type _MailOperationalAnalyticsOverview MailOperationalAnalyticsOverview

// NewMailOperationalAnalyticsOverview instantiates a new MailOperationalAnalyticsOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailOperationalAnalyticsOverview(cadenceSteps []MailOperationalAnalyticsOverviewCadenceStepsInner, replyLabels map[string]float32, sampleLimited bool, stages map[string]float32, taskOutcomes map[string]float32) *MailOperationalAnalyticsOverview {
	this := MailOperationalAnalyticsOverview{}
	this.CadenceSteps = cadenceSteps
	this.ReplyLabels = replyLabels
	this.SampleLimited = sampleLimited
	this.Stages = stages
	this.TaskOutcomes = taskOutcomes
	return &this
}

// NewMailOperationalAnalyticsOverviewWithDefaults instantiates a new MailOperationalAnalyticsOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailOperationalAnalyticsOverviewWithDefaults() *MailOperationalAnalyticsOverview {
	this := MailOperationalAnalyticsOverview{}
	return &this
}

// GetCadenceSteps returns the CadenceSteps field value
func (o *MailOperationalAnalyticsOverview) GetCadenceSteps() []MailOperationalAnalyticsOverviewCadenceStepsInner {
	if o == nil {
		var ret []MailOperationalAnalyticsOverviewCadenceStepsInner
		return ret
	}

	return o.CadenceSteps
}

// GetCadenceStepsOk returns a tuple with the CadenceSteps field value
// and a boolean to check if the value has been set.
func (o *MailOperationalAnalyticsOverview) GetCadenceStepsOk() ([]MailOperationalAnalyticsOverviewCadenceStepsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.CadenceSteps, true
}

// SetCadenceSteps sets field value
func (o *MailOperationalAnalyticsOverview) SetCadenceSteps(v []MailOperationalAnalyticsOverviewCadenceStepsInner) {
	o.CadenceSteps = v
}

// GetReplyLabels returns the ReplyLabels field value
func (o *MailOperationalAnalyticsOverview) GetReplyLabels() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.ReplyLabels
}

// GetReplyLabelsOk returns a tuple with the ReplyLabels field value
// and a boolean to check if the value has been set.
func (o *MailOperationalAnalyticsOverview) GetReplyLabelsOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReplyLabels, true
}

// SetReplyLabels sets field value
func (o *MailOperationalAnalyticsOverview) SetReplyLabels(v map[string]float32) {
	o.ReplyLabels = v
}

// GetSampleLimited returns the SampleLimited field value
func (o *MailOperationalAnalyticsOverview) GetSampleLimited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SampleLimited
}

// GetSampleLimitedOk returns a tuple with the SampleLimited field value
// and a boolean to check if the value has been set.
func (o *MailOperationalAnalyticsOverview) GetSampleLimitedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SampleLimited, true
}

// SetSampleLimited sets field value
func (o *MailOperationalAnalyticsOverview) SetSampleLimited(v bool) {
	o.SampleLimited = v
}

// GetStages returns the Stages field value
func (o *MailOperationalAnalyticsOverview) GetStages() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value
// and a boolean to check if the value has been set.
func (o *MailOperationalAnalyticsOverview) GetStagesOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stages, true
}

// SetStages sets field value
func (o *MailOperationalAnalyticsOverview) SetStages(v map[string]float32) {
	o.Stages = v
}

// GetTaskOutcomes returns the TaskOutcomes field value
func (o *MailOperationalAnalyticsOverview) GetTaskOutcomes() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.TaskOutcomes
}

// GetTaskOutcomesOk returns a tuple with the TaskOutcomes field value
// and a boolean to check if the value has been set.
func (o *MailOperationalAnalyticsOverview) GetTaskOutcomesOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskOutcomes, true
}

// SetTaskOutcomes sets field value
func (o *MailOperationalAnalyticsOverview) SetTaskOutcomes(v map[string]float32) {
	o.TaskOutcomes = v
}

func (o MailOperationalAnalyticsOverview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailOperationalAnalyticsOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cadenceSteps"] = o.CadenceSteps
	toSerialize["replyLabels"] = o.ReplyLabels
	toSerialize["sampleLimited"] = o.SampleLimited
	toSerialize["stages"] = o.Stages
	toSerialize["taskOutcomes"] = o.TaskOutcomes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailOperationalAnalyticsOverview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cadenceSteps",
		"replyLabels",
		"sampleLimited",
		"stages",
		"taskOutcomes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailOperationalAnalyticsOverview := _MailOperationalAnalyticsOverview{}

	err = json.Unmarshal(data, &varMailOperationalAnalyticsOverview)

	if err != nil {
		return err
	}

	*o = MailOperationalAnalyticsOverview(varMailOperationalAnalyticsOverview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cadenceSteps")
		delete(additionalProperties, "replyLabels")
		delete(additionalProperties, "sampleLimited")
		delete(additionalProperties, "stages")
		delete(additionalProperties, "taskOutcomes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailOperationalAnalyticsOverview struct {
	value *MailOperationalAnalyticsOverview
	isSet bool
}

func (v NullableMailOperationalAnalyticsOverview) Get() *MailOperationalAnalyticsOverview {
	return v.value
}

func (v *NullableMailOperationalAnalyticsOverview) Set(val *MailOperationalAnalyticsOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableMailOperationalAnalyticsOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableMailOperationalAnalyticsOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailOperationalAnalyticsOverview(val *MailOperationalAnalyticsOverview) *NullableMailOperationalAnalyticsOverview {
	return &NullableMailOperationalAnalyticsOverview{value: val, isSet: true}
}

func (v NullableMailOperationalAnalyticsOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailOperationalAnalyticsOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


