/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPostWebhooksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostWebhooksRequest{}

// MailPostWebhooksRequest struct for MailPostWebhooksRequest
type MailPostWebhooksRequest struct {
	Endpoint string `json:"endpoint"`
	EventTypes []string `json:"eventTypes,omitempty"`
}

type _MailPostWebhooksRequest MailPostWebhooksRequest

// NewMailPostWebhooksRequest instantiates a new MailPostWebhooksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostWebhooksRequest(endpoint string) *MailPostWebhooksRequest {
	this := MailPostWebhooksRequest{}
	this.Endpoint = endpoint
	return &this
}

// NewMailPostWebhooksRequestWithDefaults instantiates a new MailPostWebhooksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostWebhooksRequestWithDefaults() *MailPostWebhooksRequest {
	this := MailPostWebhooksRequest{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *MailPostWebhooksRequest) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *MailPostWebhooksRequest) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *MailPostWebhooksRequest) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetEventTypes returns the EventTypes field value if set, zero value otherwise.
func (o *MailPostWebhooksRequest) GetEventTypes() []string {
	if o == nil || IsNil(o.EventTypes) {
		var ret []string
		return ret
	}
	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPostWebhooksRequest) GetEventTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.EventTypes) {
		return nil, false
	}
	return o.EventTypes, true
}

// HasEventTypes returns a boolean if a field has been set.
func (o *MailPostWebhooksRequest) HasEventTypes() bool {
	if o != nil && !IsNil(o.EventTypes) {
		return true
	}

	return false
}

// SetEventTypes gets a reference to the given []string and assigns it to the EventTypes field.
func (o *MailPostWebhooksRequest) SetEventTypes(v []string) {
	o.EventTypes = v
}

func (o MailPostWebhooksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostWebhooksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	if !IsNil(o.EventTypes) {
		toSerialize["eventTypes"] = o.EventTypes
	}
	return toSerialize, nil
}

func (o *MailPostWebhooksRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostWebhooksRequest := _MailPostWebhooksRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostWebhooksRequest)

	if err != nil {
		return err
	}

	*o = MailPostWebhooksRequest(varMailPostWebhooksRequest)

	return err
}

type NullableMailPostWebhooksRequest struct {
	value *MailPostWebhooksRequest
	isSet bool
}

func (v NullableMailPostWebhooksRequest) Get() *MailPostWebhooksRequest {
	return v.value
}

func (v *NullableMailPostWebhooksRequest) Set(val *MailPostWebhooksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostWebhooksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostWebhooksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostWebhooksRequest(val *MailPostWebhooksRequest) *NullableMailPostWebhooksRequest {
	return &NullableMailPostWebhooksRequest{value: val, isSet: true}
}

func (v NullableMailPostWebhooksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostWebhooksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


