/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InspectGoogleSheetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InspectGoogleSheetRequest{}

// InspectGoogleSheetRequest struct for InspectGoogleSheetRequest
type InspectGoogleSheetRequest struct {
	ConnectionId string `json:"connectionId"`
	HeaderRow *int32 `json:"headerRow,omitempty"`
	SheetName NullableString `json:"sheetName,omitempty"`
	SpreadsheetId string `json:"spreadsheetId"`
}

type _InspectGoogleSheetRequest InspectGoogleSheetRequest

// NewInspectGoogleSheetRequest instantiates a new InspectGoogleSheetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInspectGoogleSheetRequest(connectionId string, spreadsheetId string) *InspectGoogleSheetRequest {
	this := InspectGoogleSheetRequest{}
	this.ConnectionId = connectionId
	this.SpreadsheetId = spreadsheetId
	return &this
}

// NewInspectGoogleSheetRequestWithDefaults instantiates a new InspectGoogleSheetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInspectGoogleSheetRequestWithDefaults() *InspectGoogleSheetRequest {
	this := InspectGoogleSheetRequest{}
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *InspectGoogleSheetRequest) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *InspectGoogleSheetRequest) GetConnectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *InspectGoogleSheetRequest) SetConnectionId(v string) {
	o.ConnectionId = v
}

// GetHeaderRow returns the HeaderRow field value if set, zero value otherwise.
func (o *InspectGoogleSheetRequest) GetHeaderRow() int32 {
	if o == nil || IsNil(o.HeaderRow) {
		var ret int32
		return ret
	}
	return *o.HeaderRow
}

// GetHeaderRowOk returns a tuple with the HeaderRow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InspectGoogleSheetRequest) GetHeaderRowOk() (*int32, bool) {
	if o == nil || IsNil(o.HeaderRow) {
		return nil, false
	}
	return o.HeaderRow, true
}

// HasHeaderRow returns a boolean if a field has been set.
func (o *InspectGoogleSheetRequest) HasHeaderRow() bool {
	if o != nil && !IsNil(o.HeaderRow) {
		return true
	}

	return false
}

// SetHeaderRow gets a reference to the given int32 and assigns it to the HeaderRow field.
func (o *InspectGoogleSheetRequest) SetHeaderRow(v int32) {
	o.HeaderRow = &v
}

// GetSheetName returns the SheetName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InspectGoogleSheetRequest) GetSheetName() string {
	if o == nil || IsNil(o.SheetName.Get()) {
		var ret string
		return ret
	}
	return *o.SheetName.Get()
}

// GetSheetNameOk returns a tuple with the SheetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InspectGoogleSheetRequest) GetSheetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SheetName.Get(), o.SheetName.IsSet()
}

// HasSheetName returns a boolean if a field has been set.
func (o *InspectGoogleSheetRequest) HasSheetName() bool {
	if o != nil && o.SheetName.IsSet() {
		return true
	}

	return false
}

// SetSheetName gets a reference to the given NullableString and assigns it to the SheetName field.
func (o *InspectGoogleSheetRequest) SetSheetName(v string) {
	o.SheetName.Set(&v)
}
// SetSheetNameNil sets the value for SheetName to be an explicit nil
func (o *InspectGoogleSheetRequest) SetSheetNameNil() {
	o.SheetName.Set(nil)
}

// UnsetSheetName ensures that no value is present for SheetName, not even an explicit nil
func (o *InspectGoogleSheetRequest) UnsetSheetName() {
	o.SheetName.Unset()
}

// GetSpreadsheetId returns the SpreadsheetId field value
func (o *InspectGoogleSheetRequest) GetSpreadsheetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpreadsheetId
}

// GetSpreadsheetIdOk returns a tuple with the SpreadsheetId field value
// and a boolean to check if the value has been set.
func (o *InspectGoogleSheetRequest) GetSpreadsheetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpreadsheetId, true
}

// SetSpreadsheetId sets field value
func (o *InspectGoogleSheetRequest) SetSpreadsheetId(v string) {
	o.SpreadsheetId = v
}

func (o InspectGoogleSheetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InspectGoogleSheetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectionId"] = o.ConnectionId
	if !IsNil(o.HeaderRow) {
		toSerialize["headerRow"] = o.HeaderRow
	}
	if o.SheetName.IsSet() {
		toSerialize["sheetName"] = o.SheetName.Get()
	}
	toSerialize["spreadsheetId"] = o.SpreadsheetId
	return toSerialize, nil
}

func (o *InspectGoogleSheetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionId",
		"spreadsheetId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInspectGoogleSheetRequest := _InspectGoogleSheetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInspectGoogleSheetRequest)

	if err != nil {
		return err
	}

	*o = InspectGoogleSheetRequest(varInspectGoogleSheetRequest)

	return err
}

type NullableInspectGoogleSheetRequest struct {
	value *InspectGoogleSheetRequest
	isSet bool
}

func (v NullableInspectGoogleSheetRequest) Get() *InspectGoogleSheetRequest {
	return v.value
}

func (v *NullableInspectGoogleSheetRequest) Set(val *InspectGoogleSheetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInspectGoogleSheetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInspectGoogleSheetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInspectGoogleSheetRequest(val *InspectGoogleSheetRequest) *NullableInspectGoogleSheetRequest {
	return &NullableInspectGoogleSheetRequest{value: val, isSet: true}
}

func (v NullableInspectGoogleSheetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInspectGoogleSheetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


