/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductSequenceRecipientCancelExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSequenceRecipientCancelExecution{}

// ProductSequenceRecipientCancelExecution struct for ProductSequenceRecipientCancelExecution
type ProductSequenceRecipientCancelExecution struct {
	ExecutionId string `json:"executionId"`
	Output ProductRecipient `json:"output"`
	Replay bool `json:"replay"`
	Tool string `json:"tool"`
	AdditionalProperties map[string]interface{}
}

type _ProductSequenceRecipientCancelExecution ProductSequenceRecipientCancelExecution

// NewProductSequenceRecipientCancelExecution instantiates a new ProductSequenceRecipientCancelExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSequenceRecipientCancelExecution(executionId string, output ProductRecipient, replay bool, tool string) *ProductSequenceRecipientCancelExecution {
	this := ProductSequenceRecipientCancelExecution{}
	this.ExecutionId = executionId
	this.Output = output
	this.Replay = replay
	this.Tool = tool
	return &this
}

// NewProductSequenceRecipientCancelExecutionWithDefaults instantiates a new ProductSequenceRecipientCancelExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSequenceRecipientCancelExecutionWithDefaults() *ProductSequenceRecipientCancelExecution {
	this := ProductSequenceRecipientCancelExecution{}
	return &this
}

// GetExecutionId returns the ExecutionId field value
func (o *ProductSequenceRecipientCancelExecution) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientCancelExecution) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *ProductSequenceRecipientCancelExecution) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetOutput returns the Output field value
func (o *ProductSequenceRecipientCancelExecution) GetOutput() ProductRecipient {
	if o == nil {
		var ret ProductRecipient
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientCancelExecution) GetOutputOk() (*ProductRecipient, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *ProductSequenceRecipientCancelExecution) SetOutput(v ProductRecipient) {
	o.Output = v
}

// GetReplay returns the Replay field value
func (o *ProductSequenceRecipientCancelExecution) GetReplay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Replay
}

// GetReplayOk returns a tuple with the Replay field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientCancelExecution) GetReplayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replay, true
}

// SetReplay sets field value
func (o *ProductSequenceRecipientCancelExecution) SetReplay(v bool) {
	o.Replay = v
}

// GetTool returns the Tool field value
func (o *ProductSequenceRecipientCancelExecution) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *ProductSequenceRecipientCancelExecution) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *ProductSequenceRecipientCancelExecution) SetTool(v string) {
	o.Tool = v
}

func (o ProductSequenceRecipientCancelExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSequenceRecipientCancelExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["executionId"] = o.ExecutionId
	toSerialize["output"] = o.Output
	toSerialize["replay"] = o.Replay
	toSerialize["tool"] = o.Tool

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductSequenceRecipientCancelExecution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"executionId",
		"output",
		"replay",
		"tool",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductSequenceRecipientCancelExecution := _ProductSequenceRecipientCancelExecution{}

	err = json.Unmarshal(data, &varProductSequenceRecipientCancelExecution)

	if err != nil {
		return err
	}

	*o = ProductSequenceRecipientCancelExecution(varProductSequenceRecipientCancelExecution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "executionId")
		delete(additionalProperties, "output")
		delete(additionalProperties, "replay")
		delete(additionalProperties, "tool")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductSequenceRecipientCancelExecution struct {
	value *ProductSequenceRecipientCancelExecution
	isSet bool
}

func (v NullableProductSequenceRecipientCancelExecution) Get() *ProductSequenceRecipientCancelExecution {
	return v.value
}

func (v *NullableProductSequenceRecipientCancelExecution) Set(val *ProductSequenceRecipientCancelExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSequenceRecipientCancelExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSequenceRecipientCancelExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSequenceRecipientCancelExecution(val *ProductSequenceRecipientCancelExecution) *NullableProductSequenceRecipientCancelExecution {
	return &NullableProductSequenceRecipientCancelExecution{value: val, isSet: true}
}

func (v NullableProductSequenceRecipientCancelExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSequenceRecipientCancelExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


