/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductDomainFinderInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDomainFinderInput{}

// ProductDomainFinderInput struct for ProductDomainFinderInput
type ProductDomainFinderInput struct {
	// The server applies trim before validating {\"type\":\"string\",\"minLength\":1,\"maxLength\":500}.
	Company string `json:"company"`
}

type _ProductDomainFinderInput ProductDomainFinderInput

// NewProductDomainFinderInput instantiates a new ProductDomainFinderInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDomainFinderInput(company string) *ProductDomainFinderInput {
	this := ProductDomainFinderInput{}
	this.Company = company
	return &this
}

// NewProductDomainFinderInputWithDefaults instantiates a new ProductDomainFinderInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDomainFinderInputWithDefaults() *ProductDomainFinderInput {
	this := ProductDomainFinderInput{}
	return &this
}

// GetCompany returns the Company field value
func (o *ProductDomainFinderInput) GetCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *ProductDomainFinderInput) GetCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *ProductDomainFinderInput) SetCompany(v string) {
	o.Company = v
}

func (o ProductDomainFinderInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDomainFinderInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["company"] = o.Company
	return toSerialize, nil
}

func (o *ProductDomainFinderInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductDomainFinderInput := _ProductDomainFinderInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductDomainFinderInput)

	if err != nil {
		return err
	}

	*o = ProductDomainFinderInput(varProductDomainFinderInput)

	return err
}

type NullableProductDomainFinderInput struct {
	value *ProductDomainFinderInput
	isSet bool
}

func (v NullableProductDomainFinderInput) Get() *ProductDomainFinderInput {
	return v.value
}

func (v *NullableProductDomainFinderInput) Set(val *ProductDomainFinderInput) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDomainFinderInput) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDomainFinderInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDomainFinderInput(val *ProductDomainFinderInput) *NullableProductDomainFinderInput {
	return &NullableProductDomainFinderInput{value: val, isSet: true}
}

func (v NullableProductDomainFinderInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDomainFinderInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


