/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigureAirtableMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureAirtableMappingRequest{}

// ConfigureAirtableMappingRequest struct for ConfigureAirtableMappingRequest
type ConfigureAirtableMappingRequest struct {
	Mapping map[string]interface{} `json:"mapping"`
}

type _ConfigureAirtableMappingRequest ConfigureAirtableMappingRequest

// NewConfigureAirtableMappingRequest instantiates a new ConfigureAirtableMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureAirtableMappingRequest(mapping map[string]interface{}) *ConfigureAirtableMappingRequest {
	this := ConfigureAirtableMappingRequest{}
	this.Mapping = mapping
	return &this
}

// NewConfigureAirtableMappingRequestWithDefaults instantiates a new ConfigureAirtableMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureAirtableMappingRequestWithDefaults() *ConfigureAirtableMappingRequest {
	this := ConfigureAirtableMappingRequest{}
	return &this
}

// GetMapping returns the Mapping field value
func (o *ConfigureAirtableMappingRequest) GetMapping() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Mapping
}

// GetMappingOk returns a tuple with the Mapping field value
// and a boolean to check if the value has been set.
func (o *ConfigureAirtableMappingRequest) GetMappingOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Mapping, true
}

// SetMapping sets field value
func (o *ConfigureAirtableMappingRequest) SetMapping(v map[string]interface{}) {
	o.Mapping = v
}

func (o ConfigureAirtableMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureAirtableMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mapping"] = o.Mapping
	return toSerialize, nil
}

func (o *ConfigureAirtableMappingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mapping",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureAirtableMappingRequest := _ConfigureAirtableMappingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigureAirtableMappingRequest)

	if err != nil {
		return err
	}

	*o = ConfigureAirtableMappingRequest(varConfigureAirtableMappingRequest)

	return err
}

type NullableConfigureAirtableMappingRequest struct {
	value *ConfigureAirtableMappingRequest
	isSet bool
}

func (v NullableConfigureAirtableMappingRequest) Get() *ConfigureAirtableMappingRequest {
	return v.value
}

func (v *NullableConfigureAirtableMappingRequest) Set(val *ConfigureAirtableMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureAirtableMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureAirtableMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureAirtableMappingRequest(val *ConfigureAirtableMappingRequest) *NullableConfigureAirtableMappingRequest {
	return &NullableConfigureAirtableMappingRequest{value: val, isSet: true}
}

func (v NullableConfigureAirtableMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureAirtableMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


