/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the CrmMappingOptionsResponseOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrmMappingOptionsResponseOptions{}

// CrmMappingOptionsResponseOptions struct for CrmMappingOptionsResponseOptions
type CrmMappingOptionsResponseOptions struct {
	Objects []CrmMappingOptionsResponseOptionsObjectsInner `json:"objects"`
	Provider string `json:"provider"`
	AdditionalProperties map[string]interface{}
}

type _CrmMappingOptionsResponseOptions CrmMappingOptionsResponseOptions

// NewCrmMappingOptionsResponseOptions instantiates a new CrmMappingOptionsResponseOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrmMappingOptionsResponseOptions(objects []CrmMappingOptionsResponseOptionsObjectsInner, provider string) *CrmMappingOptionsResponseOptions {
	this := CrmMappingOptionsResponseOptions{}
	this.Objects = objects
	this.Provider = provider
	return &this
}

// NewCrmMappingOptionsResponseOptionsWithDefaults instantiates a new CrmMappingOptionsResponseOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrmMappingOptionsResponseOptionsWithDefaults() *CrmMappingOptionsResponseOptions {
	this := CrmMappingOptionsResponseOptions{}
	return &this
}

// GetObjects returns the Objects field value
func (o *CrmMappingOptionsResponseOptions) GetObjects() []CrmMappingOptionsResponseOptionsObjectsInner {
	if o == nil {
		var ret []CrmMappingOptionsResponseOptionsObjectsInner
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *CrmMappingOptionsResponseOptions) GetObjectsOk() ([]CrmMappingOptionsResponseOptionsObjectsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Objects, true
}

// SetObjects sets field value
func (o *CrmMappingOptionsResponseOptions) SetObjects(v []CrmMappingOptionsResponseOptionsObjectsInner) {
	o.Objects = v
}

// GetProvider returns the Provider field value
func (o *CrmMappingOptionsResponseOptions) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CrmMappingOptionsResponseOptions) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CrmMappingOptionsResponseOptions) SetProvider(v string) {
	o.Provider = v
}

func (o CrmMappingOptionsResponseOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrmMappingOptionsResponseOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objects"] = o.Objects
	toSerialize["provider"] = o.Provider

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrmMappingOptionsResponseOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objects",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrmMappingOptionsResponseOptions := _CrmMappingOptionsResponseOptions{}

	err = json.Unmarshal(data, &varCrmMappingOptionsResponseOptions)

	if err != nil {
		return err
	}

	*o = CrmMappingOptionsResponseOptions(varCrmMappingOptionsResponseOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "objects")
		delete(additionalProperties, "provider")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrmMappingOptionsResponseOptions struct {
	value *CrmMappingOptionsResponseOptions
	isSet bool
}

func (v NullableCrmMappingOptionsResponseOptions) Get() *CrmMappingOptionsResponseOptions {
	return v.value
}

func (v *NullableCrmMappingOptionsResponseOptions) Set(val *CrmMappingOptionsResponseOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCrmMappingOptionsResponseOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCrmMappingOptionsResponseOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrmMappingOptionsResponseOptions(val *CrmMappingOptionsResponseOptions) *NullableCrmMappingOptionsResponseOptions {
	return &NullableCrmMappingOptionsResponseOptions{value: val, isSet: true}
}

func (v NullableCrmMappingOptionsResponseOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrmMappingOptionsResponseOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


