/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPostCadencesRequestNodesInnerAnyOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostCadencesRequestNodesInnerAnyOf4{}

// MailPostCadencesRequestNodesInnerAnyOf4 struct for MailPostCadencesRequestNodesInnerAnyOf4
type MailPostCadencesRequestNodesInnerAnyOf4 struct {
	Condition MailPostCadencesRequestNodesInnerAnyOf4Condition `json:"condition"`
	FalseNodeId string `json:"falseNodeId" validate:"regexp=^[a-zA-Z0-9_-]{1\\,100}$"`
	Id string `json:"id" validate:"regexp=^[a-zA-Z0-9_-]{1\\,100}$"`
	Kind string `json:"kind"`
	Name string `json:"name"`
	TrueNodeId string `json:"trueNodeId" validate:"regexp=^[a-zA-Z0-9_-]{1\\,100}$"`
}

type _MailPostCadencesRequestNodesInnerAnyOf4 MailPostCadencesRequestNodesInnerAnyOf4

// NewMailPostCadencesRequestNodesInnerAnyOf4 instantiates a new MailPostCadencesRequestNodesInnerAnyOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostCadencesRequestNodesInnerAnyOf4(condition MailPostCadencesRequestNodesInnerAnyOf4Condition, falseNodeId string, id string, kind string, name string, trueNodeId string) *MailPostCadencesRequestNodesInnerAnyOf4 {
	this := MailPostCadencesRequestNodesInnerAnyOf4{}
	this.Condition = condition
	this.FalseNodeId = falseNodeId
	this.Id = id
	this.Kind = kind
	this.Name = name
	this.TrueNodeId = trueNodeId
	return &this
}

// NewMailPostCadencesRequestNodesInnerAnyOf4WithDefaults instantiates a new MailPostCadencesRequestNodesInnerAnyOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostCadencesRequestNodesInnerAnyOf4WithDefaults() *MailPostCadencesRequestNodesInnerAnyOf4 {
	this := MailPostCadencesRequestNodesInnerAnyOf4{}
	return &this
}

// GetCondition returns the Condition field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetCondition() MailPostCadencesRequestNodesInnerAnyOf4Condition {
	if o == nil {
		var ret MailPostCadencesRequestNodesInnerAnyOf4Condition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetConditionOk() (*MailPostCadencesRequestNodesInnerAnyOf4Condition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetCondition(v MailPostCadencesRequestNodesInnerAnyOf4Condition) {
	o.Condition = v
}

// GetFalseNodeId returns the FalseNodeId field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetFalseNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FalseNodeId
}

// GetFalseNodeIdOk returns a tuple with the FalseNodeId field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetFalseNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FalseNodeId, true
}

// SetFalseNodeId sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetFalseNodeId(v string) {
	o.FalseNodeId = v
}

// GetId returns the Id field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetName(v string) {
	o.Name = v
}

// GetTrueNodeId returns the TrueNodeId field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetTrueNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrueNodeId
}

// GetTrueNodeIdOk returns a tuple with the TrueNodeId field value
// and a boolean to check if the value has been set.
func (o *MailPostCadencesRequestNodesInnerAnyOf4) GetTrueNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrueNodeId, true
}

// SetTrueNodeId sets field value
func (o *MailPostCadencesRequestNodesInnerAnyOf4) SetTrueNodeId(v string) {
	o.TrueNodeId = v
}

func (o MailPostCadencesRequestNodesInnerAnyOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostCadencesRequestNodesInnerAnyOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition"] = o.Condition
	toSerialize["falseNodeId"] = o.FalseNodeId
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["trueNodeId"] = o.TrueNodeId
	return toSerialize, nil
}

func (o *MailPostCadencesRequestNodesInnerAnyOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition",
		"falseNodeId",
		"id",
		"kind",
		"name",
		"trueNodeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostCadencesRequestNodesInnerAnyOf4 := _MailPostCadencesRequestNodesInnerAnyOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostCadencesRequestNodesInnerAnyOf4)

	if err != nil {
		return err
	}

	*o = MailPostCadencesRequestNodesInnerAnyOf4(varMailPostCadencesRequestNodesInnerAnyOf4)

	return err
}

type NullableMailPostCadencesRequestNodesInnerAnyOf4 struct {
	value *MailPostCadencesRequestNodesInnerAnyOf4
	isSet bool
}

func (v NullableMailPostCadencesRequestNodesInnerAnyOf4) Get() *MailPostCadencesRequestNodesInnerAnyOf4 {
	return v.value
}

func (v *NullableMailPostCadencesRequestNodesInnerAnyOf4) Set(val *MailPostCadencesRequestNodesInnerAnyOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostCadencesRequestNodesInnerAnyOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostCadencesRequestNodesInnerAnyOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostCadencesRequestNodesInnerAnyOf4(val *MailPostCadencesRequestNodesInnerAnyOf4) *NullableMailPostCadencesRequestNodesInnerAnyOf4 {
	return &NullableMailPostCadencesRequestNodesInnerAnyOf4{value: val, isSet: true}
}

func (v NullableMailPostCadencesRequestNodesInnerAnyOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostCadencesRequestNodesInnerAnyOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


