/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the ProductDiscoverCompaniesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDiscoverCompaniesInput{}

// ProductDiscoverCompaniesInput struct for ProductDiscoverCompaniesInput
type ProductDiscoverCompaniesInput struct {
	Industry *string `json:"industry,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Location *string `json:"location,omitempty"`
	Query *string `json:"query,omitempty"`
}

// NewProductDiscoverCompaniesInput instantiates a new ProductDiscoverCompaniesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDiscoverCompaniesInput() *ProductDiscoverCompaniesInput {
	this := ProductDiscoverCompaniesInput{}
	var limit int32 = 25
	this.Limit = &limit
	var query string = ""
	this.Query = &query
	return &this
}

// NewProductDiscoverCompaniesInputWithDefaults instantiates a new ProductDiscoverCompaniesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDiscoverCompaniesInputWithDefaults() *ProductDiscoverCompaniesInput {
	this := ProductDiscoverCompaniesInput{}
	var limit int32 = 25
	this.Limit = &limit
	var query string = ""
	this.Query = &query
	return &this
}

// GetIndustry returns the Industry field value if set, zero value otherwise.
func (o *ProductDiscoverCompaniesInput) GetIndustry() string {
	if o == nil || IsNil(o.Industry) {
		var ret string
		return ret
	}
	return *o.Industry
}

// GetIndustryOk returns a tuple with the Industry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDiscoverCompaniesInput) GetIndustryOk() (*string, bool) {
	if o == nil || IsNil(o.Industry) {
		return nil, false
	}
	return o.Industry, true
}

// HasIndustry returns a boolean if a field has been set.
func (o *ProductDiscoverCompaniesInput) HasIndustry() bool {
	if o != nil && !IsNil(o.Industry) {
		return true
	}

	return false
}

// SetIndustry gets a reference to the given string and assigns it to the Industry field.
func (o *ProductDiscoverCompaniesInput) SetIndustry(v string) {
	o.Industry = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ProductDiscoverCompaniesInput) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDiscoverCompaniesInput) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ProductDiscoverCompaniesInput) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ProductDiscoverCompaniesInput) SetLimit(v int32) {
	o.Limit = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ProductDiscoverCompaniesInput) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDiscoverCompaniesInput) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ProductDiscoverCompaniesInput) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ProductDiscoverCompaniesInput) SetLocation(v string) {
	o.Location = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ProductDiscoverCompaniesInput) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDiscoverCompaniesInput) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ProductDiscoverCompaniesInput) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *ProductDiscoverCompaniesInput) SetQuery(v string) {
	o.Query = &v
}

func (o ProductDiscoverCompaniesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDiscoverCompaniesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Industry) {
		toSerialize["industry"] = o.Industry
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableProductDiscoverCompaniesInput struct {
	value *ProductDiscoverCompaniesInput
	isSet bool
}

func (v NullableProductDiscoverCompaniesInput) Get() *ProductDiscoverCompaniesInput {
	return v.value
}

func (v *NullableProductDiscoverCompaniesInput) Set(val *ProductDiscoverCompaniesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDiscoverCompaniesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDiscoverCompaniesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDiscoverCompaniesInput(val *ProductDiscoverCompaniesInput) *NullableProductDiscoverCompaniesInput {
	return &NullableProductDiscoverCompaniesInput{value: val, isSet: true}
}

func (v NullableProductDiscoverCompaniesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDiscoverCompaniesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


