/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ProductNamedResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductNamedResource{}

// ProductNamedResource struct for ProductNamedResource
type ProductNamedResource struct {
	CreatedAt time.Time `json:"createdAt"`
	Id string `json:"id"`
	Name string `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _ProductNamedResource ProductNamedResource

// NewProductNamedResource instantiates a new ProductNamedResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductNamedResource(createdAt time.Time, id string, name string, updatedAt time.Time) *ProductNamedResource {
	this := ProductNamedResource{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Name = name
	this.UpdatedAt = updatedAt
	return &this
}

// NewProductNamedResourceWithDefaults instantiates a new ProductNamedResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductNamedResourceWithDefaults() *ProductNamedResource {
	this := ProductNamedResource{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProductNamedResource) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProductNamedResource) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProductNamedResource) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *ProductNamedResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProductNamedResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProductNamedResource) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ProductNamedResource) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductNamedResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductNamedResource) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ProductNamedResource) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ProductNamedResource) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ProductNamedResource) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ProductNamedResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductNamedResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductNamedResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"id",
		"name",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductNamedResource := _ProductNamedResource{}

	err = json.Unmarshal(data, &varProductNamedResource)

	if err != nil {
		return err
	}

	*o = ProductNamedResource(varProductNamedResource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductNamedResource struct {
	value *ProductNamedResource
	isSet bool
}

func (v NullableProductNamedResource) Get() *ProductNamedResource {
	return v.value
}

func (v *NullableProductNamedResource) Set(val *ProductNamedResource) {
	v.value = val
	v.isSet = true
}

func (v NullableProductNamedResource) IsSet() bool {
	return v.isSet
}

func (v *NullableProductNamedResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductNamedResource(val *ProductNamedResource) *NullableProductNamedResource {
	return &NullableProductNamedResource{value: val, isSet: true}
}

func (v NullableProductNamedResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductNamedResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


