/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailPostInboxByMessageIdReplyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostInboxByMessageIdReplyRequest{}

// MailPostInboxByMessageIdReplyRequest struct for MailPostInboxByMessageIdReplyRequest
type MailPostInboxByMessageIdReplyRequest struct {
	ClientRequestId string `json:"clientRequestId"`
	Text string `json:"text"`
}

type _MailPostInboxByMessageIdReplyRequest MailPostInboxByMessageIdReplyRequest

// NewMailPostInboxByMessageIdReplyRequest instantiates a new MailPostInboxByMessageIdReplyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostInboxByMessageIdReplyRequest(clientRequestId string, text string) *MailPostInboxByMessageIdReplyRequest {
	this := MailPostInboxByMessageIdReplyRequest{}
	this.ClientRequestId = clientRequestId
	this.Text = text
	return &this
}

// NewMailPostInboxByMessageIdReplyRequestWithDefaults instantiates a new MailPostInboxByMessageIdReplyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostInboxByMessageIdReplyRequestWithDefaults() *MailPostInboxByMessageIdReplyRequest {
	this := MailPostInboxByMessageIdReplyRequest{}
	return &this
}

// GetClientRequestId returns the ClientRequestId field value
func (o *MailPostInboxByMessageIdReplyRequest) GetClientRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientRequestId
}

// GetClientRequestIdOk returns a tuple with the ClientRequestId field value
// and a boolean to check if the value has been set.
func (o *MailPostInboxByMessageIdReplyRequest) GetClientRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientRequestId, true
}

// SetClientRequestId sets field value
func (o *MailPostInboxByMessageIdReplyRequest) SetClientRequestId(v string) {
	o.ClientRequestId = v
}

// GetText returns the Text field value
func (o *MailPostInboxByMessageIdReplyRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *MailPostInboxByMessageIdReplyRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *MailPostInboxByMessageIdReplyRequest) SetText(v string) {
	o.Text = v
}

func (o MailPostInboxByMessageIdReplyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostInboxByMessageIdReplyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientRequestId"] = o.ClientRequestId
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *MailPostInboxByMessageIdReplyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clientRequestId",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostInboxByMessageIdReplyRequest := _MailPostInboxByMessageIdReplyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailPostInboxByMessageIdReplyRequest)

	if err != nil {
		return err
	}

	*o = MailPostInboxByMessageIdReplyRequest(varMailPostInboxByMessageIdReplyRequest)

	return err
}

type NullableMailPostInboxByMessageIdReplyRequest struct {
	value *MailPostInboxByMessageIdReplyRequest
	isSet bool
}

func (v NullableMailPostInboxByMessageIdReplyRequest) Get() *MailPostInboxByMessageIdReplyRequest {
	return v.value
}

func (v *NullableMailPostInboxByMessageIdReplyRequest) Set(val *MailPostInboxByMessageIdReplyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostInboxByMessageIdReplyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostInboxByMessageIdReplyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostInboxByMessageIdReplyRequest(val *MailPostInboxByMessageIdReplyRequest) *NullableMailPostInboxByMessageIdReplyRequest {
	return &NullableMailPostInboxByMessageIdReplyRequest{value: val, isSet: true}
}

func (v NullableMailPostInboxByMessageIdReplyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostInboxByMessageIdReplyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


