/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateLeadResponseLead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLeadResponseLead{}

// UpdateLeadResponseLead struct for UpdateLeadResponseLead
type UpdateLeadResponseLead struct {
	Company *CreateLeadRequestCompany `json:"company,omitempty"`
	CompanyId NullableString `json:"company_id,omitempty"`
	CreatedAt string `json:"created_at"`
	CreatedBy NullableString `json:"created_by"`
	Email string `json:"email"`
	Id string `json:"id"`
	LastActivityAt NullableString `json:"last_activity_at,omitempty"`
	LastContactedAt NullableString `json:"last_contacted_at,omitempty"`
	Person *CreateLeadRequestPerson `json:"person,omitempty"`
	Sync *GetLeadResponseLeadSync `json:"sync,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TeamId string `json:"team_id"`
	UpdatedAt string `json:"updated_at"`
	Verification *GetLeadResponseLeadVerification `json:"verification,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateLeadResponseLead UpdateLeadResponseLead

// NewUpdateLeadResponseLead instantiates a new UpdateLeadResponseLead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLeadResponseLead(createdAt string, createdBy NullableString, email string, id string, teamId string, updatedAt string) *UpdateLeadResponseLead {
	this := UpdateLeadResponseLead{}
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.Email = email
	this.Id = id
	this.TeamId = teamId
	this.UpdatedAt = updatedAt
	return &this
}

// NewUpdateLeadResponseLeadWithDefaults instantiates a new UpdateLeadResponseLead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLeadResponseLeadWithDefaults() *UpdateLeadResponseLead {
	this := UpdateLeadResponseLead{}
	return &this
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *UpdateLeadResponseLead) GetCompany() CreateLeadRequestCompany {
	if o == nil || IsNil(o.Company) {
		var ret CreateLeadRequestCompany
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetCompanyOk() (*CreateLeadRequestCompany, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given CreateLeadRequestCompany and assigns it to the Company field.
func (o *UpdateLeadResponseLead) SetCompany(v CreateLeadRequestCompany) {
	o.Company = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateLeadResponseLead) GetCompanyId() string {
	if o == nil || IsNil(o.CompanyId.Get()) {
		var ret string
		return ret
	}
	return *o.CompanyId.Get()
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateLeadResponseLead) GetCompanyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompanyId.Get(), o.CompanyId.IsSet()
}

// HasCompanyId returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasCompanyId() bool {
	if o != nil && o.CompanyId.IsSet() {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given NullableString and assigns it to the CompanyId field.
func (o *UpdateLeadResponseLead) SetCompanyId(v string) {
	o.CompanyId.Set(&v)
}
// SetCompanyIdNil sets the value for CompanyId to be an explicit nil
func (o *UpdateLeadResponseLead) SetCompanyIdNil() {
	o.CompanyId.Set(nil)
}

// UnsetCompanyId ensures that no value is present for CompanyId, not even an explicit nil
func (o *UpdateLeadResponseLead) UnsetCompanyId() {
	o.CompanyId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *UpdateLeadResponseLead) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UpdateLeadResponseLead) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateLeadResponseLead) GetCreatedBy() string {
	if o == nil || o.CreatedBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateLeadResponseLead) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// SetCreatedBy sets field value
func (o *UpdateLeadResponseLead) SetCreatedBy(v string) {
	o.CreatedBy.Set(&v)
}

// GetEmail returns the Email field value
func (o *UpdateLeadResponseLead) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UpdateLeadResponseLead) SetEmail(v string) {
	o.Email = v
}

// GetId returns the Id field value
func (o *UpdateLeadResponseLead) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateLeadResponseLead) SetId(v string) {
	o.Id = v
}

// GetLastActivityAt returns the LastActivityAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateLeadResponseLead) GetLastActivityAt() string {
	if o == nil || IsNil(o.LastActivityAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastActivityAt.Get()
}

// GetLastActivityAtOk returns a tuple with the LastActivityAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateLeadResponseLead) GetLastActivityAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastActivityAt.Get(), o.LastActivityAt.IsSet()
}

// HasLastActivityAt returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasLastActivityAt() bool {
	if o != nil && o.LastActivityAt.IsSet() {
		return true
	}

	return false
}

// SetLastActivityAt gets a reference to the given NullableString and assigns it to the LastActivityAt field.
func (o *UpdateLeadResponseLead) SetLastActivityAt(v string) {
	o.LastActivityAt.Set(&v)
}
// SetLastActivityAtNil sets the value for LastActivityAt to be an explicit nil
func (o *UpdateLeadResponseLead) SetLastActivityAtNil() {
	o.LastActivityAt.Set(nil)
}

// UnsetLastActivityAt ensures that no value is present for LastActivityAt, not even an explicit nil
func (o *UpdateLeadResponseLead) UnsetLastActivityAt() {
	o.LastActivityAt.Unset()
}

// GetLastContactedAt returns the LastContactedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateLeadResponseLead) GetLastContactedAt() string {
	if o == nil || IsNil(o.LastContactedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastContactedAt.Get()
}

// GetLastContactedAtOk returns a tuple with the LastContactedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateLeadResponseLead) GetLastContactedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastContactedAt.Get(), o.LastContactedAt.IsSet()
}

// HasLastContactedAt returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasLastContactedAt() bool {
	if o != nil && o.LastContactedAt.IsSet() {
		return true
	}

	return false
}

// SetLastContactedAt gets a reference to the given NullableString and assigns it to the LastContactedAt field.
func (o *UpdateLeadResponseLead) SetLastContactedAt(v string) {
	o.LastContactedAt.Set(&v)
}
// SetLastContactedAtNil sets the value for LastContactedAt to be an explicit nil
func (o *UpdateLeadResponseLead) SetLastContactedAtNil() {
	o.LastContactedAt.Set(nil)
}

// UnsetLastContactedAt ensures that no value is present for LastContactedAt, not even an explicit nil
func (o *UpdateLeadResponseLead) UnsetLastContactedAt() {
	o.LastContactedAt.Unset()
}

// GetPerson returns the Person field value if set, zero value otherwise.
func (o *UpdateLeadResponseLead) GetPerson() CreateLeadRequestPerson {
	if o == nil || IsNil(o.Person) {
		var ret CreateLeadRequestPerson
		return ret
	}
	return *o.Person
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetPersonOk() (*CreateLeadRequestPerson, bool) {
	if o == nil || IsNil(o.Person) {
		return nil, false
	}
	return o.Person, true
}

// HasPerson returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasPerson() bool {
	if o != nil && !IsNil(o.Person) {
		return true
	}

	return false
}

// SetPerson gets a reference to the given CreateLeadRequestPerson and assigns it to the Person field.
func (o *UpdateLeadResponseLead) SetPerson(v CreateLeadRequestPerson) {
	o.Person = &v
}

// GetSync returns the Sync field value if set, zero value otherwise.
func (o *UpdateLeadResponseLead) GetSync() GetLeadResponseLeadSync {
	if o == nil || IsNil(o.Sync) {
		var ret GetLeadResponseLeadSync
		return ret
	}
	return *o.Sync
}

// GetSyncOk returns a tuple with the Sync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetSyncOk() (*GetLeadResponseLeadSync, bool) {
	if o == nil || IsNil(o.Sync) {
		return nil, false
	}
	return o.Sync, true
}

// HasSync returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasSync() bool {
	if o != nil && !IsNil(o.Sync) {
		return true
	}

	return false
}

// SetSync gets a reference to the given GetLeadResponseLeadSync and assigns it to the Sync field.
func (o *UpdateLeadResponseLead) SetSync(v GetLeadResponseLeadSync) {
	o.Sync = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UpdateLeadResponseLead) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *UpdateLeadResponseLead) SetTags(v []string) {
	o.Tags = v
}

// GetTeamId returns the TeamId field value
func (o *UpdateLeadResponseLead) GetTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *UpdateLeadResponseLead) SetTeamId(v string) {
	o.TeamId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UpdateLeadResponseLead) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UpdateLeadResponseLead) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetVerification returns the Verification field value if set, zero value otherwise.
func (o *UpdateLeadResponseLead) GetVerification() GetLeadResponseLeadVerification {
	if o == nil || IsNil(o.Verification) {
		var ret GetLeadResponseLeadVerification
		return ret
	}
	return *o.Verification
}

// GetVerificationOk returns a tuple with the Verification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLeadResponseLead) GetVerificationOk() (*GetLeadResponseLeadVerification, bool) {
	if o == nil || IsNil(o.Verification) {
		return nil, false
	}
	return o.Verification, true
}

// HasVerification returns a boolean if a field has been set.
func (o *UpdateLeadResponseLead) HasVerification() bool {
	if o != nil && !IsNil(o.Verification) {
		return true
	}

	return false
}

// SetVerification gets a reference to the given GetLeadResponseLeadVerification and assigns it to the Verification field.
func (o *UpdateLeadResponseLead) SetVerification(v GetLeadResponseLeadVerification) {
	o.Verification = &v
}

func (o UpdateLeadResponseLead) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLeadResponseLead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if o.CompanyId.IsSet() {
		toSerialize["company_id"] = o.CompanyId.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["created_by"] = o.CreatedBy.Get()
	toSerialize["email"] = o.Email
	toSerialize["id"] = o.Id
	if o.LastActivityAt.IsSet() {
		toSerialize["last_activity_at"] = o.LastActivityAt.Get()
	}
	if o.LastContactedAt.IsSet() {
		toSerialize["last_contacted_at"] = o.LastContactedAt.Get()
	}
	if !IsNil(o.Person) {
		toSerialize["person"] = o.Person
	}
	if !IsNil(o.Sync) {
		toSerialize["sync"] = o.Sync
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["team_id"] = o.TeamId
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Verification) {
		toSerialize["verification"] = o.Verification
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateLeadResponseLead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"created_by",
		"email",
		"id",
		"team_id",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateLeadResponseLead := _UpdateLeadResponseLead{}

	err = json.Unmarshal(data, &varUpdateLeadResponseLead)

	if err != nil {
		return err
	}

	*o = UpdateLeadResponseLead(varUpdateLeadResponseLead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "company")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "email")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_activity_at")
		delete(additionalProperties, "last_contacted_at")
		delete(additionalProperties, "person")
		delete(additionalProperties, "sync")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "team_id")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "verification")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateLeadResponseLead struct {
	value *UpdateLeadResponseLead
	isSet bool
}

func (v NullableUpdateLeadResponseLead) Get() *UpdateLeadResponseLead {
	return v.value
}

func (v *NullableUpdateLeadResponseLead) Set(val *UpdateLeadResponseLead) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLeadResponseLead) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLeadResponseLead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLeadResponseLead(val *UpdateLeadResponseLead) *NullableUpdateLeadResponseLead {
	return &NullableUpdateLeadResponseLead{value: val, isSet: true}
}

func (v NullableUpdateLeadResponseLead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLeadResponseLead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


