/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailGetCampaignProgressResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailGetCampaignProgressResponse200{}

// MailGetCampaignProgressResponse200 struct for MailGetCampaignProgressResponse200
type MailGetCampaignProgressResponse200 struct {
	Results []MailCampaignProgress `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _MailGetCampaignProgressResponse200 MailGetCampaignProgressResponse200

// NewMailGetCampaignProgressResponse200 instantiates a new MailGetCampaignProgressResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailGetCampaignProgressResponse200(results []MailCampaignProgress) *MailGetCampaignProgressResponse200 {
	this := MailGetCampaignProgressResponse200{}
	this.Results = results
	return &this
}

// NewMailGetCampaignProgressResponse200WithDefaults instantiates a new MailGetCampaignProgressResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailGetCampaignProgressResponse200WithDefaults() *MailGetCampaignProgressResponse200 {
	this := MailGetCampaignProgressResponse200{}
	return &this
}

// GetResults returns the Results field value
func (o *MailGetCampaignProgressResponse200) GetResults() []MailCampaignProgress {
	if o == nil {
		var ret []MailCampaignProgress
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *MailGetCampaignProgressResponse200) GetResultsOk() ([]MailCampaignProgress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *MailGetCampaignProgressResponse200) SetResults(v []MailCampaignProgress) {
	o.Results = v
}

func (o MailGetCampaignProgressResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailGetCampaignProgressResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailGetCampaignProgressResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailGetCampaignProgressResponse200 := _MailGetCampaignProgressResponse200{}

	err = json.Unmarshal(data, &varMailGetCampaignProgressResponse200)

	if err != nil {
		return err
	}

	*o = MailGetCampaignProgressResponse200(varMailGetCampaignProgressResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailGetCampaignProgressResponse200 struct {
	value *MailGetCampaignProgressResponse200
	isSet bool
}

func (v NullableMailGetCampaignProgressResponse200) Get() *MailGetCampaignProgressResponse200 {
	return v.value
}

func (v *NullableMailGetCampaignProgressResponse200) Set(val *MailGetCampaignProgressResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailGetCampaignProgressResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailGetCampaignProgressResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailGetCampaignProgressResponse200(val *MailGetCampaignProgressResponse200) *NullableMailGetCampaignProgressResponse200 {
	return &NullableMailGetCampaignProgressResponse200{value: val, isSet: true}
}

func (v NullableMailGetCampaignProgressResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailGetCampaignProgressResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


