/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigureWebflowFormRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureWebflowFormRequest{}

// ConfigureWebflowFormRequest struct for ConfigureWebflowFormRequest
type ConfigureWebflowFormRequest struct {
	AccessToken string `json:"accessToken"`
	Capability string `json:"capability"`
	FieldMapping map[string]string `json:"fieldMapping"`
	FormId string `json:"formId"`
	Label string `json:"label"`
	Mode *string `json:"mode,omitempty"`
	SiteId string `json:"siteId"`
}

type _ConfigureWebflowFormRequest ConfigureWebflowFormRequest

// NewConfigureWebflowFormRequest instantiates a new ConfigureWebflowFormRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureWebflowFormRequest(accessToken string, capability string, fieldMapping map[string]string, formId string, label string, siteId string) *ConfigureWebflowFormRequest {
	this := ConfigureWebflowFormRequest{}
	this.AccessToken = accessToken
	this.Capability = capability
	this.FieldMapping = fieldMapping
	this.FormId = formId
	this.Label = label
	this.SiteId = siteId
	return &this
}

// NewConfigureWebflowFormRequestWithDefaults instantiates a new ConfigureWebflowFormRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureWebflowFormRequestWithDefaults() *ConfigureWebflowFormRequest {
	this := ConfigureWebflowFormRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *ConfigureWebflowFormRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *ConfigureWebflowFormRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetCapability returns the Capability field value
func (o *ConfigureWebflowFormRequest) GetCapability() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Capability
}

// GetCapabilityOk returns a tuple with the Capability field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetCapabilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capability, true
}

// SetCapability sets field value
func (o *ConfigureWebflowFormRequest) SetCapability(v string) {
	o.Capability = v
}

// GetFieldMapping returns the FieldMapping field value
func (o *ConfigureWebflowFormRequest) GetFieldMapping() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.FieldMapping
}

// GetFieldMappingOk returns a tuple with the FieldMapping field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetFieldMappingOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldMapping, true
}

// SetFieldMapping sets field value
func (o *ConfigureWebflowFormRequest) SetFieldMapping(v map[string]string) {
	o.FieldMapping = v
}

// GetFormId returns the FormId field value
func (o *ConfigureWebflowFormRequest) GetFormId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FormId
}

// GetFormIdOk returns a tuple with the FormId field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetFormIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormId, true
}

// SetFormId sets field value
func (o *ConfigureWebflowFormRequest) SetFormId(v string) {
	o.FormId = v
}

// GetLabel returns the Label field value
func (o *ConfigureWebflowFormRequest) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ConfigureWebflowFormRequest) SetLabel(v string) {
	o.Label = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *ConfigureWebflowFormRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *ConfigureWebflowFormRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *ConfigureWebflowFormRequest) SetMode(v string) {
	o.Mode = &v
}

// GetSiteId returns the SiteId field value
func (o *ConfigureWebflowFormRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ConfigureWebflowFormRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ConfigureWebflowFormRequest) SetSiteId(v string) {
	o.SiteId = v
}

func (o ConfigureWebflowFormRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureWebflowFormRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessToken"] = o.AccessToken
	toSerialize["capability"] = o.Capability
	toSerialize["fieldMapping"] = o.FieldMapping
	toSerialize["formId"] = o.FormId
	toSerialize["label"] = o.Label
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *ConfigureWebflowFormRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessToken",
		"capability",
		"fieldMapping",
		"formId",
		"label",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureWebflowFormRequest := _ConfigureWebflowFormRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigureWebflowFormRequest)

	if err != nil {
		return err
	}

	*o = ConfigureWebflowFormRequest(varConfigureWebflowFormRequest)

	return err
}

type NullableConfigureWebflowFormRequest struct {
	value *ConfigureWebflowFormRequest
	isSet bool
}

func (v NullableConfigureWebflowFormRequest) Get() *ConfigureWebflowFormRequest {
	return v.value
}

func (v *NullableConfigureWebflowFormRequest) Set(val *ConfigureWebflowFormRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureWebflowFormRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureWebflowFormRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureWebflowFormRequest(val *ConfigureWebflowFormRequest) *NullableConfigureWebflowFormRequest {
	return &NullableConfigureWebflowFormRequest{value: val, isSet: true}
}

func (v NullableConfigureWebflowFormRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureWebflowFormRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


