/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the IntegrationOAuthStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationOAuthStartResponse{}

// IntegrationOAuthStartResponse struct for IntegrationOAuthStartResponse
type IntegrationOAuthStartResponse struct {
	AuthorizationUrl string `json:"authorizationUrl"`
	ExpiresAt time.Time `json:"expiresAt"`
	AdditionalProperties map[string]interface{}
}

type _IntegrationOAuthStartResponse IntegrationOAuthStartResponse

// NewIntegrationOAuthStartResponse instantiates a new IntegrationOAuthStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationOAuthStartResponse(authorizationUrl string, expiresAt time.Time) *IntegrationOAuthStartResponse {
	this := IntegrationOAuthStartResponse{}
	this.AuthorizationUrl = authorizationUrl
	this.ExpiresAt = expiresAt
	return &this
}

// NewIntegrationOAuthStartResponseWithDefaults instantiates a new IntegrationOAuthStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationOAuthStartResponseWithDefaults() *IntegrationOAuthStartResponse {
	this := IntegrationOAuthStartResponse{}
	return &this
}

// GetAuthorizationUrl returns the AuthorizationUrl field value
func (o *IntegrationOAuthStartResponse) GetAuthorizationUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizationUrl
}

// GetAuthorizationUrlOk returns a tuple with the AuthorizationUrl field value
// and a boolean to check if the value has been set.
func (o *IntegrationOAuthStartResponse) GetAuthorizationUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizationUrl, true
}

// SetAuthorizationUrl sets field value
func (o *IntegrationOAuthStartResponse) SetAuthorizationUrl(v string) {
	o.AuthorizationUrl = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *IntegrationOAuthStartResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *IntegrationOAuthStartResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *IntegrationOAuthStartResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o IntegrationOAuthStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationOAuthStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorizationUrl"] = o.AuthorizationUrl
	toSerialize["expiresAt"] = o.ExpiresAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IntegrationOAuthStartResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authorizationUrl",
		"expiresAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationOAuthStartResponse := _IntegrationOAuthStartResponse{}

	err = json.Unmarshal(data, &varIntegrationOAuthStartResponse)

	if err != nil {
		return err
	}

	*o = IntegrationOAuthStartResponse(varIntegrationOAuthStartResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authorizationUrl")
		delete(additionalProperties, "expiresAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIntegrationOAuthStartResponse struct {
	value *IntegrationOAuthStartResponse
	isSet bool
}

func (v NullableIntegrationOAuthStartResponse) Get() *IntegrationOAuthStartResponse {
	return v.value
}

func (v *NullableIntegrationOAuthStartResponse) Set(val *IntegrationOAuthStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationOAuthStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationOAuthStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationOAuthStartResponse(val *IntegrationOAuthStartResponse) *NullableIntegrationOAuthStartResponse {
	return &NullableIntegrationOAuthStartResponse{value: val, isSet: true}
}

func (v NullableIntegrationOAuthStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationOAuthStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


