/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
)

// checks if the InsightSocialProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsightSocialProfile{}

// InsightSocialProfile struct for InsightSocialProfile
type InsightSocialProfile struct {
	Handle *string `json:"handle,omitempty"`
	Platform *string `json:"platform,omitempty"`
	Url *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InsightSocialProfile InsightSocialProfile

// NewInsightSocialProfile instantiates a new InsightSocialProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsightSocialProfile() *InsightSocialProfile {
	this := InsightSocialProfile{}
	return &this
}

// NewInsightSocialProfileWithDefaults instantiates a new InsightSocialProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsightSocialProfileWithDefaults() *InsightSocialProfile {
	this := InsightSocialProfile{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *InsightSocialProfile) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightSocialProfile) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *InsightSocialProfile) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *InsightSocialProfile) SetHandle(v string) {
	o.Handle = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *InsightSocialProfile) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightSocialProfile) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *InsightSocialProfile) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *InsightSocialProfile) SetPlatform(v string) {
	o.Platform = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *InsightSocialProfile) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightSocialProfile) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *InsightSocialProfile) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *InsightSocialProfile) SetUrl(v string) {
	o.Url = &v
}

func (o InsightSocialProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsightSocialProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InsightSocialProfile) UnmarshalJSON(data []byte) (err error) {
	varInsightSocialProfile := _InsightSocialProfile{}

	err = json.Unmarshal(data, &varInsightSocialProfile)

	if err != nil {
		return err
	}

	*o = InsightSocialProfile(varInsightSocialProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "handle")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInsightSocialProfile struct {
	value *InsightSocialProfile
	isSet bool
}

func (v NullableInsightSocialProfile) Get() *InsightSocialProfile {
	return v.value
}

func (v *NullableInsightSocialProfile) Set(val *InsightSocialProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableInsightSocialProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableInsightSocialProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsightSocialProfile(val *InsightSocialProfile) *NullableInsightSocialProfile {
	return &NullableInsightSocialProfile{value: val, isSet: true}
}

func (v NullableInsightSocialProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsightSocialProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


