/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailCadenceNodeAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailCadenceNodeAnyOf1{}

// MailCadenceNodeAnyOf1 struct for MailCadenceNodeAnyOf1
type MailCadenceNodeAnyOf1 struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Channel string `json:"channel"`
	Experiment *MailCadenceMessageExperiment `json:"experiment,omitempty"`
	Kind string `json:"kind"`
	NextNodeId string `json:"nextNodeId"`
	TemplateId string `json:"templateId"`
	TemplateVersion float32 `json:"templateVersion"`
	AdditionalProperties map[string]interface{}
}

type _MailCadenceNodeAnyOf1 MailCadenceNodeAnyOf1

// NewMailCadenceNodeAnyOf1 instantiates a new MailCadenceNodeAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailCadenceNodeAnyOf1(id string, name string, channel string, kind string, nextNodeId string, templateId string, templateVersion float32) *MailCadenceNodeAnyOf1 {
	this := MailCadenceNodeAnyOf1{}
	this.Id = id
	this.Name = name
	this.Channel = channel
	this.Kind = kind
	this.NextNodeId = nextNodeId
	this.TemplateId = templateId
	this.TemplateVersion = templateVersion
	return &this
}

// NewMailCadenceNodeAnyOf1WithDefaults instantiates a new MailCadenceNodeAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailCadenceNodeAnyOf1WithDefaults() *MailCadenceNodeAnyOf1 {
	this := MailCadenceNodeAnyOf1{}
	return &this
}

// GetId returns the Id field value
func (o *MailCadenceNodeAnyOf1) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MailCadenceNodeAnyOf1) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MailCadenceNodeAnyOf1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailCadenceNodeAnyOf1) SetName(v string) {
	o.Name = v
}

// GetChannel returns the Channel field value
func (o *MailCadenceNodeAnyOf1) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *MailCadenceNodeAnyOf1) SetChannel(v string) {
	o.Channel = v
}

// GetExperiment returns the Experiment field value if set, zero value otherwise.
func (o *MailCadenceNodeAnyOf1) GetExperiment() MailCadenceMessageExperiment {
	if o == nil || IsNil(o.Experiment) {
		var ret MailCadenceMessageExperiment
		return ret
	}
	return *o.Experiment
}

// GetExperimentOk returns a tuple with the Experiment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetExperimentOk() (*MailCadenceMessageExperiment, bool) {
	if o == nil || IsNil(o.Experiment) {
		return nil, false
	}
	return o.Experiment, true
}

// HasExperiment returns a boolean if a field has been set.
func (o *MailCadenceNodeAnyOf1) HasExperiment() bool {
	if o != nil && !IsNil(o.Experiment) {
		return true
	}

	return false
}

// SetExperiment gets a reference to the given MailCadenceMessageExperiment and assigns it to the Experiment field.
func (o *MailCadenceNodeAnyOf1) SetExperiment(v MailCadenceMessageExperiment) {
	o.Experiment = &v
}

// GetKind returns the Kind field value
func (o *MailCadenceNodeAnyOf1) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MailCadenceNodeAnyOf1) SetKind(v string) {
	o.Kind = v
}

// GetNextNodeId returns the NextNodeId field value
func (o *MailCadenceNodeAnyOf1) GetNextNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextNodeId
}

// GetNextNodeIdOk returns a tuple with the NextNodeId field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetNextNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextNodeId, true
}

// SetNextNodeId sets field value
func (o *MailCadenceNodeAnyOf1) SetNextNodeId(v string) {
	o.NextNodeId = v
}

// GetTemplateId returns the TemplateId field value
func (o *MailCadenceNodeAnyOf1) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *MailCadenceNodeAnyOf1) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetTemplateVersion returns the TemplateVersion field value
func (o *MailCadenceNodeAnyOf1) GetTemplateVersion() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TemplateVersion
}

// GetTemplateVersionOk returns a tuple with the TemplateVersion field value
// and a boolean to check if the value has been set.
func (o *MailCadenceNodeAnyOf1) GetTemplateVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateVersion, true
}

// SetTemplateVersion sets field value
func (o *MailCadenceNodeAnyOf1) SetTemplateVersion(v float32) {
	o.TemplateVersion = v
}

func (o MailCadenceNodeAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailCadenceNodeAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["channel"] = o.Channel
	if !IsNil(o.Experiment) {
		toSerialize["experiment"] = o.Experiment
	}
	toSerialize["kind"] = o.Kind
	toSerialize["nextNodeId"] = o.NextNodeId
	toSerialize["templateId"] = o.TemplateId
	toSerialize["templateVersion"] = o.TemplateVersion

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailCadenceNodeAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"channel",
		"kind",
		"nextNodeId",
		"templateId",
		"templateVersion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailCadenceNodeAnyOf1 := _MailCadenceNodeAnyOf1{}

	err = json.Unmarshal(data, &varMailCadenceNodeAnyOf1)

	if err != nil {
		return err
	}

	*o = MailCadenceNodeAnyOf1(varMailCadenceNodeAnyOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "experiment")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "nextNodeId")
		delete(additionalProperties, "templateId")
		delete(additionalProperties, "templateVersion")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailCadenceNodeAnyOf1 struct {
	value *MailCadenceNodeAnyOf1
	isSet bool
}

func (v NullableMailCadenceNodeAnyOf1) Get() *MailCadenceNodeAnyOf1 {
	return v.value
}

func (v *NullableMailCadenceNodeAnyOf1) Set(val *MailCadenceNodeAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableMailCadenceNodeAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableMailCadenceNodeAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailCadenceNodeAnyOf1(val *MailCadenceNodeAnyOf1) *NullableMailCadenceNodeAnyOf1 {
	return &NullableMailCadenceNodeAnyOf1{value: val, isSet: true}
}

func (v NullableMailCadenceNodeAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailCadenceNodeAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


