/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateFreshsalesCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateFreshsalesCredentialRequest{}

// RotateFreshsalesCredentialRequest struct for RotateFreshsalesCredentialRequest
type RotateFreshsalesCredentialRequest struct {
	ApiKey string `json:"apiKey"`
}

type _RotateFreshsalesCredentialRequest RotateFreshsalesCredentialRequest

// NewRotateFreshsalesCredentialRequest instantiates a new RotateFreshsalesCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateFreshsalesCredentialRequest(apiKey string) *RotateFreshsalesCredentialRequest {
	this := RotateFreshsalesCredentialRequest{}
	this.ApiKey = apiKey
	return &this
}

// NewRotateFreshsalesCredentialRequestWithDefaults instantiates a new RotateFreshsalesCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateFreshsalesCredentialRequestWithDefaults() *RotateFreshsalesCredentialRequest {
	this := RotateFreshsalesCredentialRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *RotateFreshsalesCredentialRequest) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *RotateFreshsalesCredentialRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *RotateFreshsalesCredentialRequest) SetApiKey(v string) {
	o.ApiKey = v
}

func (o RotateFreshsalesCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateFreshsalesCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKey"] = o.ApiKey
	return toSerialize, nil
}

func (o *RotateFreshsalesCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateFreshsalesCredentialRequest := _RotateFreshsalesCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateFreshsalesCredentialRequest)

	if err != nil {
		return err
	}

	*o = RotateFreshsalesCredentialRequest(varRotateFreshsalesCredentialRequest)

	return err
}

type NullableRotateFreshsalesCredentialRequest struct {
	value *RotateFreshsalesCredentialRequest
	isSet bool
}

func (v NullableRotateFreshsalesCredentialRequest) Get() *RotateFreshsalesCredentialRequest {
	return v.value
}

func (v *NullableRotateFreshsalesCredentialRequest) Set(val *RotateFreshsalesCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateFreshsalesCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateFreshsalesCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateFreshsalesCredentialRequest(val *RotateFreshsalesCredentialRequest) *NullableRotateFreshsalesCredentialRequest {
	return &NullableRotateFreshsalesCredentialRequest{value: val, isSet: true}
}

func (v NullableRotateFreshsalesCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateFreshsalesCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


