/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200{}

// MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 struct for MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200
type MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 struct {
	Health MailMailboxHealthRecord `json:"health"`
	AdditionalProperties map[string]interface{}
}

type _MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200

// NewMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 instantiates a new MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200(health MailMailboxHealthRecord) *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
	this := MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200{}
	this.Health = health
	return &this
}

// NewMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200WithDefaults instantiates a new MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200WithDefaults() *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
	this := MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200{}
	return &this
}

// GetHealth returns the Health field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) GetHealth() MailMailboxHealthRecord {
	if o == nil {
		var ret MailMailboxHealthRecord
		return ret
	}

	return o.Health
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
func (o *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) GetHealthOk() (*MailMailboxHealthRecord, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Health, true
}

// SetHealth sets field value
func (o *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) SetHealth(v MailMailboxHealthRecord) {
	o.Health = v
}

func (o MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["health"] = o.Health

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"health",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 := _MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200{}

	err = json.Unmarshal(data, &varMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200)

	if err != nil {
		return err
	}

	*o = MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200(varMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "health")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 struct {
	value *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200
	isSet bool
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) Get() *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
	return v.value
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) Set(val *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200(val *MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) *NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
	return &NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200{value: val, isSet: true}
}

func (v NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


