/*
Reacon API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacon

import (
	"encoding/json"
	"fmt"
)

// checks if the MailPostPortfolioTeamsResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPostPortfolioTeamsResponse200{}

// MailPostPortfolioTeamsResponse200 struct for MailPostPortfolioTeamsResponse200
type MailPostPortfolioTeamsResponse200 struct {
	Team MailMailPortfolioTeam `json:"team"`
	AdditionalProperties map[string]interface{}
}

type _MailPostPortfolioTeamsResponse200 MailPostPortfolioTeamsResponse200

// NewMailPostPortfolioTeamsResponse200 instantiates a new MailPostPortfolioTeamsResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPostPortfolioTeamsResponse200(team MailMailPortfolioTeam) *MailPostPortfolioTeamsResponse200 {
	this := MailPostPortfolioTeamsResponse200{}
	this.Team = team
	return &this
}

// NewMailPostPortfolioTeamsResponse200WithDefaults instantiates a new MailPostPortfolioTeamsResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPostPortfolioTeamsResponse200WithDefaults() *MailPostPortfolioTeamsResponse200 {
	this := MailPostPortfolioTeamsResponse200{}
	return &this
}

// GetTeam returns the Team field value
func (o *MailPostPortfolioTeamsResponse200) GetTeam() MailMailPortfolioTeam {
	if o == nil {
		var ret MailMailPortfolioTeam
		return ret
	}

	return o.Team
}

// GetTeamOk returns a tuple with the Team field value
// and a boolean to check if the value has been set.
func (o *MailPostPortfolioTeamsResponse200) GetTeamOk() (*MailMailPortfolioTeam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Team, true
}

// SetTeam sets field value
func (o *MailPostPortfolioTeamsResponse200) SetTeam(v MailMailPortfolioTeam) {
	o.Team = v
}

func (o MailPostPortfolioTeamsResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPostPortfolioTeamsResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["team"] = o.Team

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailPostPortfolioTeamsResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"team",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailPostPortfolioTeamsResponse200 := _MailPostPortfolioTeamsResponse200{}

	err = json.Unmarshal(data, &varMailPostPortfolioTeamsResponse200)

	if err != nil {
		return err
	}

	*o = MailPostPortfolioTeamsResponse200(varMailPostPortfolioTeamsResponse200)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "team")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailPostPortfolioTeamsResponse200 struct {
	value *MailPostPortfolioTeamsResponse200
	isSet bool
}

func (v NullableMailPostPortfolioTeamsResponse200) Get() *MailPostPortfolioTeamsResponse200 {
	return v.value
}

func (v *NullableMailPostPortfolioTeamsResponse200) Set(val *MailPostPortfolioTeamsResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPostPortfolioTeamsResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPostPortfolioTeamsResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPostPortfolioTeamsResponse200(val *MailPostPortfolioTeamsResponse200) *NullableMailPostPortfolioTeamsResponse200 {
	return &NullableMailPostPortfolioTeamsResponse200{value: val, isSet: true}
}

func (v NullableMailPostPortfolioTeamsResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPostPortfolioTeamsResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


